### ISSUE TITLE
Importar fichero csv

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#10]
Estudiar cómo importar en php el contenido de un fichero CSV en la BD

**Comment by profeIAP** [comment]
Una cosa cada vez

**Comment by FranGarciaCo** [comment]
Ya puedo cogerla de nuevo no @profeIAP

**Comment by profeIAP** [comment]
Poder, puedes pero... sospecho que la "soltarás" pronto XD

**Comment by FranGarciaCo** [comment]
El motín se acerca... Si incluso he hecho el exportar... :(((

**Comment by profeIAP** [comment]
Perooo... ¿lo has hecho en PHP como indica el enunciado de la tarea?

**Comment by FranGarciaCo** [comment]
No, en PHP no, no lo leí. Lo haré desde ese punto de vista.

**Comment by profeIAP** [comment]
Genial, estamos deseando ver tus evoluciones en esta materia :)

**Comment by FranGarciaCo** [comment]
Acabo de subir la plantilla con la función Importar, espero que vaya bien. La cierras si consideras que he finalizado la tarea.

**Comment by profeIAP** [comment]
A pesar de los pesares, daremos por buena la tarea.

Aunque no lo parezca @FranPeroNoMoreno, has hecho un gran trabajo ¡Enhorabuena!
