### ISSUE TITLE
Exportar logo a formato SVG

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#101]
Convertir a formato SVG el logo del proyecto para poder escalarlo a cualquier tamaño.

Una posible herramienta sería [IMG2SVG](https://andalinux.wordpress.com/2012/01/30/convertir-cualquier-imagen-a-svg-online/)

**Comment by profeIAP** [comment]
Por favor, no acapares tareas

**Comment by jasvazquez** [comment]
Pablo, aunque te agradezco que hayas documentado cómo se hace, el objetivo era pasar el logotipo del proyecto a SVG.

Cuando lo tengas cuélgalo aquí mismo y/o me lo compartes por Drive.

Gracias

**Comment by profeIAP** [comment]
Ni lo has subido ni me lo has compartido... reabro la tarea.

**Comment by pablosaborido** [comment]
como se comparte?

**Comment by profeIAP** [comment]
Puedes: 
- subirlo a Google Drive (y compartírmelo como hasta ahora)
- Utilizar la opción de subir ficheros a una tarea en GitHub (explicado en la tarea #98)
- Incluirlo en la [carpeta **img** del proyecto](https://github.com/profeIAP/proyecto2015-16/tree/058c02f9d6d0cb81a3b37c9fe0e4ad0ed052ed06/img) y subirlo al repositorio

**Comment by pablosaborido** [comment]
ya esta en drive

**Comment by profeIAP** [comment]
Estará pero, has olvidado compartirlo conmigo :P

**Comment by pablosaborido** [comment]
ya esta arreglao!!!

**Comment by profeIAP** [comment]
Ahora sí... gracias Pablo (en esta ocasión no diré "buen" trabajo porque no me recortaste la imagen como te pedí :P)

**Comment by profeIAP** [comment]
Dejo aquí [el enlace al logotipo](https://drive.google.com/file/d/0B7C0XACByqOOSmNxR1V2UjVFR2M/view?usp=sharing) para que pueda ser usado por cualquier integrante del equipo
