### ISSUE TITLE
Crear "chuleta" del uso Git en la wiki

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#102]
Añadir a la wiki del proyecto los comandos que debe utilizarse para las tareas habituales de GIT.

Sería interesante fusionar los contenidos de las wikis creadas por 
1. [Proyecto Pártete](https://github.com/pablosaborido/informatica-2bach-c/wiki)
2. El [profesor](https://github.com/profeIAP/plantillaWEB/wiki)

**Comment by javierfl98** [comment]
tarea realizada

**Comment by profeIAP** [comment]
Ha quedado muy bien Javier pero:
1. hay un pequeño fallo en los encabezados
   ![captura de pantalla de 2016-04-06 11 22 36](https://cloud.githubusercontent.com/assets/16881846/14311864/e36966e8-fbe9-11e5-98c4-ac4daea3ae51.png)
2. Yo incluiría el uso de `git pull` en el apdo. _Actualización_ (si tienes suerte y te puedes actualizar tu copia local sin hacer merge, mejor ¿no te parece? ;) )

**Comment by javierfl98** [comment]
He incluido el comando git pull en el wiki

**Comment by profeIAP** [comment]
Perfecto Javi, gracias.
