### ISSUE TITLE
Renombrar formulario parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#103]
@javierfl98 lo ha subido como view/contacto.php en lugar de view/parte.php

Basta cambiar nombre y subir a git

**Comment by danigomez99** [comment]
Maestro esta tarea ya está finalizada.

**Comment by profeIAP** [comment]
Recuerda subir el código al repositorio para poder dar por cerrada la tarea

**Comment by danigomez99** [comment]
Ya está en el respositorio. Voy a cerrar la tarea.

**Comment by profeIAP** [comment]
La que has liado con la apertura/cierre de la tarea XD.

Está perfecto, gracias Dani
