### ISSUE TITLE
Añadir favicon al proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#104]
Se echa de menos [un icono propio del proyecto](https://es.wikipedia.org/wiki/Favicon).

La idea es buscar uno que pueda estar relacionado con la temática de nuestra web e incluirlo en layout.php

**Comment by SyalChain** [comment]
@profeIAP Es muy difícil encontrar uno que sea óptimo, este es el que más me convence. Acabo de hacer el push.

**Comment by profeIAP** [comment]
Está bastante bien... si encontramos otro mejor ya lo cambiamos.
Gracias Emilio
