### ISSUE TITLE
Documentar cómo añadir columnas a una tabla existente

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#105]
Crear documento compartido en Google Drive en el que se explique cómo pueden añadirse columnas a una tabla de nuestra base de datos

**Comment by jasvazquez** [comment]
Necesito que compartas conmigo el documento donde explicas el proceso, gracias.

**Comment by profeIAP** [comment]
Pablo, tienes demasiadas tareas de ofimática... la próxima que sea de programación ¿ok?
Esta tarea estaba tentado a "quitártela" pero, si realmente la tienes terminada ¡compártemela!
En caso contrario suéltala (para que otro compañero pueda abordarla) y céntrate en alguna de programación.

**Comment by profeIAP** [comment]
@fran98moreno veo que has aprovechado que @AndreaRomero9 soltó la tarea (para no asumir más penalizaciones) pero no has aprovechado [el trabajo que ella había realizado](https://docs.google.com/document/d/1P3AcXo_yP3ExqpeS82SvOObAQ06y5LoAqdjRi7U8Avc/edit?usp=sharing).

Al comenzar la [documentación](https://docs.google.com/document/d/1oKh6ZztxII3-bN3b1_lzx9q5hKKVZm7qKeHugGKNWHw/edit?usp=sharing) "desde cero" deberás **hacer uso de la plantilla** habilitada **para la documentación**.

**Comment by fran98moreno** [comment]
es que primero lo he hecho con esta estética para luego poder hacer la tarea #222 que se trata en cambiar la estética

**Comment by profeIAP** [comment]
No hagas trabajo en balde: hazlo del "tirón" y cierra las dos tareas

**Comment by fran98moreno** [comment]
[Oculto el enlace](https://docs.google.com/document/d/1oqgMgSRZ5ihozSq40GA8RhWdnaiSUVTW57Xuwh2juGU/edit?copiedFromTrash#heading=h.odk14lnc5eyk) y cierro esta tarea y la número #222

**Comment by profeIAP** [comment]
Sea que cierres las tarea #222 pero esta tarea aun requiere algo de trabajo por tu parte :)

Igualmente, para dar por finalizada, **exigiré** que "ocultes" el enlace del comentario anterior dentro del texto que has escrito (gracias)

**Comment by fran98moreno** [comment]
Done

**Comment by profeIAP** [comment]
No sé por qué cierras una tarea en la que no has aplicado partes de los cambios indicados

**Comment by profeIAP** [comment]
Faltan por acometer algunas de las anotaciones del documento.

**Comment by MartaCorzo** [comment]
No recuerdo cual era el documento donde tenia que copiar y copiar el "type" de sqlite me lo podrías recordar? @jasvazquez

**Comment by profeIAP** [comment]
Ok
