### ISSUE TITLE
Investigar cómo numerar automáticamente los apdos. de un documento

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#106]
La idea es contar con algún modo de asignar número automáticamente a los distintos apartados de un documento de texto en Google Drive sin tener que hacerlo manualmente.

![numerar-apdos](https://cloud.githubusercontent.com/assets/16881846/14211575/1bb3f2b6-f82f-11e5-9545-a7f5ba6f1b94.jpg)

Desconozco (aunque lo dudo) si existe la opción en Drive pero es posible (que no seguro) que exista alguna extensión que permita hacerlo.

El **objetivo** es:
1. encontrar si existe alguna forma de hacerlo
2. documentarlo en un documento compartido en Drive

**Comment by fran98moreno** [comment]
documento compartido

**Comment by profeIAP** [comment]
Documento recibido y comentado...

**Comment by fran98moreno** [comment]
creo que ya XD

**Comment by profeIAP** [comment]
Funcionar, funciona pero... no puede aplicarse a los apartados ("Títulos") del documento

**Comment by fran98moreno** [comment]
tarea imposible, que solución me da para mi tiempo invertido en una tarea fantasma?

**Comment by profeIAP** [comment]
¿Cómo verías que el mecánico de un taller (por poner una profesión cualquiera) te cobrase X tras devolverte el coche tal cual se lo dejaste?

**Comment by fran98moreno** [comment]
es como si vas a que te llenen de gas el mechero, pero cuando te lo hacen te das cuenta de que a tu mechero le falta una pieza; no es culpa del dependiente, sino del cliente, aun así el dependiente hizo lo que se le pidió

**Comment by profeIAP** [comment]
Muchos fueron los que se embarcaron rumbo a las américas embaucados por la leyenda del Dorado y/o la fuente de la eterna juventud a pesar de las advertencias de familiares y amigos respecto a los peligros y la poca verosimilitud (habladurías) de dichas historias.

No obstante, estos "osados" (¿locos?) aventureros optaron por lanzarse a la aventura cegados por el imaginario resplandor de la recompensa y haciendo oídos sordos a los consejos y advertencias al grito de: ¡sin riesgo no hay beneficio! arriesgando en dicha empresa tanto su vida como la propia hacienda.

**Comment by profeIAP** [comment]
Lo olvidaba Fran: movido por mi "curiosidad natural" estuve bicheando ayer un rato y he descubierto que sí existe la posibilidad de enumerar los apartados de un documento en Drive juauauauauau (poner voz maléfica XD)

**Comment by Rafaelcraftero** [comment]
me dijiste que esto era como locura porque no lo había conseguido nadie ¿cuenta como locura o como reto?

**Comment by profeIAP** [comment]
Tengo la solución anotada en uno de mis correos "internos" ¿Quieres que te lo cuente como **dos** tareas **reto**? ¡Acepto el reto! 

Pero:
1. Debes ser muy pero que muy fino con la solución (no acepto "trampas" ni "cutreríos")
2. Deberás documentar levemente la solución (primero me pasas un ejemplo para no invertir tiempo en documentar cosas que no sirven)

¿Le parece D. Rafael? ;)

**Comment by Rafaelcraftero** [comment]
challenge accepted

**Comment by Rafaelcraftero** [comment]
Dime si está bien o no te he pasado el correo con la invitación hace 1 o 2 día

**Comment by profeIAP** [comment]
Normalmente requiero que incluyáis en los comentarios un [enlace al documento compartido](https://docs.google.com/document/d/1dHbmTMZ7NaJ2dQ0FJ2JwlK2FuyZzzvAYc7VroMg82kg/edit?usp=sharing)

La solución que indicas tiene muy buena pinta pero, para darlo por bueno:
1. agradecería que aplicases la solución encontrada a tu propio documento (organiza el contenido en apdos. y numéralos)
2. utiliza la plantilla que tenemos como modelo (tu documento no cumple con el formato estándar)

Enhorabuena, tiene pinta que vas a lograr el "doble reto" ;)

**Comment by Rafaelcraftero** [comment]
ya he hecho lo que mandaste mira a ver si está bien https://docs.google.com/document/d/1QTrzsPiyyM21RMjMLe8ymJjqLxK3PGUYVazxS0eUHXY/edit#

**Comment by profeIAP** [comment]
D. Rafael... incluya el enlace del comentario anterior oculto en el texto (que queda "feo" ver los enlaces por ahí "sueltos" y es un requisito para poder dar por cerrada la tarea)

Le incluyo algunos comentarios en el espectacular documento que está elaborando ;)

**Comment by Rafaelcraftero** [comment]
Te he mandado el nuevo [documento de google drive ](https://docs.google.com/document/d/1E9OWnYHkNqVhMxpI2gMjOaWPtFUog2m7TrqSe4QBkSk/edit)con todo terminado

**Comment by profeIAP** [comment]
Bastante mejor Rafael, te dejo unos comentarios y [recuerda ocultar el enlace que pusiste en el siguiente comentario](https://github.com/profeIAP/panelDeControl/issues/106#issuecomment-223950838)

**Comment by Rafaelcraftero** [comment]
Creo que está corregido todo lo que me pusiste para corrigiera

**Comment by profeIAP** [comment]
Está espectacular D. Rafael... como "favor", agradecería incluyese el par de sugerencias que le hago para rematar uno de los documentos más completos que tenemos actualmente en nuestra "biblioteca" documental ;)

**Comment by Rafaelcraftero** [comment]
Arreglado

**Comment by profeIAP** [comment]
Estupendo D. Rafael, un gran trabajo ¡Enhorabuena!
