### ISSUE TITLE
Contar número de tablas existentes en la BD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#109]
Crear método en el controlador del proyecto que permita conocer cuántas tablas existen actualmente en la base de datos (BD).

Nos será de utilidad cuando implementemos un mecanismo que permita evitar problemas cuando algún compañero haga un commit en el repositorio y desaparezca alguna de las tablas existentes.

La solución pasa por [utilizar los metadatos de la BD](http://stackoverflow.com/a/6617764)

**Comment by profeIAP** [comment]
Será necesario utilizar la función _count(..)_ de SQL e incluir clausulas para que no incluya las secuencias

**Comment by Cesarj9** [comment]
ok... ;(

**Comment by Cesarj9** [comment]
SELECT name, sql FROM sqlite_master
WHERE type='table' and name not like 'sqlite%'
ORDER BY name

**Comment by profeIAP** [comment]
No olvides que **debe ser incluido en el controlador**.
Si lo quieres hacer limpio, [crea una vista tal y como explicó Curro](https://docs.google.com/a/iesalandalus.com/document/d/1vwjKLieWg3o0dao3fAU072zPCYhkYTxzol-xzbjXkTw/edit?usp=sharing)

**Comment by profeIAP** [comment]
Perfecto salvo que no has incluido el método en el controlador (acá **index.php**)

**Comment by profeIAP** [comment]
Redireccionas a una vista que no existe ([tablas.php](https://github.com/profeIAP/panelDeControl/blob/192421cfcdc13d855f0d7b7a9e34667ddbd8ab86/index.php#L316)) lo cual provoca un error.

Te recomendaría optar por la [solución propuesta](https://github.com/profeIAP/panelDeControl/blob/18c400bfae922ea318de611d49c1e8c134a9a16a/index.php#L413-L421) por @jpc99 y/o definir la vista que intentas renderizar.

**Comment by profeIAP** [comment]
Espectacular César, muchísimas gracias
