### ISSUE TITLE
Añadir formulario partes al proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#11]
Desarrollado en el proyecto Pártete

**Comment by profeIAP** [comment]
Para poder cerrar la tarea definitivamente, necesito poder acceder a dicho formulario desde la web (lo cual requiere modificar layout.php y el controlador.

No hace falta que se guarde ni que recupere datos, sólo que aparezca cuando se le pida ;)

Buen trabajo Javi

**Comment by javierfl98** [comment]
terminado

**Comment by profeIAP** [comment]
Damos por cerrada la tarea.
