### ISSUE TITLE
Los commits indican usuarios de forma incorrecta

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#111]
Al usar dos personas el mismo ordenador, al hacer el commit, aunque utilizes tu usuario y contraseña, puede aparecer el nombre del otro usuario de tu ordenador.

Buscar cómo evitar que ocurra esto.

A modo de ejemplo, tenemos [el commit](https://github.com/profeIAP/proyecto2015-16/commit/efbbff1b19ac404a849a5fe1f67a1ddc1917e122) de @fdm1999 que aparece como si lo hubiese hecho @mariamiura16

**Comment by SyalChain** [comment]
Ya está comprobado: el error radicaba en el comando git config --global "usuario"/"email", con lo que se registraba un usuario único para todas las subidas del proyecto.

Para solventarlo, basta con cambiar el --global por --local previamente a cada subida, asegurando que el usuario propio suba su aporte y no el anterior que hubiera trabajado con el mismo ordenador.

**Comment by profeIAP** [comment]
Queda [anotado en la wiki](https://github.com/profeIAP/proyecto2015-16/wiki) del proyecto para futuros usos.

Gracias Jesús Emilio
