### ISSUE TITLE
Mejorar imagen pantalla "Anotación jefe de estudios"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#114]
Utilizando la [técnica descrita](https://drive.google.com/open?id=1Xau2T5XaZFE-t_tYxTCcDu7N6eDoiZWnX1WUEbKzE98) por @rociomacho, [mejorar la fotografía realizada](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.59np8xmpmxmp) para documentar la pantalla utilizada por el jefe de estudios para realizar anotaciones en el documento de requisitos funcionales

**Comment by marialuisapf** [comment]
¿dónde subo la foto?

**Comment by profeIAP** [comment]
En el mismo documento de requisitos funcionales: la idea es sustituir la que tenemos por la versión mejorada

**Comment by marialuisapf** [comment]
Necesito permiso de edición, que solo tengo de vista

**Comment by profeIAP** [comment]
Observo que ya tenías permisos de edición ¿estás usando el correo electrónico de siempre?

**Comment by marialuisapf** [comment]
Sí, lo que pasa es que le pedí al dueño del documento que me diera permisos, por eso te sale como que tengo

**Comment by profeIAP** [comment]
No termina de verse bien, ¿has consultado a @rociomacho  qué puede estar fallando?

**Comment by profeIAP** [comment]
Ha quedado perfecta, gracias @marialuisapf
