### ISSUE TITLE
Cambiar de ubicación directorio calendario_dw

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#115]
En el directorio raíz del proyecto no debe haber más carpetas de las que existían originalmente.

El objetivo es mover el contenido de dicha carpeta a los directorios:
1. js
2. img
3. css

y que el calendario añadido por @fran98moreno siga funcionando.

Se entiende que cada fichero debe estar donde le corresponde (las imágenes en el directorio img, los ficheros javascript en js, ...)

**Comment by SyalChain** [comment]
Igual esta no es la mejor tarea en la que indicarlo, pero habría que corregir el título del campo con el calendario (pone 'Teléfono' xd)

**Comment by profeIAP** [comment]
Tienes toda la razón del mundo pero @fran98moreno  lo puso ahí porque no teníamos mejor sitio.
Tan pronto contemos con el mantenimiento de partes, lo cambiamos de sitio ;)

**Comment by profeIAP** [comment]
Ya era hora de que se cerrase esta tarea (llevaba días subido el cambio)
Gracias Fran
