### ISSUE TITLE
Documentar la cláusula "GROUP BY" en SQLite

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#116]
Compartir documento en Google Drive que explique cómo se realiza la agrupación de los datos de una tabla en función de los valores que se repiten de determinada columna.

**Comment by Cesarj9** [comment]
dificultad??

**Comment by profeIAP** [comment]
Como se indica, su nivel de dificultad es "[reto](https://github.com/profeIAP/proyecto2015-16/issues?utf8=%E2%9C%93&q=label%3Areto)".

El motivo (causa o razón) es que implica hacer un estudio del uso de dicha cláusula desde el gestor de bases de datos y luego ser capaz de redactar un documento lo suficientemente claro y útil como para que otros compañeros puedan hacer uso de él.

**Comment by Cesarj9** [comment]
Si cuando termine la que tengo sigue libre, me la apunto

**Comment by profeIAP** [comment]
Abro por no tener compartido el documento.

**Comment by profeIAP** [comment]
Sirva como [ejemplo base](http://www.tutorialspoint.com/sqlite/sqlite_group_by.htm) la siguiente web.

No es muy completo pero te servirá para empezar.

No pierdas de vista las funciones: count() y max()/min()

**Comment by profeIAP** [comment]
Si no se entiende el inglés... usa el "[translate](https://translate.google.es/)"

**Comment by majimgall** [comment]
Ahí  lo tienes maestro 
[GROUP BY](https://docs.google.com/document/d/1wYNH66nTpIuKOapF2-fboBFd9fuhrpZwjONjBVNclwY/edit)

**Comment by profeIAP** [comment]
Corrije la falta de ortografía y oculta el enlace dentro del texto del comentario.

Te dejo comentarios sobre el propio documento

**Comment by profeIAP** [comment]
Te ha quedado espectacular María pero (desgraciadamente) no puedo dar por cerrada la tarea.

Motivo, causa o razón: ¡HAS IGNORADO MI ÚLTIMO COMENTARIO! (ortografía + enlace)

**Comment by majimgall** [comment]
Ya están corregidas todas la faltas (o eso espero) 
[GROUP BY](https://docs.google.com/document/d/1wYNH66nTpIuKOapF2-fboBFd9fuhrpZwjONjBVNclwY/edit#)

**Comment by profeIAP** [comment]
Me refería al [comentario](https://github.com/profeIAP/panelDeControl/issues/116#issuecomment-221543962)

Sigue siendo un requisito corregirlo

**Comment by profeIAP** [comment]
Perfecto, te ha quedado perfecto ¡Buen trabajo @majimgall!
