### ISSUE TITLE
Listar todos los partes almacenados

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#12]
Leer de la BD y mostrar en pantalla

**Comment by profeIAP** [comment]
Sería equivalente al [código que tenemos actualmente en el repositorio](https://github.com/profeIAP/proyecto2015-16/blob/c62ebfbe2e7f8f362ffa527797e39381f29746db/index.php#L73-L83) pero utilizando la tabla _partes_ que se ha creado en la tarea #2

**Comment by profeIAP** [comment]
Has tenido suerte de no "romper" nada (hay cambios excesivamente raros posiblemente a una falta de actualización de tu proyecto durante demasiado tiempo)

Observa que actualmente existen dos group('/partes'):
1. El que teníamos hasta la fecha
2. El que has introducido tú

Fusiona ambos en uno solo puesto que, a pesar de estar bien implementado por tu parte, no funciona [el listado de partes](http://localhost:9000/partes) como debiese: al haber dos, el ordenador no sabe cuál es el que quieres realmente utilizar.

**Comment by angelagr** [comment]
ya está cambiado

**Comment by profeIAP** [comment]
¡Bien hecho!
Perooo...recuerda subir los cambios al repositorio para que pueda evaluar el trabajo.

**Comment by angelagr** [comment]
ya he subido los cambios

**Comment by profeIAP** [comment]
Desgraciadamente Ángela:
1. Ni hay un commit de tu usuario en el día de hoy
2. Ni hay ninguna referencia a la tarea 12 en los commits
3. Ni se listan los partes

Lo que [te comenté hace una semana](https://github.com/profeIAP/panelDeControl/issues/12#issuecomment-220575842) sigue ocurriendo

Revisa tu trabajo, está prácticamente acabada la tarea, ¡ánimo!

**Comment by profeIAP** [comment]
Sigue sin estar el listado de partes Ángela ¿has subido el commit que hicimos esta mañana?
Siguen existiendo dos _group('/partes')_

**Comment by profeIAP** [comment]
Sigue estando [en vigor lo indicado hace 4 días](https://github.com/profeIAP/panelDeControl/issues/12#issuecomment-222152932) ¿?

**Comment by profeIAP** [comment]
l

**Comment by profeIAP** [comment]
Te ha quedado perfecto, gran trabajo @angelagr
