### ISSUE TITLE
Añadir opción "Partes" en el menú superior

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#120]
Incluir nueva opción "Partes" en el menú de opciones de la web.
Deberá aparecer entre las opciones "Alumnos" y "Acerca de" y al seleccionarla únicamente deberá mostrar los mensajes "Partes registrados" y "Listado de partes" tal y como ocurre actualmente en la opción "Alumnos"

![captura de pantalla de 2016-04-07 09 32 51](https://cloud.githubusercontent.com/assets/16881846/14343828/ce53f16e-fca3-11e5-909b-8f0bee252b8f.png)

**Comment by semacg98** [comment]
Tarea realizada

**Comment by profeIAP** [comment]
Perfecto... ¡buen trabajo!
Gracias "sema"
