### ISSUE TITLE
Añadir menú lateral a la aplicación

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#121]
Incluir en layout.php (para que aparezca en todas las pantallas de la aplicación) [el siguiente menú](http://www.jqueryscript.net/menu/Super-Smooth-Accordion-Dropdown-Menu-with-jQuery-CSS3.html) 

![](http://www.jqueryscript.net/images/Super-Smooth-Accordion-Dropdown-Menu-with-jQuery-CSS3.jpg)

con las siguientes opciones
- Alumnos
  - Crear
  - Buscar
  - Listar
  - Importar
- Partes
  - Crear
  - Buscar
  - Listar
- Usuarios
  - Crear
  - Buscar
  - Listar
  - Importar
- Salir

**Comment by profeIAP** [comment]
@carlosaj98 como se está complicando la tarea, céntrate en conseguir que funcione el menú.

Mete un "comando" en el controlador (**index.php**) al que llamaremos **'/opciones_'_ que simplemente muestre una vista nueva (**view/opciones.php**) cuyo único contenido sea el menú que se pide en esta tarea.

No creo que lo necesites pero la lógica de _index.php_ es similar a la que encontrarás en el siguiente [fragmento de nuestro proyecto](https://github.com/profeIAP/proyecto2015-16/blob/f8d2d75fb672ba07828f8e8b6c892895d7c65307/index.php#L68-L71).

Procedo a crear una nueva tarea para que otro compañero se encargue de maquetar la web y conseguir que el menú aparezca en la parte derecha.

**Comment by carlosaj98** [comment]
Ya he subio el menu lateral

**Comment by profeIAP** [comment]
Y ha quedado espectacular... ¡Enhorabuena Carlos!

Hay un par de detalles que se han "estropeado" al subir tu actualización a layout.php:
1. Ha desaparecido el título "CONTROL DE PARTES" del encabezado de la página
2. Las opciones "Inicio" y "Acerca de" se han puesto "coloradas"

Sospecho que se debe a algunos de los cambios en la hoja de estilo que has aplicado.
Se requiere que queden como estaban para dar por cerrada la tarea.

Ánimo, es poca cosa, y te ha quedado realmente genial el menú, ¡Gracias!

**Comment by carlosaj98** [comment]
Ya esta solucionado

**Comment by profeIAP** [comment]
Las opciones "Inicio" y "Acerca de" han retomado su color habitual (azul) pero sigue sin aparecer el título "CONTROL DE PARTES" del encabezado de la página

**Comment by carlosaj98** [comment]
Ya se ve CONTROL DE PARTES

**Comment by profeIAP** [comment]
Desgraciadamente no, ¿has subido los cambios?

**Comment by profeIAP** [comment]
Yo sigo sin ver el encabezado (probado en Chrome y Firefox)

**Comment by carlosaj98** [comment]
Cuando hago el push me sale: Everything up-to-date y el encabezado ami me sale

**Comment by profeIAP** [comment]
Pues haz un git pull previamente

**Comment by carlosaj98** [comment]
Sigue saliendome eso, ademas por ejemplo al Francisco Diez le sale el encabezado

**Comment by profeIAP** [comment]
Damos por cerrada la tarea pues, acabo de descargarme la última versión del proyecto y ¡por fin sale!

![captura de pantalla de 2016-05-23 16 21 23](https://cloud.githubusercontent.com/assets/16881846/15473870/75b141dc-2102-11e6-91a9-b96dc9688bd6.png)

¡Buen trabajo Carlos!
