### ISSUE TITLE
Documentar funcionamiento pantalla "Alta de parte"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#123]
Documentar la interacción del usuario con la pantalla que permite [dar de alta un parte de comportamiento](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.cr0ye6bkr6k) usando como modelo la estructura definida en la [Edición de alumnos](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.urcfy1a5u9t).

**Comment by danigomez99** [comment]
Tarea finalizada.

**Comment by profeIAP** [comment]
Comento sobre el propio documento

**Comment by profeIAP** [comment]
@danigomez99 ... ¿esta tarea por qué la tenemos aquí "anquilosada" cuando realmente no es nada compleja?

**Comment by danigomez99** [comment]
Profesor, en esta tarea usted me ha puesto en el título de casos alternativos que no tiene forma de título y tiene la forma de Título 4.

**Comment by profeIAP** [comment]
Algo debe estar pasando, ahora lo veo como "Título 1" (que tampoco es correcto)
Te he dejado algunas correcciones y comentarios Daniel

**Comment by danigomez99** [comment]
Ya está otra vez corregida... aver si esta es ya la definitiva...

**Comment by profeIAP** [comment]
"Aver" César... te incluyo sugerencias para tratar de cerrar esta tarea Dani (observo que no te está cundiendo el tiempo de "trabajo" en clase demasiado ¿no te parece?)
