### ISSUE TITLE
Incluir uso de "Open Terminal Here" en la wiki del proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#124]
Incluir en la wiki del proyecto una [referencia al documento](https://drive.google.com/open?id=1cn0z1cLdcvBf4cSn4g9OHRxYvSbKLvFYVvA0FI9wUDQ) creado por @fran98moreno explicando cómo se instala.

En todos los apartados donde se indique que hay que cambiar de directorio (comando _cd_ de Linux) debería usarse "Open Terminal Here"

**Comment by javierfl98** [comment]
ya esta incluida como instalar la extension en el wiki del proyecto

**Comment by profeIAP** [comment]
La idea no era realmente incluir un apartado al final del documento Javi explicando cómo se instala (eso ya lo hace el documento de Fran) sino indicar que existe el documento de Fran y por qué es importante echarle un vistazo.

El apdo. estaría mejor al principio (¿Creamos un apartado **Recomendaciones** y lo metemos como subapartado?), si me apuras, podría ir [con la configuración del usuario ](https://github.com/profeIAP/proyecto2015-16/wiki#configuraci%C3%B3n)

**Comment by javierfl98** [comment]
he creado un apartado Recomendaciones y lo he metido en un subapartado creando una referencia al proyecto

**Comment by profeIAP** [comment]
Ok, molesta un poco verlo nada mas empezar pero podría servir.
Gracias Javier
