### ISSUE TITLE
Detectar si existe determinado fichero en disco

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#126]
Implementar método que permita conocer si existe determinado fichero (será model/dictados.db)

**Comment by profeIAP** [comment]
Miguel Ángel, llevas mucho tiempo con esta tarea y nos hace falta para complementar las tareas #109 y #110.

Existe [información a raudales](https://www.google.es/search?q=php+existe+fichero&oq=php+exist&aqs=chrome.2.69i57j0l5.4019j0j7&client=ubuntu-browser&sourceid=chrome&es_sm=122&ie=UTF-8) en Internet y la dificultad prácticamente es "nula"

**Comment by Mahc99** [comment]
Terminada, la ruta es [/Bd](http://localhost:9000/Bd)

**Comment by profeIAP** [comment]
Espectacular Miguel Ángel, espectacular... un trabajo rápido, limpio y eficiente.
Sigue así, estás creciendo más si cabe ;)
