### ISSUE TITLE
Añadir imagen a los posts de UpMyMusic

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#127]
Necesitamos que las [entradas publicadas de UpMyMusic](http://semillerodeempresas.blogspot.com.es/search/label/UpMyMusic) incluyan como mínimo una imagen (relacionada con el tema de cada post y/o motivadora)

**Comment by ghost** [comment]
Ya he puesto imágenes en cada artículo que se publicó cuando aún estaba en funcionamiento UpMyMusic. También he cambiado algunas cosas en el contenido escrito de las noticias como faltas de ortografía que he ido encontrando o expresiones incorrectas. Espero que haya quedado bien y que te guste. Salu2.

**Comment by profeIAP** [comment]
Están muchísimo mejor: no hay "color"

Sólo un par de cosas:
1. Redimensiona las imágenes para que su tamaño sea inferior al ancho de la noticia (y no se "rebosen"
2. Los enlaces que aparecen deben estar "ocultos" en algunas palabras "significativas" del párrafo (queda feo ver los enlaces por ahí sueltos)

**Comment by ghost** [comment]
Ya he puesto los los enlaces sueltos en palabras que te llevan a dicha dirección y he cambiado el tamaño de las imágenes para que no se salgan del margen

**Comment by profeIAP** [comment]
Fantástico, di que sí... buen trabajo Fco.
