### ISSUE TITLE
Añadir imagen a varios posts del blog

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#129]
Necesitamos que las siguientes entradas publicadas en el blog: 
- [Brother's Barbu](http://semillerodeempresas.blogspot.com.es/2016/03/aqui-podeis-encontrar-nuestro-enlace-de.html)
- [Panel de control](http://semillerodeempresas.blogspot.com.es/2016/01/objetivo-de-la-empresa.html)

incluyan como mínimo una imagen (relacionada con el tema de cada post y/o motivadora)

**Comment by profeIAP** [comment]
Perfecto salvo que:
- Faltan imágenes para los enlaces a Twitter y Facebook de Brother's Barbu
- La imagen de Panel de control queda rara alineada a la derecha (recomendaría incluirla en su propio párrafo y centrada)

**Comment by Cesarj9** [comment]
no hay enlace de facebook

**Comment by profeIAP** [comment]
Lo había y siempre puedes consultarlo en el [documento de requisitos funcionales](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.g6pps43qyprs)

Igualmente observo que al hacer click sobre las imágenes, en lugar de llevarme a las correspondientes páginas webs, opta por mostrar la "bonitas" imágenes que has usado :P

**Comment by Cesarj9** [comment]
¿¿contento??

**Comment by profeIAP** [comment]
Muchísimo mejor pero no me tientes... porque estéticamente (básicamente los tamaños de las imágenes no coinciden) deja bastante que desear
