### ISSUE TITLE
Listar todos los alumnos almacenados

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#13]
Leer de la BD y mostrar en pantalla

**Comment by alemorales1999** [comment]
que tengo que hacer en esta tarea ?

**Comment by profeIAP** [comment]
De especial utilidad te resultará la tarea #12 o #27 
Básicamente leer la BD y mostrar en pantalla todas las entradas existentes.
Ya hay código que lo hace, sólo tienes que cambiarlo para que recupere el contenido de la tabla _alumnos_

**Comment by alemorales1999** [comment]
po me has dejado igual

**Comment by profeIAP** [comment]
Tenemos un "problema"... bueno, realmente lo tienes tú XD
¿Has pedido cita para verlo conmigo?

**Comment by profeIAP** [comment]
Como las tareas que te indico arriba están TODAVÍA sin terminar, te recomiendo mirar [este fragmento de código](https://github.com/profeIAP/panelDeControl/blob/2052cb6e935fb7ade7df905f16785bfa687e22c9/index.php#L118-L126)

**Comment by profeIAP** [comment]
Aquí tienes [cómo se recorren en la vista los datos](https://github.com/profeIAP/panelDeControl/blob/master/view/notificaciones.php) que te envía index.php

Y aquí tienes [el fichero de la vista que debes modificar](https://github.com/profeIAP/panelDeControl/blob/c4cd614b30bdfb002a427b5fa72e47555da9eeeb/view/alumnos.php)

**Comment by alemorales1999** [comment]
yo voy a cojer otra mejor

**Comment by profeIAP** [comment]
@alemorales1999  ¡Insensato! ¿¡¿Por qué lo has abandonado?!?

**Comment by profeIAP** [comment]
Perfect... damos por cerrada esta tarea
