### ISSUE TITLE
Habilitar las acciones "editar" y "borrar" en el listado de alumnos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#130]
No se están incluyendo los IDs que permiten identificar en el listado los alumnos a editar y/o borrar

![captura de pantalla de 2016-04-13 09 34 05](https://cloud.githubusercontent.com/assets/16881846/14486083/5a4bfb7e-015b-11e6-834c-96f8036e9aa0.jpg)

**Comment by profeIAP** [comment]
Por _casualidad_ he encontrado por qué no funciona.

Observa que la tabla **alumno** [no tiene el campo ID como autonumérico](https://github.com/profeIAP/proyecto2015-16/commit/51ac19c2f779a60422f3748f4eb17d0e8ce237da) por lo que el problema se solucionará cuando cambies dicho campo (y sólo ese campo, los demás deben seguir existiendo como están ahora mismo)

Para dar por finalizada la tarea deberás:
- Modificar model/dictados.db
- Actualizar model/scripts/table_alumno.sql

**Comment by profeIAP** [comment]
Espectacular María, qué me gusta verte trabajar así.
Vamos, vamos...

**Comment by mariamiura16** [comment]
thanks :)
