### ISSUE TITLE
Cambiar ruta para acceder a los alumnos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#133]
Actualmente el enlace para acceder a los alumnos 

![captura de pantalla de 2016-04-14 13 30 07](https://cloud.githubusercontent.com/assets/16881846/14526647/0fdd6ef2-0245-11e6-97a3-e966dd7efc88.png)

utiliza (como ruta en la url) el valor "/comentarios".

Debe cambiarse por "/alumnos" tanto en **layout.php** como en **index.php**

**Comment by ghost** [comment]
Ya he terminado. Mira a ver si está bien

**Comment by profeIAP** [comment]
Lo pedido está bien salvo que [has aplicado un cambio](https://github.com/profeIAP/proyecto2015-16/commit/de4b47ff1f761cb19cdf5abe9735864f4c0718a2#diff-828e0013b8f3bc1bb22b4f57172b019dL133) que provoca que deje de funcionar [view/alumno.php](https://github.com/profeIAP/proyecto2015-16/blob/de4b47ff1f761cb19cdf5abe9735864f4c0718a2/view/alumno.php)

**Comment by ghost** [comment]
Ya creo que está bien. Sin querer he hecho dos commits porque me he confundido y creia que no se había subido.

**Comment by ghost** [comment]
Cierro la tarea ya. Creo que ya está bien

**Comment by profeIAP** [comment]
Francisco, ¿¡¿desde cuándo eres @mariamiura16?!?

Se me ocurren dos opciones:
1. Tienes mal configurado tu repositorio (aquí se explica [cómo corregirlo](https://github.com/profeIAP/proyecto2015-16/wiki#configuraci%C3%B3n))
2. Alguno de los dos os habéis confundido y estáis usando la carpeta de vuestro compañero (me consta que compartís portátil)

**Comment by profeIAP** [comment]
Fantástico Fco., pero se te [ha escapado esta redirección](https://github.com/profeIAP/proyecto2015-16/blob/d9f12a147e819acbac020947b036672bd9f7bea5/index.php#L161)

Cada vez que se guarda un alumno nuevo, te vuelve a mostrar el formulario de crear alumnos (en lugar del listado de alumnos)

Pon una redirección a **/alumnos** igual que has hecho antes.

**Comment by profeIAP** [comment]
Doy por cerrada la incidencia; no obstante, recuerda solucionar lo que te acabo de comentar ¿te parece?

**Comment by profeIAP** [comment]
@fdm1999 recuerda configurar correctamente tu usuario para que deje de aparecer @mariamiura16 como responsable de tus commits ;)
