### ISSUE TITLE
Aprovechar el espacio en pantalla

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#136]
Actualmente se desperdicia gran cantidad de espacio en pantalla

![captura de pantalla de 2016-04-15 18 22 14](https://cloud.githubusercontent.com/assets/16881846/14568009/36ad4b36-0337-11e6-8f7c-e2323791af73.png)

Cambiar la plantilla **layout.php** para que el contenido se expanda hasta cubrir todo el espacio disponible en la ventana.

De especial utilidad podría servirte estudiar cómo funciona [el "grid" en Bootstrap](http://www.w3schools.com/bootstrap/bootstrap_grid_examples.asp)

**Comment by profeIAP** [comment]
¿Cómo estás enfocando la tarea Emilio?

**Comment by SyalChain** [comment]
La idea que tengo en mente es buscar por lo pronto cómo extender todo el
texto hacia los laterales.

Creo que lo suyo sería poder redimensionar la anchura de los campos, como
el propio listado de partes para que ocupe más espacio.

Pero pensándolo bien ahora, sería lo suyo aprovechar y añadir elementos de
ayuda para la propia página, algo tipo publicidad (igual sacamos ingresos
xD), o mejor, para aquella tarea cuyo número no recuerdo con la aplicación
RSSCast. Algo que muestre el tiempo, o las estadísticas del porcentaje de
incidencias graves semanales (porque delinquir es profesión (?)).

Si me pudieras aconsejar, bien cuando puedas o bien en clase el lunes.

**Comment by profeIAP** [comment]
Ya que te gustan los "colorines", igual te resulta de utilidad [usar como base alguna plantilla ya existente](https://shapebootstrap.net/free-templates)

Agradecería:
1. No fuese muy "cargante"
2. Permita incluir en la derecha nuestro menú de opciones (tarea #125)

**Comment by profeIAP** [comment]
Otra posibilidad sería enfocar la web como lo que realmente es: [un panel de administración](https://github.com/keaplogik/Bootstrap-Clean-Dashboard-Theme)

**Comment by profeIAP** [comment]
Este es realmente [espectacular](https://github.com/puikinsh/gentelella) (e incluye menú lateral)... aquí [os dejo una demo](https://colorlib.com/polygon/gentelella/index.html)

**Comment by SyalChain** [comment]
Tarea finiquitada, por fin.

**Comment by profeIAP** [comment]
Todo lo bueno se hace esperar "pequeño" saltamontes.

Ha quedado espectacular Emilio aunque es posible que muchos no lleguen a apreciar el cambio en toda su "magnitud" (y hasta que ni se den cuenta)

Muchas gracias por este gran paso para la "Humanidad" ;)
