### ISSUE TITLE
Completar el formulario de partes

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#137]
Adaptar el formulario de partes actualmente existente bajo [la siguiente ruta](http://localhost:9000/partes/crear) al contenido y formato especificado [en el documento de requisitos funcionales](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.irh5szr1ykhh).

Se etiqueta como **reto** por tratarse de un formulario con excesivos campos, no por su complejidad.

**Comment by profeIAP** [comment]
@AntonioJ98 no sé cómo llevarás esta tarea pero, a la hora de asignar el atributo _name_ a los campos del formulario, utiliza: 
- los mismos que se usan tanto en la BD (grupo, fecha, l_dificultad, ...)
- los que espera [la ruta /partes/guardar ](https://github.com/profeIAP/panelDeControl/blob/b0bdf9471853ab43f884a4409e73cbcba8867617/index.php#L256-L290)

No te preocupes: los nombres coinciden en los dos casos anteriormente mencionados

**Comment by profeIAP** [comment]
Observo algunos detalles:
1. Ha desaparecido [la lista desplegable del campo Hora](https://github.com/profeIAP/panelDeControl/commit/d2a321e52ca2db6d25ede3c9c904e468dcdcabc9#diff-0f2508d8f1191fac02fd6df909c8fbd6L31)
2. Bloques [jumbotron nuevos](https://github.com/profeIAP/panelDeControl/commit/d2a321e52ca2db6d25ede3c9c904e468dcdcabc9#diff-0f2508d8f1191fac02fd6df909c8fbd6R52) (sólo debería existir uno al principio en la descripción del formulario)
3. Metes [ruido fruto de un "merge"](https://github.com/profeIAP/panelDeControl/commit/d2a321e52ca2db6d25ede3c9c904e468dcdcabc9#diff-0f2508d8f1191fac02fd6df909c8fbd6R181) mal ejecutado
4. Aparecen [nuevos formularios](https://github.com/profeIAP/panelDeControl/commit/d2a321e52ca2db6d25ede3c9c904e468dcdcabc9#diff-0f2508d8f1191fac02fd6df909c8fbd6R56) cuando sólo debe existir uno para el parte completo
5. ... (alguna que otra cosa más, las iré "desgranando" conforme vayas corrigiendo cosas ¿te parece?)

A pesar de todo lo anterior, ya va cogiendo "forma", ¡Ánimo!

**Comment by profeIAP** [comment]
Una posible [referencia para los checkboxes](http://www.w3schools.com/bootstrap/bootstrap_forms_inputs.asp)

**Comment by AntonioJ98** [comment]
@profeIAP

**Comment by profeIAP** [comment]
Está realmente bien Antonio pero, entre otras cosas, te has cargado:
1. [La botonera](https://github.com/profeIAP/panelDeControl/commit/c17889a78413db85d329416d392537ad9f20a1d7#diff-0f2508d8f1191fac02fd6df909c8fbd6L103) que introdujimos en la tarea #169 
2. [El calendario](https://github.com/profeIAP/panelDeControl/commit/c17889a78413db85d329416d392537ad9f20a1d7#diff-0f2508d8f1191fac02fd6df909c8fbd6L26) del campo fecha

**Comment by AntonioJ98** [comment]
Ups... No sabia nada al respecto, lo siento. ¿Qué puedo hacer? @profeIAP

**Comment by profeIAP** [comment]
Te he puesto el enlace al commit del problema: copia el fragmento original (el que tenía la botonera y que aparece a la izquierda en la comparación) y ponlo en el código actual de parte.php

**Comment by AntonioJ98** [comment]
¿Me dará tiempo de hacerlo mañana en clase? @profeIAP

**Comment by AntonioJ98** [comment]
Por cierto Jose Antonio, de mi tarea no hay nada que cambiar, ¿verdad?

**Comment by profeIAP** [comment]
Depende de lo que te cunda la hora de mañana.

Tu tarea estará bien una vez que dejes como estaba lo que has "toqueteado" ;)

No estoy mirando una serie de "detalles" que me van a costar invertir "puntos" en cosas que deberías haber incluido en esta tarea pero prefiero no verlos y que termines lo antes posible.

**Comment by AntonioJ98** [comment]
Vale, de acuerdo Jose Antonio ;) @profeIAP

**Comment by AntonioJ98** [comment]
Perdón, lo cerré sin querer jajajajja @profeIAP

**Comment by AntonioJ98** [comment]
Por fin XD @profeIAP

**Comment by profeIAP** [comment]
Ha quedado estupendo @AntonioJ98 
¡Gran trabajo!
