### ISSUE TITLE
Cambiar estilo títulos del modelo de documentación

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#138]
El [documento actual](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit?usp=sharing) aunque bonito:
1. no resulta intuitivo
2. el tamaño de los distintos niveles (título 1, ..., título 6) no es coherente (el título 6 es más grande que, por ejemplo, título 3)

Respetando los colores y tipografía actuales se debe:
1. Buscar alguna plantilla de documento en Internet que resuelva los problemas anteriores
2. Modificar los estilos de nuestro documento al usado por la plantilla encontrada

**Comment by profeIAP** [comment]
@josemita6 Está muy "feo" quitar el trabajo a los compañeros.
Considera esto un aviso formal... la próxima vez no será igual

**Comment by profeIAP** [comment]
Otra posibilidad es buscar algún add-on y/o la forma de numerar los apartados en según de su nivel

1.
1.1.
1.1.1.
...

**Comment by rociomacho** [comment]
Ya que Google Drive no permite la enumeración automática ni agregar distintas formas de subrayado para hacer que los apartados queden más diferenciados he optado por ordenarlo estableciendo los títulos de mayor a menor tamaño.

**Comment by profeIAP** [comment]
¿Segura que @fran98moreno (con su tarea #106)  está de acuerdo con esa afirmación?

**Comment by profeIAP** [comment]
Te incluyo comentario en el documento

**Comment by profeIAP** [comment]
No entiendo la "liá": los títulos cambian de tamaño de forma pseudo-aleatoria.

Me explico: 
- **Título 1** tamaño de letra 48
- **Título 3** tamaño de letra 20
- **Título 4** tamaño de letra 36

Parece que te ha debido bailar algo (o yo he perdido la capacidad racional de encontrar patrones en los datos XD )

**Comment by profeIAP** [comment]
Muchas gracias Rocío, ha quedado estupendo a pesar de los "pesares" ;)
