### ISSUE TITLE
Habilitar las acciones "editar" y "borrar" en el listado de notificaciones

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#139]
Igual que ocurre en la tarea #130 se necesita poder borrar (y editar) entradas de la lista de **Notificaciones**

**Comment by Patriexd** [comment]
¿Qué tengo que hacer en esta tarea @profeIAP ?

**Comment by profeIAP** [comment]
Como se indica, mira la #130 (te puede ser de ayuda)

Debes:
1. colocar correctamente las urls (falta el /notificaciones al principio) y 
2. que funcione el ID (seguramente usa la variable incorrecta en los {{XXXX.ID}} )

**Comment by profeIAP** [comment]
¡Qué bien trabajas cuando "quieres"! XD
Perfecto y a la primera, ¡buen trabajo!
