### ISSUE TITLE
Incluir campo observaciones al formulario de parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#141]
Modificar [el esbozo de la pantalla de parte](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.irh5szr1ykhh) para que incluya el campo observaciones

**Comment by mariamiura16** [comment]
ya está hecho, lo puedes comprobar en el drive de requisitos :+1:

**Comment by profeIAP** [comment]
Bien salvo que hablamos que, como buen campo de observaciones, debía ser de "tamaño grande" y no una vil caja de texto (y además, corta) como la que has puesto.

Vas a tener oportunidad de practicar tus nuevas "habilidades" con Gimp para dejarlo como se merece, ánimo ;)

**Comment by mariamiura16** [comment]
vale :( jaja pero la línea más grande o una caja ?

**Comment by profeIAP** [comment]
Una caja es lo esperado/deseable

**Comment by mariamiura16** [comment]
Despues de mucho trabajo, vuelvo a finalizar la tarea, a ver si esta vez es posible que este bien.

**Comment by profeIAP** [comment]
Ahora sí, ha quedado bastante bien.

Al final, ¿lo hiciste por tus propios medios o algún alma caritativa te ha explicado la técnica? (por agradecerle como se mere la labor o alabar tu solución ;) )

**Comment by mariamiura16** [comment]
Lo he hecho yo solita, hay pocas almas caritativas . Y ademas que soy muy cabezona y lo tenia que conseguir como fuese 💪🏼

**Comment by profeIAP** [comment]
Di que sí... lo has conseguido a fuerza de "cabezazos" (y dudo si darte la enhorabuena por haberlo logrado por "fuerza bruta" XD )

Venga va... ¡enhorabuena @mariamiura16! (te lo has currado)
