### ISSUE TITLE
Cambiar rutas para borrar/editar alumnos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#142]
Tras la reestructuración del código se debe cambiar las rutas utilizadas para borrar y editar alumnos en la vista **view/alumnos.php**

![captura de pantalla de 2016-04-20 16 31 56](https://cloud.githubusercontent.com/assets/16881846/14678532/6cf43c8a-0716-11e6-9581-20c5cedefbed.png)

Los "botones" deben utilizar
- **Borrado** /alumnos/borrar
- **Edición** /alumnos/editar

**NOTA:** dejar el parámetro ID tal cual está, sólo debe anteponerse el **/alumnos/** por delante de la acción

**Comment by profeIAP** [comment]
No tiene sentido coger esta tarea hasta que se incluyan los botones de la tarea #160

**Comment by Raul-99** [comment]
ya está hecha

**Comment by profeIAP** [comment]
Desgraciadamente, no puedo estar de acuerdo ;)

![captura de pantalla de 2016-06-01 17-33-05](https://cloud.githubusercontent.com/assets/16881846/15715545/1f9417d8-281f-11e6-8708-86fc10889756.jpg)

**Comment by profeIAP** [comment]
Igualmente debo indicar que [su último commit](https://github.com/profeIAP/panelDeControl/commit/d3db819f93c80aa7c5871ca8cb3c0e03425f8947#diff-52ef2a346517f81837f6e60c88126a1aR193) ha introducido cierto nivel de "ruido" en el proyecto

![captura de pantalla de 2016-06-02 16-17-41](https://cloud.githubusercontent.com/assets/16881846/15748056/a9b127da-28dd-11e6-9278-6ed2968896a6.png)

Como no afecta al normal funcionamiento del proyecto (aunque lo "afea") optaré por dejarle que lo corrija en lugar de hacerlo yo (y su consiguiente anotación en el "hall of blame" ;) )

**Comment by profeIAP** [comment]
¡Buen trabajo Raúl!

Por cierto, ¿por qué has optado por quitar el parámetro _?id=_ al final de las rutas (puedes verlo [en la captura del siguiente comentario](https://github.com/profeIAP/panelDeControl/issues/142#issuecomment-223032052))

**Comment by profeIAP** [comment]
Genial Raúl, ha quedado muy bien, gracias.
