### ISSUE TITLE
Renombrar formulario para listar alumnos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#144]
Renombrar tanto el fichero **view/comentarios.php** como [su invocación en index.php](https://github.com/profeIAP/proyecto2015-16/blob/8920cc69768befb2813fc5c1c47e5b788962f773/index.php#L82) para que pase a denominarse alumnos.php (tiene más sentido que el actual comentarios.php)

**Comment by profeIAP** [comment]
haz un [git pull](http://www.google.es)

**Comment by SyalChain** [comment]
@profeIAP Una menos #144

**Comment by profeIAP** [comment]
O "media tarea" menos XD

Sigue existiendo **view/comentarios.php** ¿has optado por copiar y cambiar el nombre a la copia (en lugar de renombrar directamente comentarios.php)?

**Comment by SyalChain** [comment]
@profeIAP Creo haberlo ya solucionado, el archivo que edité parecía ser copia del de comentarios. Borrado y listo.

**Comment by profeIAP** [comment]
Y muy bien que ha quedado Emilio, ¡Grazie mille!
