### ISSUE TITLE
Renombrar acción para editar usuario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#146]
Cambiar el nombre de la acción esperada para editar un usuario de **/editarUsuario** a **/editar** [en la siguiente línea de index.php](https://github.com/profeIAP/proyecto2015-16/blob/8920cc69768befb2813fc5c1c47e5b788962f773/index.php#L190)

**Comment by jairoML** [comment]
ya esta subido

**Comment by profeIAP** [comment]
Pues no se observa el cambio: 

- ni aparece un commit para esta tarea
- ni ha cambiado el nombre de la acción (sigue apareciendo /editarUsuario)

**Comment by profeIAP** [comment]
Olvida el comentario anterior (lo he borrado al no proceder)... el trabajo está perfecto.
