### ISSUE TITLE
Crear vista para listar usuarios del sistema

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#147]
Crear vista ([similar a view/partes.php](https://github.com/profeIAP/proyecto2015-16/blob/8920cc69768befb2813fc5c1c47e5b788962f773/view/partes.php) pero haciendo mención a los **usuarios**) y [cambiar la siguiente línea de index.php](https://github.com/profeIAP/proyecto2015-16/blob/8920cc69768befb2813fc5c1c47e5b788962f773/index.php#L172) para que la renderice (en lugar de a la actual comentarios.php)

**Comment by dnrg98** [comment]
Otra vez el commit se sube a nombre de usuario. Mi commit es el de tarea #147

**Comment by profeIAP** [comment]
Agradezco el comentario Daniel pero, como has puesto correctamente el número de tarea en el commit, queda perfectamente reflejado en el hilo de esta tarea (no tienes mas que mirar justo encima de tu comentario y, si te apetece, pinchar en el enlace para ver los cambios que has introducido en el código ;) )

**Comment by profeIAP** [comment]
La tarea está estupenda, ¡buen trabajo!
