### ISSUE TITLE
Esbozar pantalla Usuario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#149]
Esquematizar cómo sería la pantalla para editar los datos de un Usuario.
**OJO:** debe tenerse en cuenta que ha de mostrar la información indicada en #42

**Comment by profeIAP** [comment]
@javierfl98 asumes la penalización de quitar la tarea a @mariamiura16?!?

**Comment by javierfl98** [comment]
maria tenia 5 tareas y me dijo que le quitase esta

**Comment by profeIAP** [comment]
¿Estás de acuerdo @mariamiura16?

**Comment by Patriexd** [comment]
Qué tengo que hacer en esta tarea @profeIAP ?

**Comment by profeIAP** [comment]
Sube [aquí](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.bk2mnvcbj3mz) la imagen

**Comment by Patriexd** [comment]
Espero que esté a su agrado @profeIAP , la cierro

**Comment by profeIAP** [comment]
Hoy estás en "racha"... ha quedado espectacular, ¡enhorabuena!
