### ISSUE TITLE
Incluir recordatorio para hacer pull en README.md

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#151]
Debe incluirse una imagen tipo "warning" que acompañe al texto.

La idea es recordar a los compañeros que deben realizar un _pull_ nada mas llegar a clase antes de ponerse a trabajar.

Debe ser **bien visible**

**Comment by profeIAP** [comment]
Las imágenes puedes obtenerlas de [la siguiente web](http://findicons.com/search/alarm)

**Comment by linanalandalus** [comment]
alerta ya añadida(a ver si hacen caso...)

**Comment by profeIAP** [comment]
Algo va mal @linanalandalus 

![captura de pantalla de 2016-04-28 16 12 54](https://cloud.githubusercontent.com/assets/16881846/14888783/267c6ab0-0d5c-11e6-9eaf-9798bdbe1770.png)

**Comment by linanalandalus** [comment]
pues a mi si que me sale...
![captura de pantalla de 2016-05-03 09 48 14](https://cloud.githubusercontent.com/assets/15797268/14977475/6dffb070-1114-11e6-80d9-6bcdc6b9efe8.png)

**Comment by linanalandalus** [comment]
a lo mejor es por la conexion a internet?

**Comment by profeIAP** [comment]
Me temo que es algo más: ¿¡¿por qué usas una imagen y le pones como origen la url de la wiki?!?

![captura de pantalla de 2016-05-03 15 35 36](https://cloud.githubusercontent.com/assets/16881846/14984807/de2b7e4e-1144-11e6-91c1-bd095622e31a.png)

**Comment by linanalandalus** [comment]
ahora si que ya esta arreglado y terminado

**Comment by profeIAP** [comment]
Ahora sí, gracias Li Nan
