### ISSUE TITLE
Documentar el uso de proyectos en Geany

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#152]
Crear [documento compartido en Drive](https://docs.google.com/document/d/10oBR0YHyg4a5EKP_G94r7RhRjNqtxsv0pLvi1_s0xz0/edit?usp=sharing) que muestre la utilidad de la opción de proyectos que incluye el editor Geany

![captura de pantalla de 2016-04-21 20 08 51](https://cloud.githubusercontent.com/assets/16881846/14719516/f87ce5e0-07fc-11e6-8609-7566e1ce6f6a.jpg)

Se hará énfasis en lo útil que puede llegar a ser para evitar confusiones y conflictos cuando varias personas usan el mismo equipo para programar.

Debe hablarse de:
1. Creación de proyectos
2. Apertura de proyectos
3. Cierre de un proyecto

El último punto es importante para no dejar nuestro código abierto y que el despistado que venga detrás modifique nuestros ficheros pudiendo ocasionar alguna subida errónea al repositorio de GitHub

**Comment by Rafaelcraftero** [comment]
Ya lo he compartido contigo.

**Comment by profeIAP** [comment]
Te incluyo comentarios en el propio documento.

**Comment by Rafaelcraftero** [comment]
Ya he arreglado lo que estaba mal en el documento.

**Comment by profeIAP** [comment]
Te incluyo comentarios

**Comment by Rafaelcraftero** [comment]
He vuelto a corregir las cosas. Creo que ahora si está terminado

**Comment by profeIAP** [comment]
Al documento le queda todavía para estar listo... te incluyo comentarios y una recomendación personal: ve al grano (céntrate en lo realmente importante) y olvida las "florituras" (confunden al lector y hace que se pierda tanto la atención como el interés)

**Comment by Rafaelcraftero** [comment]
TErminado

**Comment by profeIAP** [comment]
Mejor no lanzamos las campanas al vuelo

**Comment by Rafaelcraftero** [comment]
MIrame si está por fín terminado.

**Comment by profeIAP** [comment]
Falta menos pero sigue enredado...

**Comment by Rafaelcraftero** [comment]
Mira a ver si te gusta como está terminado

**Comment by profeIAP** [comment]
Está muchísimo mejor pero alcanzar la perfección es difícil... te dejo algunas anotaciones para que te resulte más sencillo alcanzarla ;)

**Comment by Rafaelcraftero** [comment]
gracias por las anotaciones.

**Comment by profeIAP** [comment]
Gracias a ti por un gran trabajo.
