### ISSUE TITLE
Recortar logotipo en SVG

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#154]
Eliminar la gran cantidad de espacio en blanco existente en [el logotipo actual](https://drive.google.com/file/d/0B7C0XACByqOOSmNxR1V2UjVFR2M/view?usp=sharing)

El fichero debe seguir en formato SVG pero apareciendo únicamente lo que realmente importa: **el logo**

**Comment by profeIAP** [comment]
Genial Antonio, ¿qué programa has usado para editar el fichero SVG?

**Comment by AntonioJ98** [comment]
Uno que tomé como recomendación de un blogero. Un tal informático de guardia o algo asi.... ;) Jajajaja @profeIAP

**Comment by profeIAP** [comment]
Buen tipo el Informático de Guardia... incluye el enlace al artículo y/o indica el nombre del programa para que pueda ser utilizado por otros compañeros ;)

**Comment by AntonioJ98** [comment]
Claro. @profeIAP . Online Image2SVG converter : http://www.mobilefish.com/services/image2svg/image2svg.php

**Comment by profeIAP** [comment]
Qué bien trabajas, cuando trabajas bien... :)

¿He de suponer que has recortado con Gimp el logotipo (formato jpg y/o png) y utilizado image2SVG para volver a convertirla en SVG?

**Comment by AntonioJ98** [comment]
Efectivamente @profeIAP

**Comment by profeIAP** [comment]
Lo sospeché desde un principio... ha quedado genial aunque me hubiese gustado que adquirieses una nueva "habilidad".

Aprovecharé la oportunidad para crear una nueva tarea ;)

Gracias Antonio
