### ISSUE TITLE
Cargar datos reales en la tabla de alumnos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#155]
Quitar los datos "ficticios" que ha puesto (a modo de ejemplo) @Mahc99 en el [listado de alumnos](http://localhost:9000/alumnos) y mostrar los que realmente se encuentran almacenados en la base de datos.

El controlador ya [se encarga de leer y pasarnos los alumnos](https://github.com/profeIAP/proyecto2015-16/blob/a8ebcee292f8e74b57c7bf381699097746102bf1/index.php#L77-L85), tu trabajo es únicamente que aparezcan en la vista.

**Comment by profeIAP** [comment]
Lo más complicado será meter el bucle para que vaya generando las filas de datos de la tabla pero tenemos varios [ejemplos de cómo hacerlo](https://github.com/profeIAP/proyecto2015-16/blob/a8ebcee292f8e74b57c7bf381699097746102bf1/view/rss.php#L5-L14) en nuestras vistas

**Comment by JVG13** [comment]
Continúo sin poder avanzar en la tarea... 

Según dice (algo más arriba) me lo explica de una manera diferente a la que tú me dijiste o puede ser que sea otra cosa. 

He estado mirando los enlaces que hay más arriba pero no encuentro solución

**Comment by profeIAP** [comment]
Básate en lo que te expliqué yo, los enlaces de arriba son ejemplos no una plantilla para usar tal cual en la solución que debes proporcionar a esta tarea ;)

**Comment by profeIAP** [comment]
Jesús, antes de dar por cerrada la tarea, asegúrate que estás poniendo los valores de **ID** en los botones editar/borrar alumno (gracias)

![captura de pantalla de 2016-06-06 17 43 55](https://cloud.githubusercontent.com/assets/16881846/15828367/51a5cd2c-2c0f-11e6-9d64-ebc681587e67.jpg)

**Comment by JVG13** [comment]
ya he acabado la tarea y he realizado el git push correctamente cierro la tarea

**Comment by profeIAP** [comment]
Me gustaría creerte Jesús, pero sigue sin aparecer el ID (recuerda usar {{alumno.ID}} en los enlaces de los botones borrar y editar)
