### ISSUE TITLE
Quitar IES Al-Ándalus del logo del proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#156]
Recortar [la imagen utilizada](https://github.com/profeIAP/proyecto2015-16/blob/master/img/logo.png) como logotipo para que no incluya el nombre del instituto.

Se supone que este proyecto podría utilizarse en cualquier centro.

**Comment by profeIAP** [comment]
Agradecería la incluyeses en la carpeta **img** del proyecto para que todos podamos "disfrutarla" ;)

**Comment by AntonioJ98** [comment]
¿A qué te refieres con carpeta img? @profeIAP

**Comment by profeIAP** [comment]
A que sustituyas la que cogiste (estaba en la carpeta img del proyecto) por la que has recortado (y la subas al repositorio)

**Comment by profeIAP** [comment]
Fantástico pero no has **sustituido** el logo por el nuevo: lo has incluido como logo1.png y "conviven" los dos en el directorio.

Recomiendo:
1. Borrar logo.png
2. Renombrar logo1.png a logo.png
3. Subir los cambios al repositorio :)

**Objetivo:** que desaparezca de una vez el logo "antigüo" y que aparezca el tuyo (sin letras) en la cabecera de nuestra web

**Comment by AntonioJ98** [comment]
De acuerdo, el miércoles lo hago desde clase. @profeIAP

**Comment by profeIAP** [comment]
Y te ha quedado genial, muchas gracias
