### ISSUE TITLE
Esbozar pantalla Asignación de Tutores

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#157]
Esquematizar [cómo sería la pantalla](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.7vd6m09yp57k) para indicar qué profesores ejercerán de tutores de los distintos grupos de nuestro instituto.

Debe ser rápida, sencilla y eficiente.

La imagino en dos columnas:
1. En la **izquierda** (sólo etiquetas, no editables) los nombres de los cursos
2. En la **derecha** cajas de texto donde poder ir escribiendo los nombres de los profesores (con autocompletado)

Es sólo una propuesta; se admite cualquier idea que ayude a hacerla lo más cómoda posible de usar

**Comment by j1m1** [comment]
Ya está añadida a el documento: requisitos funcionales

**Comment by profeIAP** [comment]
Agradecería recortases la "basurilla" que ha quedado en la parte de abajo de la pantalla (puntos de colores)

Igualmente cambiaría los botones pues no se entiende qué significan los cuadrados a la izquierda de las opciones "Aceptar" y "Cancelar"

**Comment by j1m1** [comment]
he recortado las manchas que aparecían y he decido cortar y eliminar también la opción aceptar/ cancelar que había quedado un poco mal, y creo que se podría ignorar

**Comment by profeIAP** [comment]
¿Qué [versión del documento](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.7vd6m09yp57k) estás utilizando?

Ten en cuenta que @rociodanone3 está cambiando la estética

Yo lo veo como antes.

**NOTA:** aunque más cómodo, quitar los botones no lo considero una opción

**Comment by j1m1** [comment]
acabo de subir el mismo boceto pero con la opción "aceptar/cancelar" más clara.

**Comment by profeIAP** [comment]
Fantástico @j1m1 pero recuerda:
1. Debes pasar el filtro de Gimp para que no se note que hemos hecho una foto (espero que el "typex" no se note demasiado tras hacerlo ;) )
2. Elimina la que no sirve

**Comment by j1m1** [comment]
He decidido hacerlo ahora de nuevo y no esperar a perder la hora mañana. Espero que te guste !

**Comment by profeIAP** [comment]
Me parece buena decisión optar por hacerlo en casa y dedicar la hora de clase para tareas que requieran otras herramientas o preguntar a los compañeros, ¡bien hecho Jesús!

**Recorta** algo la foto (no cabe en una página y le está sobrando la mesa que se ve por abajo del folio) y no olvides **aplica**r el **filtro** de Gimp para que no se note que es una foto ;)

**Comment by j1m1** [comment]
Los efectos de la luz molestan un poco pero ya he conseguido que esté mejor.

**Comment by j1m1** [comment]
¡ ahora sí que sí !

**Comment by j1m1** [comment]
¿Documentar mi trabajo es una tarea? Si no lo hace nadie lo hago yo mismo. (Objetivo: mejorar mi nota 😂)

**Comment by profeIAP** [comment]
Sabes que aprecio y valoro la iniciativa personal, Jesús ¿Qué parte de tu trabajo consideras interesante/importante documentar?

Por cierto, la tarea ha quedado perfecta ¡Enhorabuena! (y gracias)
