### ISSUE TITLE
Cambiar tipo al campo PARTES.ID_ALUMNO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#158]
Está definido como tipo TEXT cuando realmente debería ser INTEGER.

Debe actualizarse la base de datos [como el script](https://github.com/profeIAP/proyecto2015-16/blob/a8ebcee292f8e74b57c7bf381699097746102bf1/model/scripts/partes.sql).

**Comment by semacg98** [comment]
Ya esta cambiado.

**Comment by profeIAP** [comment]
Sí que lo has subido pero [no has corregido los errores de 'merge' en el fichero model/scripts/partes.sql](https://github.com/profeIAP/proyecto2015-16/commit/d2afb06e3c1106db7eceafb4b9b706af14a1b3db)
Igualmente, se ve que has usado una versión antigüa, has devuelto el campo 'CURSO Y GRUPO' que corregimos en la tarea #135

**Comment by semacg98** [comment]
Ya creo que está bien.. jajaja

**Comment by profeIAP** [comment]
Doy fe de ello... gracias "Semita"
