### ISSUE TITLE
Implementar el almacenamiento de un Parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#159]
Implementar el [almacenamiento en la BD](https://github.com/profeIAP/proyecto2015-16/blob/0a4a69261f4aedcf7b54d004bcfe9ad07f8a93d3/index.php#L253-L289) de un parte de incidencia.

Lo etiqueto como "reto" por la gran cantidad de campos que contiene la tabla asociada no por su dificultad.

**Comment by profeIAP** [comment]
Dentro de **index.php** deberá ser incluido como **/partes/guardar**

**Comment by dnrg98** [comment]
El [commit está hecho](https://github.com/profeIAP/panelDeControl/commit/72eb6878f222a4039dbf1b1c0ee214a44808f913) pero sale que lo ha hecho "usuario" a la próxima hago git config user.name

**Comment by profeIAP** [comment]
Sí señor, veo que eres consciente tanto del problema como de la solución ¡Enhorabuena Daniel!

Gracias por avisar (pues me facilita el trabajo y puedo dedicar más tiempo tanto a ti como al resto de tus compañeros).

Para que sea incluso más perfecto, recuerda poner la almohadilla delante del número de tarea para que aparezca el commit entre los comentarios de la tarea ;)
