### ISSUE TITLE
Incluir botones editar/borrar alumno en listado de alumnos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#160]
La tabla actual, no incluye los botones de edición y borrado.

**Comment by josemita6** [comment]
que tenia que modificar el index? que ya no me acuerdo

**Comment by profeIAP** [comment]
No, [la vista comentarios.php](https://github.com/profeIAP/panelDeControl/blob/09e695d4f1c5fd963b39cdc26d427138fd82fffe/view/comentarios.php) aunque, ten cuidado, si @Isa70199 termina su tarea #144, deberás usar **view/alumnos.php**

**Comment by josemita6** [comment]
no me la vayas a abrir mas que me suicido, gracias.

**Comment by profeIAP** [comment]
Cuidado con el vocabulario utilizado Medina: debes distinguir el coloquial (y con los colegas) del laboral y/o académico (con tu profesor).

La tarea está pseudo terminada pero podríamos darla por buena (ya "invertiré" puntos para que otro pula lo que no está del todo bien)
