### ISSUE TITLE
Eliminar opción "Gráficas" del menú principal

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#163]
Quitar la opción subida por @rociomacho  para mostrar su página de gráficas.

![captura de pantalla de 2016-04-25 16 07 04](https://cloud.githubusercontent.com/assets/16881846/14786633/15fbd166-0b00-11e6-9d26-6b4e741e02a9.png)

**Comment by profeIAP** [comment]
Sigo sin poder dar por finalizada la tarea:
1. No existe ningún commit de tu usuario
2. No existe mención a esta tarea en los commits
3. El código sigue estando donde no debe

**Comment by profeIAP** [comment]
Nachooooo....
1. Te has cargado la BD (ha dejado de tener tablas)
2. El menú se ha ido al garete

Tienes dos opciones:
1. Arreglarlo tú
2. Lo hago yo pero te penalizo :)

**Comment by nachowe12** [comment]
Terminada la tarea pero no puedo quitar el punto

**Comment by profeIAP** [comment]
No la puedo dar por buena al seguir estando el "punto" y haber dejado de funcionar la opción Alumnos del menú

**Comment by jasvazquez** [comment]
Implemento la tarea
