### ISSUE TITLE
Crear copias locales de todos los javascripts usados por el proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#165]
Descargar e Incluir en la carpeta **js** todos los ficheros asociados a las librerías javascript usadas por nuestro proyecto.

La conexión en el centro es lamentable y aunque usen CDN se hace eterno el renderizado de la página.

Deberán modificarse las vistas para que apunten a nuestra copia local

**NOTA:** no olvidéis usar rutas absolutas (la url al fichero local debe empezar por **/js/**XXX)

**Comment by angel2190** [comment]
listo

**Comment by profeIAP** [comment]
La verdad es que le has cogido el truco pronto @angel2190 (enhorabuena)

Algunas observaciones:
- Se te ha escapado **bootstrap**
- Hay formularios que usan scripts (te recomiendo lanzar `grep -lir "<script" view/*` para localizarlos)
- ¿Qué son los ficheros localNN,js?

![captura de pantalla de 2016-05-30 19 25 04](https://cloud.githubusercontent.com/assets/16881846/15655314/457c8b30-269c-11e6-99be-4672f359b732.png)

**Comment by angel2190** [comment]
listo

**Comment by profeIAP** [comment]
Fantástico Ángel, ahora va como un "tiro" la web.
Gracias
