### ISSUE TITLE
Crear copias locales de todas las hojas de estilo usadas por el proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#166]
Descargar e Incluir en la carpeta **css** todos los ficheros asociados a las hojas de estilo usadas por nuestro proyecto.

La conexión en el centro es lamentable y aunque usen CDN se hace eterno el renderizado de la página.

Deberán **modificarse las vistas** para que apunten a nuestra copia local

**NOTA:** no olvidéis usar rutas absolutas (la url al fichero local debe empezar por **/css/**XXX)

**Comment by angel2190** [comment]
ya estan subidos los cambios

**Comment by profeIAP** [comment]
Lo siento pero en layout.php quedan hojas de estilo apuntando a internet (p.e. jquery.dataTables.min.css)

**Comment by angel2190** [comment]
creo que ya esta bien

**Comment by profeIAP** [comment]
Está perfecto el cambio pero faltan algunos ficheros (básicamente _fontawesome_) lo que provoca que no aparezcan los iconos

![captura de pantalla de 2016-05-18 18 28 16](https://cloud.githubusercontent.com/assets/16881846/15366853/9635fc70-1d26-11e6-8606-8c059c30d88a.jpg)

**Comment by angel2190** [comment]
listo

**Comment by angel2190** [comment]
listo

**Comment by profeIAP** [comment]
Ahora sí Ángel, ¡ha quedado perfecto! (se ven los iconos de nuevo ;) )

Siguen quedando algunos ficheros en "remoto"

![captura de pantalla de 2016-05-23 16 37 53](https://cloud.githubusercontent.com/assets/16881846/15474344/c752bd02-2104-11e6-88ae-7fc00bda1197.png)

Pero, si te parece, céntrate en los que están en rojo (no existen), es posible que:
1. hayas escrito mal el nombre
2. no sean necesarios por estar duplicados con distinto número (¿que diferencia hay entre datatable y datatable5?)

**Comment by angel2190** [comment]
ya

**Comment by profeIAP** [comment]
Genial, ¡muchas gracias Ángel!

Como premio (y agradecimiento) al buen trabajo realizado, opto por etiquetar como "reto" la tarea.

Sigue así que, poco a poco, saldrá a la luz tus dotes para la informática que, hasta ahora, las tienes un poco ocultas ;)
