### ISSUE TITLE
Crear favicon con el logo del proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#167]
Crear, a partir del fichero SVG del logotipo del proyecto (tarea #154), una imagen de 32x32.

El usar el SVG es porque no pierda calidad.

Debe usarse la versión de logotipo sin letras (a 32x32 píxeles no habría forma humana de leerlos y quedaría echo un "churro)

**Comment by fran98moreno** [comment]
Esta tarea es casi imposible de realizar al querer mantener el SVG pues segun : http://ayudacreandounblog.blogspot.com.es/2015/02/5-formas-de-crear-un-favicon.html ''Extensión .svg: demasiado nueva, sólo Opera la lee pero sería la extensión ideal y probablemente acabe convirtiéndose en la norma.'' Como se observa es la más óptima pero solo Opera puede realizar esa acción y no disponemos de ese programa :S

**Comment by fran98moreno** [comment]
puedo hacerlo con ICO? según la misma fuente: Extensión .ico: El archivo con esta extensión será el mejor soportado por los navegadores. También es el único formato que el navegador detectará sin usar el elemento . Soporta transparencia alpha.

**Comment by profeIAP** [comment]
**Debes** hacerlo en formato .ico (también admite .jpg y .png pero el ideal es el que propones)

Cuando decía que debías utilizar el .svg me refería como base para crear el otro fichero: SVG escala muy bien por lo que podrás (una vez quites las letras que aún le quedan al logotipo) redimensionarlo a 32x32 con más calidad (dentro de la poca "información" que caben en 1024 píxeles cuadrados jojojo)

Te recomiendo hablar con @AntonioJ98 pues se ha encargado de la tarea #154

**Comment by fran98moreno** [comment]
compartido

**Comment by profeIAP** [comment]
Súbela al repositorio del proyecto con nombre **favicon.ico** y tamaño 32x32 (la que has proporcionado es de 64x64) ¿es por algún motivo en especial o por un despiste "en general"? :P

**Comment by profeIAP** [comment]
Qué desperdicio de espacio ¿no?
Lo digo porque, aunque es 32x32, hay demasiado espacio en blanco como para que la imagen se vea bien.
Agradecería que le dieses un repaso una vez más (sorry)

**Comment by fran98moreno** [comment]
a ver si ya

**Comment by profeIAP** [comment]
Salvo que el nombre no es el adecuado (le pediremos al que lo incluya que cambie el nombre) para ser utilizado (favicon.ico) te ha quedado espectacular. ¡Gracias Fran!
