### ISSUE TITLE
Añadir botonera al formulario Parte.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#169]
Añadir tres botones al formulario view/parte.php de modo que incluya las siguientes acciones sobre el formulario:
1. Cancelar (rojo)
2. Guardar (¿azul?)
3. Aceptar (verde)

**NOTA:** El orden debe ser el que aparece en la lista anterior (el botón más a la izquierda será Cancelar y el de la dcha. del todo "Aceptar")

De especial utilidad será la documentación actualmente existente en [la documentación de Bootstrap](http://v4-alpha.getbootstrap.com/components/buttons/)

**Comment by jonathan1328** [comment]
Ya está la bononera al formulario de partes, y funciona correctamente. Aquí tienes [el link  ](http://localhost:9000/partes/crear)

**Comment by profeIAP** [comment]
Sospecho que no has debido subir los cambios al repositorio.
Sigo viendo el "triste" (y gris) botón Aceptar de siempre :(

**Comment by jonathan1328** [comment]
Cadena está de testigo de que hice un commit y no me dio ningún problema, mañana lo intentaré de nuevo @profeIAP

**Comment by profeIAP** [comment]
Creo en tu palabra, no metas a @SyalChain ;)

¿Puede que no hicieses [el "push"](https://github.com/profeIAP/panelDeControl/wiki#subida)?

**Comment by jonathan1328** [comment]
Ya estáááááááááááááááááááááááá @profeIAP

**Comment by profeIAP** [comment]
Sí, pero:
1. te has cargado [la lista desplegable de las horas](https://github.com/profeIAP/panelDeControl/commit/a4d34d1e95570bdae182b12f4845688e64a3b4f1) del bueno de @javierfl98 
2. el botón "Enviar" no debería estar

**Comment by profeIAP** [comment]
Todos los botones invocan la misma acción **/partes/guardar**

Agradecería me indicases por qué no has optado por recuperar la lista desplegable de las horas que eliminaste.

**Comment by profeIAP** [comment]
Perfecto Jonathan, buen trabajo
