### ISSUE TITLE
Listar entradas en formato "tabla"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#17]
Usar una tabla para mostrar, mediante filas, todas las entradas de la BD.
Esta funcionalidad será utilizada por el resto de listados de entradas

**Comment by profeIAP** [comment]
Se usará los datos de cualquiera de las tablas existentes en la BD o bien ponerlos directamente en las filas de dicha tabla dentro del html.

Existen ejemplos de tablas (en Bootstrap que es la plantilla estética que estamos usando) en internet; algunos ejemplos:
1. [Tabla con funcionalidad adicional](http://issues.wenzhixin.net.cn/bootstrap-table/)
2. Sintaxis básica de las [tablas en BootStrap](http://v4-alpha.getbootstrap.com/content/tables/)

**Comment by Mahc99** [comment]
Tarea terminada ~~

**Comment by profeIAP** [comment]
Espectacular, realmente espectacular.
Gran trabajo Migue (diga lo que diga el "envidioso" de @julioosos jojojo)
Muchísimas gracias

**Comment by profeIAP** [comment]
Este logro merece ser "loado" en el blog.
Lo dejo como sugerencia para los autores menos creativos de la tarea #70
