### ISSUE TITLE
Tabla tutoría

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#171]
Crear tabla para almacenar los tutores de cada grupo.

Dicha tabla debe contener los campos:
- ID
- ID_ALUMNO
- ID_USUARIO

**Comment by antoniio92** [comment]
SUBIDO CON EXITO!

**Comment by profeIAP** [comment]
¿Y tú eres el que decías que se te daba mal la "programación"? ;)

Buen trabajo Antonio salvoooo... que acabo de ver (éso me pasa por mirar) que has definido los campos ID_XXXX de tipo texto cuando, al tratarse de identificadores, deberían ser de tipo INTEGER

Mas que como un problema, te recomiendo enfocarlo como una oportunidad para practicar el uso de GIT ;)

Ánimo, que es una chorrada

**Comment by antoniio92** [comment]
LISTO YA ESTA CAMBIADO A INTEGER !

**Comment by profeIAP** [comment]
Perfecto
