### ISSUE TITLE
Hacer no editables los campos Curso y Asignatura de Partes.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#172]
Evitar que el usuario pueda modificar el contenido de los campos Curso y Asignatura d[el formulario Partes.php](http://localhost:9000/partes/crear)

Se etiqueta como "Reto" al ser la primera vez que abordamos este tipo de tareas y requerir cierta investigación.

**Comment by danigomez99** [comment]
Profesor dame una guía que no se hacer la tarea.

**Comment by profeIAP** [comment]
Te [la di en mi mesa](https://goo.gl/ZoUV9x) "desmemoriado"

**Comment by danigomez99** [comment]
Pero la necesito escrita porque mi mente no da para tanto.

**Comment by profeIAP** [comment]
:+1:

**Comment by danigomez99** [comment]
po yasta, si no me la das no empezaré en la vida porque no tengo ni idea.

**Comment by danigomez99** [comment]
:-1:

**Comment by profeIAP** [comment]
Observa que, en [este comentario](https://github.com/profeIAP/panelDeControl/issues/172#issuecomment-220997350), te he dejado un enlace para que veas cómo se hace.

Para dar por cerrada esta tarea [exigiré que corrijas la falta de ortografía](https://github.com/profeIAP/panelDeControl/issues/172#issuecomment-221547922) de tu anterior comentario ;P

**Comment by danigomez99** [comment]
lo he hecho queriendo jajajaj

**Comment by profeIAP** [comment]
#define yasta

![](http://paginabierta.mx/sitio/wp-content/uploads/2014/11/29pip.jpg)

**Comment by danigomez99** [comment]
Ya está terminada.

**Comment by danigomez99** [comment]
La cierro.

**Comment by danigomez99** [comment]
tarea finalizada.

**Comment by profeIAP** [comment]
Fantástico @danigomez99, ha quedado espectacular... ya tenéis idea para una posible publicación en el blog (tarea #70)
