### ISSUE TITLE
Ordenar opciones del menú superior

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#173]
Cambiar la ubicación de las opciones del menú superior de la aplicación de modo que "Inicio" esté a la derecha y "Acerca de" a la izquierda

![captura de pantalla de 2016-04-27 09 07 55](https://cloud.githubusercontent.com/assets/16881846/14844461/cd134962-0c57-11e6-88f3-9c7dfac35077.jpg)

**Comment by profeIAP** [comment]
No hay commit y las opciones de menú siguen estando como siempre.
Quedo a la espera de que subas el cambio Raúl

**Comment by ghost** [comment]
Terminada :)

**Comment by profeIAP** [comment]
A la primera y sin "fisuras", ¡buen trabajo!
