### ISSUE TITLE
Redireccionar a la página de inicio al pinchar sobre el logo de la web

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#174]
Cuando se haga "click" sobre el icono de la aplicación, deberá mostrarse la página de inicio.

Para ello debe añadirse un enlace a la imagen que direccione a la dirección base de nuestra web

> <a href="/"> xxxxx </a>

**Comment by AbrahamgcArahal** [comment]
ya he terminado y subido la tarea

**Comment by profeIAP** [comment]
Y a la primera (enhorabuena)... ¡qué no pare el ritmo Abraham! (que pareces estar en "racha")
¡Ánimo!
