### ISSUE TITLE
Crear "Hall of Blame" v2.0

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#176]
Pasa el documento "Hall of Blame" (tarea #150) a una [hoja de cálculo de Google Sheets](https://docs.google.com/spreadsheets/d/1l1e95Witjb32cqwsGMdJKBEEs54ahocouJtckO9dZo0/edit?usp=sharing) compartida con el profesor.

La idea es poder utilizar la información almacenada en ella a la hora de estimar las penalizaciones que deben aplicarse a los alumnos que, de forma reiterada, alteran el trabajo del resto de sus compañeros.

**Comment by profeIAP** [comment]
Viniendo de ti, esperaba algo con más "estilo"
Imita (aunque sea) la estética sugerida por @fran98moreno :P

**Comment by antoniio92** [comment]
¿Bien de estilo ya? jajajaj

**Comment by antoniio92** [comment]
¿Bien de estilo? jajajaj

**Comment by profeIAP** [comment]
Simpático sí que es... lo damos por finalizado.
Gracias Antonio
