### ISSUE TITLE
Listar asignaturas

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#177]
Crear vista en la BD que permita obtener las distintas asignaturas utilizadas en los partes actualmente registrados en el sistema.

Deberá usarse la cláusula "distinct" en la sentencia SQL.

IMPORTANTE: No olvides incluir la sentencia SQL que permite crear la vista dentro de la carpeta /model/scripts

**Comment by linanalandalus** [comment]
ya acabo de hacer el script de listarasignaturas en partes

**Comment by profeIAP** [comment]
Veo que te has convertido en un auténtico maestro de las consultas (y/o vistas)
¡Buen trabajo Li Nan!
