### ISSUE TITLE
Cambiar url del repositorio en la Wiki

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#179]
Editar la [wiki del proyecto](https://github.com/profeIAP/panelDeControl/wiki#descargar-proyecto-completo) para que todas las referencias a nuestro repositorio pasen de

> https://github.com/profeIAP/proyecto2015-16.git

a

> https://github.com/profeIAP/panelDeControl

**Comment by pablosaborido** [comment]
ya esta to flamaaaaaa

**Comment by profeIAP** [comment]
Sí señor, ¡hasta "brilla" y tó!
Buen trabajo, Pablo
