### ISSUE TITLE
Exportar a pdf

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#18]
Estudiar el modo de generar pdfs en php como salida de los listados que se generarán

**Comment by profeIAP** [comment]
El objetivo sería buscar una librería que permita hacerlo y hacer una pequeña prueba que demuestre cómo funciona

**Comment by josufg** [comment]
He encontrado una librería para php que se llama [fpdf](http://www.fpdf.org/) @profeIAP . Me pongo manos a la obra investigando para conocer su funcionamiento.

**Comment by jasvazquez** [comment]
Lo ideal sería utilizar una librería que permita generar un pdf a partir de un html y/o un csv.

fPDF es muy potente pero requiere generar (paso a paso) el pdf completo y se escapa al tiempo y requisitos que tenemos

**Comment by josufg** [comment]
@profeIAP He estado investigando y la librería o extensión más sencilla que he encontrado para generar pdf a partir php es fpdf. He encontrado otras como tcpdf, R&OS, FPDI y DOMPDF. Barajo ponerme con DOMPDF o FPDF.

**Comment by profeIAP** [comment]
Como comentamos anteriormiente, descarta fPDF (por complejo).

DOMPDF parece bastante más sencillo y útil. He encontrado [el siguiente ejemplo de uso](https://goo.gl/2X4f4f) que podría adaptarse a nuestras necesidades. Prueba que funcione en nuestro proyecto y contaremos con una fantástica funcionalidad.

¡Suerte!

**Comment by profeIAP** [comment]
Ejemplo de [uso básico de domPDF](https://oscargascon.es/uso-de-dompdf-para-generar-pdf-con-php-html-y-css/)

**Comment by josufg** [comment]
@profeIAP Ya he conseguido que el localhost arranque a la perfección, es decir, que dompdf está sin errores en funcionamiento. ¿Ahora qué debo hacer para descargar un pdf desde localhost?

**Comment by profeIAP** [comment]
Como comentamos en clase, debes meter el código de tu ejemplo en un método GET (sirva como recomendación de ejemplo **'/pdf'**) y comprobar si el navegador ([cuando usas dicha ruta](http://localhost:9000/pdf)) te devuelve un pdf.

**Comment by josufg** [comment]
@profeIAP Como te he comentado me falla el /pdf porque no carga la libreria dompdf. Mientras investigas el fallo con las dependencias(ahi creo que está el fallo) voy a acabar la tarea #71

**Comment by profeIAP** [comment]
Anotado queda, gracias Josué

**Comment by josufg** [comment]
@profeIAP  Terminada. Crear tarea para documentar la instalacion de dompdf(tener en cuenta libreria gd. La cierro.

**Comment by profeIAP** [comment]
Ha quedado espectacular, muchas gracias Josué.

¿Quién se invita a contar en el blog que ya contamos con [la funcionalidad de generar PDFs](http://localhost:9000) en nuestra web? #70
