### ISSUE TITLE
Incluir editor WYSIWYG en las observaciones de un parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#182]
Elegir (e incluir) un editor de textos tipo WYSIWYG (What You See If What You Get) en el textarea de las observaciones de un parte.

Sirvan como posibles alternativas [los que aparecen en el siguiente artículo](http://www.sitepoint.com/10-best-html-wysiwyg-plugins/) pero se podría utilizar cualquier otro.

La idea es poder "enriquecer" la descripción del motivo por el que se pone un parte de disciplina.

**Comment by linanalandalus** [comment]
ya esta hecho

**Comment by profeIAP** [comment]
Observo que eres el responsable de haber "estropeado" el trabajo de @javierfl98 en su tarea #184 

Entiendo que no ha sido intencionado (en caso contrario hubieses acabado fusilado en el paredón :P ) y que se debe a un problema con el "merge" de vuestros cambios.

Dejo abierta la tarea mientras solucionas el "estropicio"

**Comment by linanalandalus** [comment]
ya he arreglado mi estropicio

**Comment by profeIAP** [comment]
Genial Li Nan ¡fantástico trabajo!
Muchísimas gracias
