### ISSUE TITLE
Definir como combo el campo PARTE.HORA del formulario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#183]
Cambiar el formulario view/parte.php para que **la Hora** 

![captura de pantalla de 2016-05-03 17 11 39](https://cloud.githubusercontent.com/assets/16881846/14988112/d55f980a-1152-11e6-8fd1-f99260ed2f91.png)

sea una lista desplegable con los valores
1. Primera
2. Segunda
3. Tercera
4. Recreo
5. Cuarta
6. Quinta
7. Sexta

Tienes ejemplo de [cómo definir un combo en el siguiente enlace](http://getbootstrap.com/components/#dropdowns)

**Comment by javierfl98** [comment]
Tarea realizada

**Comment by profeIAP** [comment]
Independientemente de no ocupar todo el espacio disponible (no le hemos dado importancia pero puede que cuando arregles lo que te voy a comentar se pueda solucionar) observa que resulta imposible seleccionar un valor.

**Comment by javierfl98** [comment]
problema arreglado

**Comment by profeIAP** [comment]
Pero has metido otro problema

![captura de pantalla de 2016-05-13 18 41 36](https://cloud.githubusercontent.com/assets/16881846/15255123/6be5591a-193a-11e6-9a48-10dedf385dd5.png)

**Comment by javierfl98** [comment]
terminado porfiiiinnnn

**Comment by profeIAP** [comment]
Y [ha quedado bonito](https://github.com/profeIAP/panelDeControl/commit/b5770e3a15520f61d8ea1990d2fc9ab041c63397) y todo ¡Buen trabajo Javi! (pero recuerda indicar en los commits el número de tarea para que no haya que ir a buscarlo a las subidas de código)
