### ISSUE TITLE
Incluir calendario al campo PARTE.FECHA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#184]
Modificar el formulario **view/parte.php** para que el campo FECHA incluya la posibilidad de seleccionar una fecha (evitando tener que introducirla manualmente)

![captura de pantalla de 2016-05-03 17 16 31](https://cloud.githubusercontent.com/assets/16881846/14988167/100c4bc4-1153-11e6-871c-69e934950904.png)

Te resultará de especial utilidad el trabajo realizado en las tareas #91 y #92

**Comment by javierfl98** [comment]
terminado

**Comment by profeIAP** [comment]
Buen trabajo Javi, lástima que alguien se haya cargado tus cambios.
No es problema tuyo, busco al responsable y que lo solucione.
Muy buen trabajo, gracias
