### ISSUE TITLE
Añadir sistema logging

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#185]
Con objeto de poder volcar información a los ficheros de log (que ayuden a detectar posibles fallos) se requiere añadir al proyecto algún sistema de logging.

Entre los existentes recomiendo [KLogger](https://github.com/katzgrau/KLogger#installation) (aunque [existen más](http://stackoverflow.com/questions/341154/php-logging-framework)) por 
- conocerlo (lo he usado en proyectos personales) y 
- resultar sencillo de utilizar

El objetivo es: 
1. incluirlo en el proyecto (añadiendo a composer.json)
2. Añadir una anotación tipo "debug" en [el get de la raíz del proyecto](https://github.com/profeIAP/panelDeControl/blob/e0985d10c738f886240acbc1a201522afab52cf1/index.php#L67-L70)

**Comment by alexrueda7** [comment]
Ha costado pero ya está hecha.

**Comment by profeIAP** [comment]
Un gran paso para el proyecto Alejandro, ¡muchas gracias! (nos va a venir de lujo en futuras versiones del proyecto)
