### ISSUE TITLE
Documentar cómo insertar la fecha del sistema en la BD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#188]
Crear [documento compartido en Drive](https://docs.google.com/document/d/12xUXJVmHaz0dJU-MKhlcwfSe-_PTxj_Mk9vSwjBWrHI/edit) en el que se explique cómo insertar automáticamente la fecha (y hora) actuales.

Valdrá enfocar la solución desde alguno de los siguientes puntos:
1. Valor por defecto de una columna
2. Uso de triggers

**Comment by Mahc99** [comment]
Ya [he compartido el archivo](https://docs.google.com/document/d/12xUXJVmHaz0dJU-MKhlcwfSe-_PTxj_Mk9vSwjBWrHI/edit?usp=sharing) contigo.

**Comment by profeIAP** [comment]
Está casi perfecto salvo por por el uso del término "insertar" (no es lo que realmente se está haciendo)

Falta insertar en un campo (recuerda: valor por defecto o trigger) el valor que obtienes.

**Comment by profeIAP** [comment]
Una posible referencia al [trigger de insert](http://stackoverflow.com/a/16886556)

**Comment by Mahc99** [comment]
Si hay suerte esta terminada =P

**Comment by profeIAP** [comment]
Perfecto salvo un par de "detallitos" :)

**Comment by Mahc99** [comment]
"Detallitos" corregidos ^^

**Comment by profeIAP** [comment]
Vamos a tener que crear una tarea explicando cómo se utilizan los títulos en Drive ¿¡¿no te parece?!? ¬ ¬

**Comment by Mahc99** [comment]
Los titulos son mi criptonita, pero creo que ya lo he puesto bien. T_T

**Comment by profeIAP** [comment]
Oeeee....oe, oe, oé...
