### ISSUE TITLE
Borrar alumno

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#19]
Eliminar entrada de la bd

**Comment by Cesarj9** [comment]
Esto esta hecho

**Comment by jasvazquez** [comment]
Tienes toda la razón del mundo... la cierro pues no hay ni que hacerla.
Gracias por avisar, César.

**Comment by profeIAP** [comment]
Tienes toda la razón del mundo... la cierro pues no hay ni que hacerla.
Gracias por "avisar", @Cesarj9

**Comment by Cesarj9** [comment]
No es nada, yo solo quiero la puntuacion porque antes de quitarla, me tomo
mi tiempo ;)

**Comment by profeIAP** [comment]
LOL!
