### ISSUE TITLE
Gestionar la subida e importación de un fichero CSV

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#190]
Por "aclamación particular" (muy particular) crearemos la siguiente tarea que permitirá elegir un fichero CSV del disco duro y subir su contenido a determinada tabla.

Para su correcta implementación, deberán tener en cuenta el trabajo realizado en las tareas #84 y #10

**Comment by profeIAP** [comment]
Agradecería que, al implementar esta nueva funcionalidad, fusionases (en frío) las entradas del menú
- Alumnos > Subir
- Alumnos > Importar

en una sola (llamémosla Alumnos > Importar por coherencia con el resto de la web)

**Comment by FranGarciaCo** [comment]
No se si lo que ahora le propongo es una locura, pero, ¿y si incluimos un "menú" para seleccionar la tabla a la que deseamos importar?. Eso involucra muchas tareas, creo que la de César es una de ellas, pero ademas, ¿hay alguna forma ver ,desde la web, cómo son las tablas a las que vamos importar?. Esto si que sería un gran final, respecto a mis tareas, para el proyecto no crees.

**Comment by profeIAP** [comment]
Es el otro posible enfoque: actualmente tenemos una entrada en el menú por entidad (Partes, Alumnos, Usuarios, ...) y en ellas iremos colocando las distintas opciones Importar que mencionas.

No entiendo la propuesta final (ver la estructura de las tablas desde la web) pero no suena del todo bien (no me gustaría dar información a posibles atacantes respecto a la estructura de nuestro modelo de datos ;) )

Si lo hacemos bien (y esa es la intención) no requerirá tanto trabajo como estimas ya que la función de importación que implementaste es "agnóstica" de la estructura y serán los ficheros CSV los que deban saber el orden y el número de campos que deben incluir.

Como mejora (recuerda las premisas que establecí el primer día: "menos es más" y "sólo implementaremos lo que vayamos necesitando") y, sólo si fuese necesario, se incluirían comprobaciones sobre los ficheros a importar en base a evitar posibles funcionamientos anómalos (o que directamente no funcionen)

**Comment by FranGarciaCo** [comment]
El ver las tablas tiene la finalidad de que el usuario que desee subir algunos datos sepa conforme a que ha de subirlo, claro que es es una función de admin, puesto que el que rellena los datos lo hace desde los formularios. Básicamente es para el que desee editar los datos y así lo haga cómodamente desde los "CSV". Es cierto lo que dices de que la función "import..." no mira los datos, si no que lo deja a cargo del fichero, se mejor decidir, si es útil o si se requiere, empíricamente no?

**Comment by profeIAP** [comment]
Con la funcionalidad actual siempre se puede exportar la tabla (para
conocer la estructura de la tabla) y luego importar.

**Comment by FranGarciaCo** [comment]
Subido el código y finalizada por tanto la tarea.

**Comment by profeIAP** [comment]
Si te subo un fichero _nombremalevolo.csv_ ¿¡¿estaríamos importando los datos en la **tabla alumnos**?!? ;P

**Comment by FranGarciaCo** [comment]
Me has encontrado el punto débil... Daremos por finalizada la tarea cuando incluya las verificaciones con Mime y el incluir a una tabla determinada entonces, ¿no?

**Comment by FranGarciaCo** [comment]
Finalizada

**Comment by profeIAP** [comment]
Todo "superhéroe" tiene su "criptonita" Fran.

Me conformo con la correcta gestión de las tablas aunque intuyo que, por filosofía de vida, no resistirás la tentación de perfeccionar la "técnica" ;)

Agradecería:
1. quitases los "andamios" utilizados (me refiero a los "echoes" que afean y afectan al comportamiento de la web) 
   ![captura de pantalla de 2016-05-12 18 16 34](https://cloud.githubusercontent.com/assets/16881846/15221927/c5d2a798-186d-11e6-8d9b-7a3434245ae9.jpg)
2. Elimines la tabla **alumnos** de la BD (la que utilizamos es **alumnO**
3. Modifiques el script para que la importación se realice sobre la tabla auténtica **alumnO**

Con todo esto que que puedes (merecidamente) darte por satisfecho y finalizar la tarea ¿o no? ;)

**Comment by FranGarciaCo** [comment]
De acuerdo, haré los requisitos que me mencionas y en vista de que alientas mi curiosidad (como yo ya hice con usted), he de admitir que me deja muy intrigado el asunto de la verificación de un archivo y el concepto de clases en programación (en parte me interesa porque cuando comencé con Haskell, el concepto de clase y definición de tipos están por doquier). Así que, cumplidos los requisitos, como recreo personal me dedicaré a ese asunto de verificar la extensión de un fichero. Por cierto he encontrado referencias a ['fileinfo'](http://php.net/manual/es/book.fileinfo.php) , no se si es una forma de abordar el asunto.

**Comment by profeIAP** [comment]
Motivar y ser motivado interesante y satisfactoria mezcla.
Fileinfo es otra forma de abordar el problema planteado.

Respecto a la orientación a objetos (OOP) ya me encantaría poder sacar tiempo para darte una base sólida al respecto :(

**Comment by FranGarciaCo** [comment]
Lo último que me puntualizaste ya esta resuelto, cerraré la tarea y a ver si llega a algo lo de fileinfo no? Jajaja

**Comment by profeIAP** [comment]
Ha quedado perfecto @FranPeroNoMoreno, ¡Enhorabuena!

Me encantaría poder echar un vistazo al "magic mime" este fin de semana pero llevo una desviación demasiado significativa en mi planificación y no sé si lograré sacar el tiempo que requiere (dicen que querer es poder pero, degraciadamente no es una condición necesaria y suficiente ;) )
