### ISSUE TITLE
Documentar "insert into" en SQLite

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#191]
Crear [documento compartido](https://docs.google.com/document/d/1vsfp2vsPzJzy1TZGVUlECMQf0NxgYru159wIRq0EjoI/edit?usp=sharing) explicando cómo usar la sentencia SQL "insert into" para volcar en una tabla determinados campos de otra tabla y/o consulta.

Nos será de utilidad cuando comencemos a implementar métodos de importación que, a partir de una macro tabla (con decenas de campos) rellenemos otras más pequeñas pero cuyo contenido se obtendrá de la tabla importada.

**Comment by profeIAP** [comment]
Está francamente bien: tanto que no parece ni tuyo :package: 
Corrige los detallitos que te comento (en el propio documento) y damos por finalizada la tarea.

**Comment by profeIAP** [comment]
Dejo comentarios

**Comment by Isa70199** [comment]
¿Puedo cerrar ya esta tarea? @profeIAP

**Comment by profeIAP** [comment]
Siempre puedes cerrar Isabel... ya me encargo yo de volver a abrirla si considero que puede ser mejorada ;)

**Comment by profeIAP** [comment]
No obstante, he añadido comentarios

**Comment by profeIAP** [comment]
Y los últimos detalles para poder dar por finalizado el trabajo.

**Comment by profeIAP** [comment]
Genial @Isa70199, por fin podemos dar por cerrada la tarea. 
¡Enhorabuena!
