### ISSUE TITLE
Crear entrada menú Anotaciones > Crear

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#192]
Crear nueva entrada en el menú que permita la creación de nuevas anotaciones.

Deberá figurar entre Alumnos y Notificaciones

![captura de pantalla de 2016-05-05 19 10 55](https://cloud.githubusercontent.com/assets/16881846/15050646/468c26da-12f5-11e6-83c2-3a5fd8070a2b.jpg)

No debe hacer absolutamente nada, sólo aparecer en el menú con la ruta de acción /alumnos/anotaciones/crear

**Comment by carlosaj98** [comment]
Ya he solucionado el problema

**Comment by profeIAP** [comment]
Pero has introducido otro XD

Como se indica, la ruta de la acción debe ser /alumnos/**anotaciones**/crear (en plural)

Es un cambio nimio, esperamos a que lo implementes para dar por buena la tarea

**Comment by carlosaj98** [comment]
Ya lo he puesto bien

**Comment by profeIAP** [comment]
Perfecto, gracias Carlos
