### ISSUE TITLE
Añadir acción "Crear Anotación"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#193]
Añadir a **index.php** un nuevo método GET que responda a la ruta **/alumnos/anotaciones/crear** renderizando la vista **/view/anotacion.php**

No debes crear la vista anotacion.php, sólo incluir el método GET en index.php [tal y como hace, por poner un ejemplo, /alumnos/crear](https://github.com/profeIAP/panelDeControl/blob/77affb9a1d9e3789383afca6f825a5fb236a9aa2/index.php#L135)

Básicamente usarás dicho código cambiando la vista que hay que mostrar.

**Comment by ghost** [comment]
Ya está terminada :)

**Comment by profeIAP** [comment]
Perfecto, un trabajo limpio y a la primera.
