### ISSUE TITLE
Documentar cómo instalar SQLiteman en Windows

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#196]
Añadir a [la documentación base del proyecto](https://docs.google.com/document/d/1-uDZdebGRuAp2iNBLcgsNaav6VfR3dg3KJwp8HW5P7I/edit#bookmark=id.bin49dt896a) un apartado indicando cómo instalar el gestor de bases de datos que utilizamos en clase.

En principio se etiqueta como **normal** pues se entiende que bastará con indicar dónde puede descargarse; si se necesitase instalar _sqlite_ avísame para subir el nivel de dificultad de la tarea o crear otra nueva donde se explique la instalación de _sqlite_

**Comment by carlosaj98** [comment]
Ya he terminado la tarea

**Comment by profeIAP** [comment]
Comento sobre el propio documento

**Comment by carlosaj98** [comment]
ya esta corregio

**Comment by profeIAP** [comment]
Te dejo comentarios en el documento

**Comment by carlosaj98** [comment]
ya lo he hecho

**Comment by profeIAP** [comment]
Casi

**Comment by carlosaj98** [comment]
Ya

**Comment by profeIAP** [comment]
La daremos por cerrada (para que puedas avanzar con otras tareas) pero deberías haber recortado un poco más las imágenes pues muestran demasiado ventana y no se aprecian los detalles.

Confío (y agradezco) que, si encuentras hueco, las mejores.
