### ISSUE TITLE
Documentar cómo instalar Geany en Windows

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#198]
Añadir a [la documentación base del proyecto](https://docs.google.com/document/d/1-uDZdebGRuAp2iNBLcgsNaav6VfR3dg3KJwp8HW5P7I/edit#bookmark=id.bin49dt896a) un apartado indicando cómo instalar el gestor de bases de datos que utilizamos en clase.

En principio se etiqueta como **normal** pues se entiende que bastará con indicar dónde puede descargarse; si se necesitase instalar _GTK+_ (o similar) avísame para subir el nivel de dificultad de la tarea o crear otra nueva donde se explique la instalación de _GTK+_

**Comment by ghost** [comment]
Acabo de terminar la tarea, espero que esté bien. A menos que se utilice un instalador completo con _GTK+_, es necesario instalarlo. Crearía otra tarea para eso.

**Comment by profeIAP** [comment]
Bastante bien salvo un par de detalles nimios que comento sobre el propio documento.

**Comment by ghost** [comment]
Acabo de corregir los fallos.

**Comment by profeIAP** [comment]
Y acabo de afinar los comentarios...

**Comment by ghost** [comment]
Ya he puesto una distinción del fichero que hay que descargar en la imagen de la página de Geany. Creo que ya está todo bien

**Comment by profeIAP** [comment]
Sí señor, ha quedado perfecto.
Gracias Francisco
