### ISSUE TITLE
Ordenar alfabéticamente entradas de la documentación

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#199]
Ordenar alfabéticamente [los apartados de las distintas herramientas que usamos](https://docs.google.com/document/d/1-uDZdebGRuAp2iNBLcgsNaav6VfR3dg3KJwp8HW5P7I/edit#bookmark=id.t7sfpss5tj9z) para desarrollar en clase (GIT, Geany, PHP, ...)

**Comment by semacg98** [comment]
Ya esta ordenado correctamente ;) .

**Comment by profeIAP** [comment]
Perfecto, gracias
