### ISSUE TITLE
Tabla partes

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#2]
Crear tabla para almacenar los partes que se emitan

**Comment by semacg98** [comment]
falta mucho?

**Comment by profeIAP** [comment]
La tabla tiene una gran cantidad de campos, dale un poco de tiempo a @j1m1

**Comment by j1m1** [comment]
ya está subida

**Comment by profeIAP** [comment]
Fantástico Jesús, ha quedado muy bien.
¡Gracias!
