### ISSUE TITLE
Alinear imagen de la sirena en README.MD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#200]
Encontrar la forma (no digo que sea sencillo, de ahí que sea etiquetada como "reto" y no se lo haya exigido a @linanalandalus cuando implementó la tarea #151) de maquetar la imagen de la sirena de modo que el texto de recomendación esté alineado verticalmente con la sirena.

![captura de pantalla de 2016-05-06 17 56 03](https://cloud.githubusercontent.com/assets/16881846/15078634/63ab6a04-13b4-11e6-8609-93d671364878.png)

Por si sirve de referencia, el concepto en HTML (+CSS) sería añadir el atributo _style="float:left"_ en la imagen pero aquí tenemos que **usar Markdown** (hay gente que recomienda usar tablas pero no deben tener bordes para que no cante demasidado)

**Comment by SyalChain** [comment]
@profeIAP Esto es lo máximo que consigo con las tablas.

![captura de pantalla de 2016-05-25 10 04 12](https://cloud.githubusercontent.com/assets/15797249/15532509/74f9abb2-2260-11e6-9fdc-c51d0794c727.png)
![captura de pantalla de 2016-05-25 10 06 32](https://cloud.githubusercontent.com/assets/15797249/15532511/767d8396-2260-11e6-8699-c3490af34eb6.png)

**Comment by profeIAP** [comment]
Salvo por los encabezados de la tabla me parece estupendo.

Edita el README.MD y nos quitamos esta tarea de encima ¿te parece? ;)

**Comment by profeIAP** [comment]
Ha quedado estupendo Emilio... mil gracias
