### ISSUE TITLE
Crear "Buzón de sugerencias"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#201]
Compartir [hoja de cálculo](https://docs.google.com/spreadsheets/d/1GWBdArQ-0j-Db2zIGtvORs9uhucbrG9X1V1fWlzMtlo/edit?usp=sharing) en la que podamos ir registrando las ideas que nos gustaría ver incluidas en nuestro proyecto.

Debe incluir (entre otros campos):
- Descripción
- Quién sugiere la idea (usuario github)
- Por qué la considera interesante
- Fecha de la idea
- ...

Cuidar la estética (no se aceptará una hoja con las columnas simplemente)

**Comment by profeIAP** [comment]
Cuasi perfecto Antonio (y suficientemente "bonito")

Me ha encantado la iniciativa de añadir nuevos campos que has visto necesarios (¡bien hecho!) pero, personalmente: 
1. dejaría más espacio en aquellos campos en los que se debe escribir más (Descripción, ¿Por qué interesa?, ...)
2. tengo una duda: ¿Qué diferencia existe entre IDEA y NOMBRE DE LA IDEA?

**Comment by antoniio92** [comment]
LISTO!

**Comment by profeIAP** [comment]
Sigo echando de menos espacio para poder escribir en apartados como Descripción y "¿Por qué interesa?" (sin que sirva de precedente, mejor a lo ancho que a lo alto)

**Comment by antoniio92** [comment]
BIEN!?

**Comment by profeIAP** [comment]
Más que bien... buen trabajo Antonio
