### ISSUE TITLE
Documentar cómo crear triggers en SQLite

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#204]
Compartir documento con el profesor explicando [cómo se crean triggers en SQLite](https://goo.gl/BKTLGA) (y una pequeña referencia a su utilidad).

No es tan importante explicar su manejo en SQLiteman como la sintaxis.

**Comment by profeIAP** [comment]
Desgraciadamente, el documento compartido:
1. No usa la plantilla que tenemos para la documentación.
2. No deja de ser una traducción de un documento de Internet.

**Comment by profeIAP** [comment]
El documento no ha sido modificado ni se han tenido en cuenta las mejoras comentadas

**Comment by Mahc99** [comment]
[Ya te he compartido el documento de la tarea](https://docs.google.com/document/d/1_zCFyyGwNnZ4p1FE2wMtYPCW8wCM--Aap8lq3ob7Brw/edit#heading=h.g392zqc0dnc)

**Comment by profeIAP** [comment]
Miguel Ángel, el documento te está quedando realmente espectacular (uno de los mejores de la "biblioteca" que nos estamos montando), pero, ya sabes que soy exigente por lo que te va a tocar "pulir" el resultado final.

**Comment by profeIAP** [comment]
Me voy a convertir en tu peor pesadilla :P

Naaa... te va a quedar un gran documento, tiene una pinta estupenda

**Comment by Mahc99** [comment]
¡Bueno mientras sea por aprender! ¡Corrigo y espero nuevas ordenes!

**Comment by profeIAP** [comment]
Aunque mejorable, podríamos dar por bueno el documento ¿te parece? ;)
Te he incluido algunas correcciones (que no comentarios) que igual te interesa leer
