### ISSUE TITLE
Asignar valor por defecto ACCION.ID_USUARIO

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#206]
Modificar la tabla (y actualizar el script model/scripts/accion.sql) para que asigne (por defecto) al valor 1 al campo ID_USUARIO

**Comment by dnrg98** [comment]
Creo que he hecho lo que pedía. En el caso que no sea me la vuelves a abrir ;)

**Comment by profeIAP** [comment]
Desgraciadamente no sólo no se asigna el valor uno al campo ID_USUARIO sino que además el campo ID ha dejado de ser autonumérico.

Recuerda que debes modificar tanto **dictados.db** como **scripts/table_accion.sql**

**Comment by profeIAP** [comment]
Perfecto María, a por otra tarea: vamos, vamos...
