### ISSUE TITLE
Cambiar rutas para borrar/editar usuarios

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#207]
Tras la reestructuración del código se debe cambiar las rutas utilizadas para borrar y editar alumnos en la vista **view/comentarios.php**

![captura de pantalla de 2016-05-09 17 31 14](https://cloud.githubusercontent.com/assets/16881846/15118350/219eb832-160c-11e6-9950-782c9a37f134.jpg)

Los "botones" deben utilizar
- **Borrado** /usuarios/borrar
- **Edición** /usuarios/editar

**NOTA:** dejar el parámetro ID tal cual está, sólo debe anteponerse el **/usuarios/** por delante de la acción

**Comment by profeIAP** [comment]
Tras implementar la tarea #144 ya no existe **view/comentarios.php** (ahora se llama **view/usuario.php**)

**Comment by Patriexd** [comment]
la reabro que no puedo subir los cambios

**Comment by profeIAP** [comment]
Espectacular la evolución estos días, ¡enhorabuena!
