### ISSUE TITLE
Anotar la última acción realizada en la BD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#208]
Editar [el método Utilidades.anotarAccion()](https://github.com/profeIAP/panelDeControl/blob/master/controller/Utils.php#L66) para que inserte en la tabla ACCIÓN de la base de datos la ruta que acaba de utilizar el usuario.

Consideraciones:
1. Sólo debe insertar (de momento) la ruta, el resto de campos ya se añadirán cuando sea posible.
2. La ruta se obtiene de _$req->getPathInfo()_
3. Para probar que funciona no tienes mas que
   - utilizar la opción Notificaciones > Listar
   - Mirar que se va llenando la tabla ACCIÓN

**Comment by angelagr** [comment]
modifica para que tenga acceso a la base de datos

**Comment by profeIAP** [comment]
Modificado...

**Comment by angelagr** [comment]
ya está subida

**Comment by profeIAP** [comment]
Perfecto Ángela, te ha quedado realmente bien.
¡Enhorabuena!
