### ISSUE TITLE
Borrar parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#21]
Eliminar entrada de la bd

**Comment by mariamiura16** [comment]
Requiere esté implementada la tarea #2

**Comment by profeIAP** [comment]
Te será de utilidad el siguiente [fragmento de código](https://github.com/profeIAP/proyecto2015-16/blob/f816d3e6043221e3438bb94d4fd21588c3cec3ab/index.php#L105-L118)

**Comment by profeIAP** [comment]
Para probar te bastará utilizar la siguiente url en tu navegador

> localhost:9000/partes/borrar?id=NNNN

Cambiando NNNN por el número de la entrada a borrar.

**Comment by profeIAP** [comment]
Sí señora... ¡enhorabuena!

Me ha encantado ver que has conseguido implementar (a pesar de las "fatiguitas") tu primera tarea de programación.

Grande Rocío, grande... ¡A por la siguiente!
