### ISSUE TITLE
Cambiar de sitio el icono del menú

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#213]
Cambiar a la derecha el icono de la maleta que acompaña al apartado MENÚ en el panel lateral

![icono-menu](https://cloud.githubusercontent.com/assets/16881846/15151083/0de69e58-16d0-11e6-8a27-471ba642db41.jpg)

**Comment by MartaCorzo** [comment]
mandame el menú nuevo

**Comment by MartaCorzo** [comment]
Camnia esta tarea a reto que llevo perdida una semana y pico

**Comment by profeIAP** [comment]
Bajo ese razonamiento, ¿debo cambiar (por poner un ejemplo que le tengo "cariño" y tó) a retos las tareas de @josemita6?

**Comment by MartaCorzo** [comment]
Como quieras y lo veas oportuno pero llevo un tiempo trabajando en esta tarea y no sé lo que cada uno trabaja en la suya por ese motivo no puedo opinar en la de los demás @profeIAP

**Comment by profeIAP** [comment]
No sabes pero lo intuyes XD
Sabia respuesta Marta

**Comment by MartaCorzo** [comment]
jajajajajaj exacto, y gracias así que ya sabes (Normal--->Reto) ;) @profeIAP

**Comment by MartaCorzo** [comment]
volver a poner bien el menu

**Comment by profeIAP** [comment]
Paso la tarea a reto tras comprobar que con los continuos cambios introducidos por tus compañeros en layout.php (que afectan al menú y su correcto funcionamiento) se te está haciendo especialmente dificultoso terminarlo y has perdido un precioso tiempo.

Sospecho que no me tendrás a mal este cambio :)

**Comment by profeIAP** [comment]
Ya tienes, nuevamente, el [menú listo](https://github.com/profeIAP/panelDeControl/commit/5f57cea05268708e4bc7338f64047339fe80a30d) para ser "mejorado"
