### ISSUE TITLE
Cambiar colores del menú

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#214]
Aunque bonitos, se deben cambiar los tonos "morados" y "violetas" (para los colores soy algo daltónico) del menú por unos **tonos de azul** acordes a nuestros colores "corporativos"
![colores-menu](https://cloud.githubusercontent.com/assets/16881846/15151205/813f3e14-16d0-11e6-8dad-decc5df16a45.jpg)

**Comment by Rafaelcraftero** [comment]
terminada

**Comment by profeIAP** [comment]
Cambiado está pero ha pasado a unos tonos "morado-azulados" que hacen daño XD

Juega con los tonos de azul de nuestro logo

![logo](https://cloud.githubusercontent.com/assets/16881846/15542375/cbe140a4-2290-11e6-963a-cdb4e3b017a3.png)

**Comment by profeIAP** [comment]
D. Rafael
1. No veo commit a su nombre ni que haga referencia a la tarea
2. Los colores siguen siendo los "morados"

¿Ha hecho realmente un push al repositorio?

**Comment by Rafaelcraftero** [comment]
terminada

**Comment by profeIAP** [comment]
Espectacular D. Rafael, ha quedado realmente bien (gracias)
