### ISSUE TITLE
Cambiar anchura del menú

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#215]
Cambiar la anchura del menú para que ocupe la mayor superficie posible 

![anchura-menu](https://cloud.githubusercontent.com/assets/16881846/15151654/5dce5a80-16d2-11e6-8f77-be13faa4b47b.gif)

**Comment by Rafaelcraftero** [comment]
Terminado ahora el menú es más grande

**Comment by profeIAP** [comment]
Difiero D. Rafael: lo veo igual y no encuentro el commit por ningún lugar ¿Ha subido los cambios al repositorio?

**Comment by profeIAP** [comment]
En el listado de commits no aparece referencia a:
1. La tarea que supuestamente ha finalizado
2. Su usuario

Por lo que entenderé que no se ha subido dicho cambio y no procedo a corregirlo (hoy tengo excesiva prisa como para ponerme a buscar)

Recomiendo elegir entre:
1. Hacer un nuevo commit indicando tarea+usuario
2. Modificar su comentario anterior enlazando al commit para que pueda observar los cambios

Pido disculpas por las prisas

**Comment by Rafaelcraftero** [comment]
Subida y terminada

**Comment by profeIAP** [comment]
Es verdad que ahora está más grande D.Rafael pero ha excedido el número de columnas máximo que admite nuestra "rejilla" ([ha puesto 14](https://github.com/profeIAP/panelDeControl/commit/348b9c700f8a32e915938eab5b93f2ad784386cc) cuando la suma de todos los elementos de una misma "fila" no deben exceder las 12 unidades)

**Comment by Rafaelcraftero** [comment]
mira ahora a ver

**Comment by profeIAP** [comment]
Está perfectísimo, gracias D.Rafael.
¡Gran trabajo!
