### ISSUE TITLE
Incluir acceso al buzón de sugerencias en README.MD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#216]
Añadir [enlace al buzón de sugerencias](https://docs.google.com/spreadsheets/d/1GWBdArQ-0j-Db2zIGtvORs9uhucbrG9X1V1fWlzMtlo/edit?usp=sharing) creado por @antoniio92 en el fichero README.MD

La entrada debe incluir:
1. un icono "alusivo" (un buzón o similar)
2. un texto que invite a la participación (que no sea excesivamente largo, sólo exhortar a la acción)

**Comment by Patriexd** [comment]
¿ Qué tengo que hacer en esta tarea ? @profeIAP

**Comment by profeIAP** [comment]
Lo que se indica en la descripción, algo similar a lo hecho por @linanalandalus en su tarea #151

**Comment by profeIAP** [comment]
Pefecto Patri, buen trabajo

**Comment by profeIAP** [comment]
Subo el nivel de dificultad a normal por similitud con otras tareas.
