### ISSUE TITLE
Cambiar estética documento "Uso de la sentencia 'INSERT INTO'"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#218]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #191

**Comment by profeIAP** [comment]
@Mahc99, ya ha terminado su tarea @Isa70199 
Puedes abordarla cuando buenamente puedas ;)

**Comment by Mahc99** [comment]
¡Necesito permisos para realizar la tarea!

**Comment by profeIAP** [comment]
Ya [tenías permiso](https://docs.google.com/document/d/1vsfp2vsPzJzy1TZGVUlECMQf0NxgYru159wIRq0EjoI/edit?usp=sharing) ¿?

**Comment by Mahc99** [comment]
Terminada.

**Comment by profeIAP** [comment]
Te lo he dejado bien "comentadito" ;P

**Comment by profeIAP** [comment]
Cuasi perfecto... parece que los márgenes siguen "alocados" :)

**Comment by Mahc99** [comment]
Creo que ya los he arreglado ~

**Comment by profeIAP** [comment]
Francamente mejorable tu gusto estético pero sí, lo has arreglado.
¡Enhorabuena Miguel Ángel!
