### ISSUE TITLE
Cambiar estética documento "Exportar e importar - CSV & SQLite"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#219]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by juliacc98** [comment]
[Documento](https://docs.google.com/document/d/1_2iVrT2UXc0eRS3sHsPkw45I4s95ichYmkQi048n_90/edit?ts=5735c133) compartido

**Comment by profeIAP** [comment]
Perfecto Julia, buen trabajo
