### ISSUE TITLE
Editar alumno

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#22]
Modificar entrada de la bd

**Comment by MartaCorzo** [comment]
Código subido al repositorio y listo para editar los datos del alumno.

**Comment by profeIAP** [comment]
No veo el commit en el repositorio, ¿te has acordado de hacer el [_push_ al servidor](https://github.com/profeIAP/proyecto2015-16/wiki#subida)?

**Comment by profeIAP** [comment]
Está perfecto salvo que la tabla usuario tiene más campos de los que actualizas con tu método.

Añade las columnas que faltan y damos por finalizada la tarea.

![captura de pantalla de 2016-04-15 17 03 05](https://cloud.githubusercontent.com/assets/16881846/14565607/332ce33c-032c-11e6-9f1d-06965922a011.png)

**Comment by profeIAP** [comment]
Por cierto, recuerda poner el número de tarea cuando hagas el commit (git commit -m "Implementada **tarea #22"**)

De este modo aparecerá una referencia en la lista de cambios de tus tareas y se facilita el acceso al código ;)

**Comment by profeIAP** [comment]
Retiro que seas una máquina con gitHub: ya es [la segunda vez que tengo que contarte lo mismo](https://github.com/profeIAP/proyecto2015-16/issues/135#issuecomment-212483764).

Si quieres destacar,
te lo tienes que currar.

Y me dejo de rimar

**Comment by profeIAP** [comment]
Sigue sin incluir todos los campos de la BD

**Comment by profeIAP** [comment]
Bien está lo que "bien" acaba :)
Buen trabajo, Marta
