### ISSUE TITLE
Cambiar estética documento "Crear tablas en sqliteman"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#220]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #97

**Comment by alemorales1999** [comment]
me la voy a quitar que si no voy a tener desfase

**Comment by profeIAP** [comment]
Ok, céntrate en las tareas de programación entonces.
Ánimo Alejandro, que es más sencillo de lo que en un principio parece ;)

**Comment by profeIAP** [comment]
Aunque lo habrás compartido conmigo, necesito incluyas el enlaces en los comentarios de la tarea.

**Comment by Patriexd** [comment]
El [documento](https://docs.google.com/document/d/1l7PTjkjGZc3nwjRnbMnjWL9JZPkcHbCDd2RNI7YWctg/edit#heading=h.c66ldd5im71z)

**Comment by profeIAP** [comment]
Patri, procura ocultar los enlaces en el texto de tus comentarios.
No obstante el enlace enviado dice no existir ¿?

**Comment by Patriexd** [comment]
[enlace](https://docs.google.com/document/d/1l7PTjkjGZc3nwjRnbMnjWL9JZPkcHbCDd2RNI7YWctg/edit#heading=h.h5f1n1n3nqz4)

**Comment by profeIAP** [comment]
Incluyo comentarios

**Comment by Patriexd** [comment]
yap

**Comment by profeIAP** [comment]
Le queda algo todavía para estar finalizado

**Comment by Patriexd** [comment]
[Está corregido](https://docs.google.com/document/d/1l7PTjkjGZc3nwjRnbMnjWL9JZPkcHbCDd2RNI7YWctg/edit#heading=h.c66ldd5im71z)

**Comment by profeIAP** [comment]
Comentado... algunas cosas han "bailado"

**Comment by Patriexd** [comment]
[a ver que tal ahora](https://docs.google.com/document/d/1l7PTjkjGZc3nwjRnbMnjWL9JZPkcHbCDd2RNI7YWctg/edit#heading=h.c66ldd5im71z)

**Comment by profeIAP** [comment]
Bastante mejor... pero necesita ser "afinado"

**Comment by Patriexd** [comment]
[ESTO ESTÁ YA](https://docs.google.com/document/d/1lDIcDnOWUugKzajEs1lRzupFVExtHkb3HrgSL9P9XDA/edit#)

**Comment by profeIAP** [comment]
Sí que está ya... ya está para revisar XD

**Comment by Patriexd** [comment]
a ver que tal ahora

**Comment by profeIAP** [comment]
Curiosamente, como muchos de tus compañeros, fallas en el uso de los encabezados... te [recomendaría mirar el documento](https://docs.google.com/document/d/1LPQWt2d5souc6ria3OrDtXyAlduAnX3R820ifnkYa4I/edit?usp=sharing) generado por @jpc99

**Comment by Patriexd** [comment]
[now? ;(((](https://docs.google.com/document/d/1lDIcDnOWUugKzajEs1lRzupFVExtHkb3HrgSL9P9XDA/edit)

**Comment by profeIAP** [comment]
Te dejo alguna sugerencia pero está muy bien ;)
