### ISSUE TITLE
Cambiar estética documento "Creando una vista SQLite"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#221]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #46

**Comment by jairoML** [comment]
Ya está [realizada](https://docs.google.com/document/d/15zs1X1B9oxRHNS3VqiGujETDuHr6Agf5d9B5yAozbi0/edit?usp=sharing)

**Comment by jairoML** [comment]
y compartida

**Comment by profeIAP** [comment]
Y comentada

**Comment by jairoML** [comment]
ya

**Comment by profeIAP** [comment]
Siguen quedando cosas...

**Comment by profeIAP** [comment]
¿Has usado la plantilla original? Comento sobre el documento

**Comment by profeIAP** [comment]
Definitivamente no creo que hayas usado la plantilla original...comento sobre el documento

**Comment by profeIAP** [comment]
A falta de comprobar que has comprendido el uso de los estilos en el documento, prácticamente terminado

**Comment by profeIAP** [comment]
Confirmaod Jairo: has aprendido a usar correctamente los estilos ;)
