### ISSUE TITLE
Cambiar estética documento "Uso de PHPUnit"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#224]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #32

**Comment by alemorales1999** [comment]
voy a coger otra porque requiere que la tarea #32 este cerrada y no está aún

**Comment by profeIAP** [comment]
Buena elección, Alejandro

**Comment by profeIAP** [comment]
@marialuisapf, entiendo que tienes prisa pero, a día de hoy, la tarea #32 no está cerrada :O

Con un poco de suerte, a @JVG13 no le importará [utilizar tu nueva versión](https://docs.google.com/document/d/1D9U1INpzX-T4S9xqx2GsMwXzkSmEAmOJwefhwgFsdtY/edit?usp=sharing) (agradezco confirmación)

Mientras tanto, no puedo aceptar como cerrada esta tarea al no cumplir el requisito inicial (motivo por el cual @alemorales1999 optó por abandonarla)

**Comment by marialuisapf** [comment]
Sorry, la había visto cerrada anteriormente y no ne había dado cuenta de que la habías reabierto

**Comment by profeIAP** [comment]
Raro que reabra una tarea de documentación ¿verdad? XD

**Comment by marialuisapf** [comment]
Raro... XD Bueno, te paso el enlace del [documento](https://docs.google.com/document/d/1D9U1INpzX-T4S9xqx2GsMwXzkSmEAmOJwefhwgFsdtY/edit) me he asegurado de que está cerrada la anterior

**Comment by profeIAP** [comment]
Está perfecto, gran trabajo Mª Luisa
