### ISSUE TITLE
Cambiar estética documento "Servidor PHP"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#225]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by Cesarj9** [comment]
[Hecha](https://docs.google.com/a/iesalandalus.com/document/d/1PRNOKOUI6jrGdE59teeujpevFCpb5mLf4GoEo5vcOGo/edit?usp=sharing)

**Comment by profeIAP** [comment]
"Estropeada"...

**Comment by Cesarj9** [comment]
¿Perdone? Esta perfectamente hecha... tal y como se pedia, ha sido
adaptada, otra cosa es que el documento inicial fuese una "porqueria" pero
eso no entra dentro de mi tarea, sino de otra de la cual no tengo que
hacerme cargo, desde mi mas umilde opinion...

**Comment by profeIAP** [comment]
Te queda "menos"

**Comment by profeIAP** [comment]
Yo sigo viendo que el formato no es el de la plantilla que tenemos (el documento es feo "per se" pero que sea pseudo parecido a los demás queda feo de verdad)

Básicamente el encabezado no se parece al nuestro y el texto se mete en ocasiones dentro dando muy mala "imagen"

**Comment by Cesarj9** [comment]
Pero si he hecho lo que dijistes... y he hecho una copia del original... si
se ve feo sera porque no le pega ese modelo, no por que lo haya alterado.

**Comment by Cesarj9** [comment]
[Link a la copia ](https://docs.google.com/document/d/1GlND23b3caNHesv0FdWZ00MwFfi-B4Oo1ZWfLC6BcSM/edit#heading=h.3060w3s4z00b)

**Comment by profeIAP** [comment]
Te voy a abrir la tarea sólo por no haber "ocultado" (y eso que deberías tener experiencia por la tarea #245) el enlace anterior ¡Sacrílego!

**Comment by profeIAP** [comment]
Mucho mejor, dónde va a parar.
Gracias César
