### ISSUE TITLE
Cambiar estética documento "Incluir dependencias en el proyecto"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#226]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #89

**Comment by semacg98** [comment]
Aquí la [dejo](https://docs.google.com/document/d/1wYUSw307FGIwW0tiWmTR5h__OQwucZhwMPRy3YVdo0c/edit#). Cierro tarea.

**Comment by profeIAP** [comment]
Y yo la abro...

**Comment by semacg98** [comment]
Ya corregido.

**Comment by profeIAP** [comment]
Te dejo pequeñas correcciones, ánimo.

**Comment by semacg98** [comment]
No me sale que me hayas dejado ningún comentario con alguna sugerencia para corregir. @profeIAP

**Comment by semacg98** [comment]
He corregido algunas faltas que tenía, no se si ese era el error, cierro tarea aún asi.

**Comment by profeIAP** [comment]
Has "olvidado" algunos de los cambios propuestos

**Comment by semacg98** [comment]
Lo [he vuelto a hacer de nuevo](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#) porque me he liado un poco... espero que no me lo tengas en cuenta :P
Espero que ahora esté correctamente...

**Comment by profeIAP** [comment]
Al final conseguirás que me líe también yo (amén de hacerme corregir dos documentos innecesariamente)

Vuelvo a comentar sobre el nuevo documento

**Comment by profeIAP** [comment]
Sólo te queda "lidiar" con la estructura del documento

**Comment by semacg98** [comment]
Lo he vuelto a cambiar, por favor dime que está bien ya...  T.T

**Comment by profeIAP** [comment]
Yo te lo diría pero el documento sigue prácticamente igual :(

**Comment by jpc99** [comment]
¿Que tengo que hacer en esta tarea? @profeIAP

**Comment by profeIAP** [comment]
Creo que te lo he comentado en clase, no obstante, lo repetiré: coge el documento actualmente existente y pásalo a la plantilla que tenemos definida para la documentación (el que incluye el logotipo y los colores "corporativos")

Ambos documentos están referenciados en la descripción de esta tarea.

**Comment by jpc99** [comment]
[cierro tarea](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#heading=h.kutji7iyuc35) @profeIAP

**Comment by profeIAP** [comment]
Incluyo un par de comentarios en el documento

**Comment by jpc99** [comment]
[Cierro tarea de nuevo](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#)

**Comment by profeIAP** [comment]
Sigues liándonte con los apartados... te dejo comentario

**Comment by jpc99** [comment]
[¿Ahora si?](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#heading=h.ywuzgox89h42)

**Comment by profeIAP** [comment]
Me temo que no

**Comment by jpc99** [comment]
No se como poner el esquema de documento. ¡AYUDA! @profeIAP

**Comment by jpc99** [comment]
[espero que ya](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#heading=h.ywuzgox89h42) Por favor dime que esta bien :(((((

**Comment by jpc99** [comment]
[ahora si ](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#heading=h.5pz18rrp7ti)

**Comment by profeIAP** [comment]
Nopes

**Comment by jpc99** [comment]
Me estoy cansando de esta tareaaa [¿ya?](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#)

**Comment by profeIAP** [comment]
Pues descansa un poco, céntrate y afina la puntería :P

Ánimo que sólo queda un detalle y se hace en dos minutos (como mucho)

**Comment by jpc99** [comment]
[listo](https://docs.google.com/document/d/1hVbyywASaLmZV68PFc6D8j-GULtVsm9pt6Z2VbfLtWU/edit#)

**Comment by profeIAP** [comment]
Pero listo que está... ¡Gracias Julia! (buen trabajo)
