### ISSUE TITLE
Cambiar estética documento "Contratar Hosting"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#228]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by antoniio92** [comment]
No se si el documento esta terminado por parte del otro alumno pero yo le cambiado la estética ya :smile:

**Comment by antoniio92** [comment]
No se si [el documento esta terminado](https://docs.google.com/document/d/15H4T28lAE-S-IU3DCjjvKs9945TctU_hwDRbDIwukZc/edit) por parte del otro alumno pero yo le cambiado la estética ya :smile:

**Comment by profeIAP** [comment]
Ese documento duerme el "sueño de los justos" desde hace tiempo.
Te dejo comentarios.

**Comment by antoniio92** [comment]
ajajjaja no lo entendido pero ya te los he respondido y corregido :smiley:

**Comment by profeIAP** [comment]
Que lleva mucho tiempo terminado y "olvidado".
Comento sobre el documento.

@antoniio92 tus tareas de programación son demasiado pocas... deja que otros puedan practicar sus dotes ofimáticas cambiando la estética a documentos .

**Comment by antoniio92** [comment]
Lo sé pero es que quiero tener algo mas de nota :/ y las únicas actividades que se hacer bien son estas y por eso las hago.

**Comment by profeIAP** [comment]
Pero entonces suspenderás por no saber programar y no tener "balanceados" los resultados de ofimática, web y programación
Te hago algunos comentarios en el documento

**Comment by antoniio92** [comment]
maetro hecho dos programaciones 
La actividad 171 y la 42

**Comment by antoniio92** [comment]
maetro hecho dos programaciones 
La actividad #171 y la #42
Pues te vuelvo a preguntar porque no se que es lo que me pides :astonished:

**Comment by profeIAP** [comment]
Imagino te habrán llegado los comentarios al correo electrónico
