### ISSUE TITLE
Editar parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#23]
Modificar entrada de la bd

**Comment by profeIAP** [comment]
El objetivo sería únicamente implementar un [método similar al '/guardarSugerencia'](https://github.com/profeIAP/proyecto2015-16/blob/ad569a45d2ba196094d792b6e558c4db757b99a1/index.php#L133-L170) que tenemos en index.php pero utilizando la tabla _parte_.

Requiere contar en la BD con la tabla *parte' de la tarea #2

**Comment by profeIAP** [comment]
Cambio el nivel de dificultad debido a la gran cantidad de campos que hay que gestionar y comprobar en la tabla Partes

**Comment by rociolm** [comment]
Ya está hecha.

**Comment by profeIAP** [comment]
Genial Rocío, enhorabuena por tu primer reto
¡Sigue así!
