### ISSUE TITLE
Cambiar estética documento "Uso de la función concatenate"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#230]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #112

**Comment by semacg98** [comment]
[Aquí](https://docs.google.com/document/d/10Z09UTJnhUuhDhDViEVN3a61f32BK23Op_mGFb6hlA0/edit#) lo dejo. Cierro tarea.

**Comment by profeIAP** [comment]
Perfecto
