### ISSUE TITLE
Cambiar estética documento "Piloto de datos"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#231]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #68

**Comment by linanalandalus** [comment]
acabo de terminar de cambiar la estética y lo he compartido contigo

**Comment by profeIAP** [comment]
Pero no has puesto aquí el enlace al documento compartido y te he puesto algún que otro comentario :)

**Comment by linanalandalus** [comment]
Aqui esta en enlace d[el nuevo documento](https://docs.google.com/document/d/1VT2Sw8TIX0sPpTLlMUObYtc7IJUrl7IeXO_2cA4Ee74/edit?usp=sharing) y ya he solucionado los problemas

**Comment by profeIAP** [comment]
He de reconocer que cambiar, has cambiado la estética del documento (no se parece en nada al formato establecido en la plantilla base XD )

El enlace compartido parece pertenecer a una publicación web: pide ayuda a los compañeros si no sabes obtener el enlace para compartir (dudo que lo necesites, supongo que será un despiste)

Quedo a la espera de los cambios para seguir corrigiendo.

**Comment by linanalandalus** [comment]
ahora si que te lo comparto bien que me equivoque en la manera de compartirlo por git hub

Aqui [el enlace ya bien](https://docs.google.com/document/d/1VT2Sw8TIX0sPpTLlMUObYtc7IJUrl7IeXO_2cA4Ee74/edit?usp=sharing).

**Comment by profeIAP** [comment]
Ahora sí, perfecto Li Nan, buen trabajo.

Procura, a partir de ahora, "ocultar" los enlaces en el texto de tu comentario (es el estándar corporativo pues queda feo ver las "urls sueltas")
