### ISSUE TITLE
Cambiar estética documento "Función Randbetween"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#232]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #94

**Comment by semacg98** [comment]
[Aquí](https://docs.google.com/document/d/1WY-ZVTbH6JwxDcA55HN9ILbywsUlHrhcutsBrusyzfw/edit#) lo dejo, cierro tarea.

**Comment by profeIAP** [comment]
Incluyo comentarios en el documento

**Comment by semacg98** [comment]
Listo, ya lo he corregido.

**Comment by profeIAP** [comment]
Perfecto, buen trabajo.
