### ISSUE TITLE
Cambiar estética documento "Función lookup"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#233]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #69

**Comment by jairoML** [comment]
Ya está [realizada](https://docs.google.com/document/d/16VHS9pRu36PDqXspKh6TRGzZEvTDatoxItXfQje0zYg/edit#heading=h.pffgm5rxyv2z)

**Comment by profeIAP** [comment]
Sospecho que no lo has compartido con mi usuario pues no tengo acceso.

**Comment by jairoML** [comment]
Ya esta compartido :)

**Comment by profeIAP** [comment]
Casi

**Comment by jairoML** [comment]
ya

**Comment by profeIAP** [comment]
Casi...

**Comment by profeIAP** [comment]
Está perfecto salvo que al no usar la plantilla hay pequeños detalles por corregir en el encabezado y el pie de página.

**Comment by profeIAP** [comment]
Ahora sí, gracias Jairo
