### ISSUE TITLE
Cambiar estética documento "GITHUB"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#234]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by profeIAP** [comment]
Comento sobre el propio documento.
Incluye en tu próximo comentario un enlace al documento compartido, please.

**Comment by profeIAP** [comment]
Los comentarios siguen pendientes

**Comment by marinacobano98** [comment]
He corregido los errores que me has indicado, por lo que considero la tarea como terminada

**Comment by profeIAP** [comment]
No has incluid el enlace en el comentario como te pedí luego considero que no debo volver a buscar el documento para corregir XD

**Comment by profeIAP** [comment]
Sigue pendiente que incluyas **enlace al documento compartido** dentro de alguno de tus comentarios para proceder a su corrección

**Comment by profeIAP** [comment]
Por tercera (¿y última vez? :P): el enlace sigue faltando en los comentarios de esta tarea

**Comment by profeIAP** [comment]
Incluyo comentarios sobre el documento

**Comment by julioosos** [comment]
comparte conmigo el documento de @marinacobano98 para seguir con lo que ella dejó

**Comment by profeIAP** [comment]
Sus deseos son órdenes... aquí tienes el [enlace al documento editado](https://drive.google.com/open?id=1OT9a2_AYelnIjZ195twHyiTZApiQVgRigF8XPM2ddaI)

Procedo a darte permisos de edición en el mismo.

**Comment by julioosos** [comment]
Ya

**Comment by profeIAP** [comment]
Comentado sobre el propio documento

**Comment by julioosos** [comment]
Corregidos los comentarios

**Comment by profeIAP** [comment]
Te he dejado algunas correcciones, gracias Julio

**Comment by julioosos** [comment]
ya

**Comment by profeIAP** [comment]
Sea, ha quedado aceptablemente bien, gracias Julio
