### ISSUE TITLE
Cambiar estética documento "Gestor de Tareas"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#235]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by profeIAP** [comment]
Incluyo comentarios en el documento.
Agradecería incluyeses en tu próximo comentario, enlace al documento compartido.

**Comment by juliacc98** [comment]
[Documento](https://docs.google.com/document/d/1evLYiFmfeqXdkhIpVlxVFQ2Q7BumRlZUsqpOS2dw_qc/edit) compartido

**Comment by profeIAP** [comment]
Incluyo comentarios

**Comment by profeIAP** [comment]
Fantástico Julia, muchas gracias
