### ISSUE TITLE
Cambiar estética documento "‘Push’ proyecto al repositorio de GitHub"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#237]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by marialuisapf** [comment]
acabada la tarea, el link del documento compartido te lo dejo [aquí](https://docs.google.com/document/d/1Xvw-C4EJdKVrnMS8tZWtP1iuE3_hMODKDByybL_Vj64/edit#)

**Comment by profeIAP** [comment]
Comento sobre el propio documento

**Comment by marialuisapf** [comment]
Hecho

**Comment by profeIAP** [comment]
Nopes

**Comment by marialuisapf** [comment]
YAP

**Comment by profeIAP** [comment]
Sure?

**Comment by profeIAP** [comment]
Algunos de los cambios habían sido "olvidados"

**Comment by marialuisapf** [comment]
No pillo el último comentario, sorry

**Comment by profeIAP** [comment]
Normal: falta información.

Que hay comentarios que te he incluido en el documento que has obviado

**Comment by marialuisapf** [comment]
Creo que ya están bien definidos los apartados

**Comment by profeIAP** [comment]
Me temo que no

**Comment by profeIAP** [comment]
Ahora están perfecto, gracias Mª Luisa
