### ISSUE TITLE
Cambiar estética documento "¿Cómo insertar imágenes en GitHub?"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#238]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by profeIAP** [comment]
Comentado sobre el propio [documento](https://docs.google.com/document/d/1q79Zg11MjFHqccKFI3NSy5tSK30s1lagssHn54QE1vQ/edit?usp=sharing)

**Comment by profeIAP** [comment]
Comento en el documento

**Comment by profeIAP** [comment]
Creo que, definitivamente, has perdido la "cabeza" (mira el comentario que te he dejado y lo comprenderás ;) )

**Comment by rociomacho** [comment]
Este es el nuevo [documento](https://docs.google.com/document/d/17nIB02wDgl03xWGu4XmKJ55OKbrE6bsAUXwdlSTK0ko/edit)

**Comment by profeIAP** [comment]
Y ha quedado perfecto, gracias Rocío
