### ISSUE TITLE
Cambiar estética documento "Recortar imágenes"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#239]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #100

**Comment by mariamiura16** [comment]
https://docs.google.com/document/d/1zfQdyTkpSxhs-k_FLnHhMz6k2pmcWuGY3r3O2gaFs-o/edit?usp=sharing cierro la tarea

**Comment by profeIAP** [comment]
Dejo comentarios sobre el propio documento.

Igualmente y, aunque pueda parecer "absurdo", es un requisito ocultar el enlace dentro del texto del comentario anterior (puedes editarlo en cualquier momento)

**Comment by mariamiura16** [comment]
[documento recortar imagenes ](https://docs.google.com/document/d/1zfQdyTkpSxhs-k_FLnHhMz6k2pmcWuGY3r3O2gaFs-o/edit?usp=sharing)

**Comment by mariamiura16** [comment]
cierro de nuevo porque he resuelto tus comentarios

**Comment by profeIAP** [comment]
Casi... quedaban dos

**Comment by profeIAP** [comment]
Han quedado cosas en el "tintero"

**Comment by profeIAP** [comment]
Desgraciadamente, siguen cosas pendientes

**Comment by mariamiura16** [comment]
a ver si ya es posible

**Comment by profeIAP** [comment]
Puede ser posible y, de echo, lo es... ¡Enhorabuena María!
