### ISSUE TITLE
Editar anotación

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#24]
Modificar entrada de la bd

**Comment by profeIAP** [comment]
Depende de la tarea #3

**Comment by profeIAP** [comment]
La implementación sería similar a [la que tenemos en el proyecto](https://github.com/profeIAP/proyecto2015-16/blob/3ddb49c48d2747de5df4e1ad4581ccedd932bf0a/index.php#L129)

**Comment by profeIAP** [comment]
Veo algunos problemas:
1. Has metido el código _dentro del método get('/')_ (es el encargado de listar anotaciones, no de guardarlas)
2. El [código que introduces](https://github.com/profeIAP/panelDeControl/commit/afbb38ff3a55fea772fe2ce506fd7c8883e164f0#diff-828e0013b8f3bc1bb22b4f57172b019dR101) opera sobre la tabla alumnos (en lugar de anotaciones)

Por facilitar el trabajo, recomiendo que incluyas en los comentarios de los próximos commits el número de tarea para que aparezca reflejado entre los comentarios del trabajo que estás realizando ( @antoniio92 puede ayudarte con este tema ;) )

**Comment by Patriexd** [comment]
que tengo que hacer en esta tarea @profeIAP

**Comment by profeIAP** [comment]
Espero que sea suficiente con lo comentado en clase, si no es así, dame un toque y te lo explico ¿te parece?

**Comment by profeIAP** [comment]
Otro sitio donde [puedes encontrar un ejemplo](https://github.com/profeIAP/panelDeControl/blob/50d3cd0eddcfff4fcc86e71393e9ac7cb218c456/index.php#L200)

**Comment by Patriexd** [comment]
Por fin

**Comment by profeIAP** [comment]
Sí señora, ¡por fin!

Pero hay que reconocer que ha quedado muy bien, ¡Enhorabuena Patri!
