### ISSUE TITLE
Cambiar estética documento "Mejorar calidad imágenes escaneadas"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#240]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by AbrahamgcArahal** [comment]
jose antonio ya te [he compartido el documento](https://docs.google.com/document/d/1ZK8Bw-ZbvOWcR05ZUCJFs6ZduXXh-WAvoHWO_Qg08fA/edit?usp=sharing) espero que sea de tu agrado

**Comment by profeIAP** [comment]
Desgraciadamente hay "detallitos" que pulir, ánimo

**Comment by AbrahamgcArahal** [comment]
Ya he resuelto los problemas que me comentaste, espero que ya esten resueltas, un saludo

**Comment by profeIAP** [comment]
Alguno nos queda pendiente

**Comment by AbrahamgcArahal** [comment]
A ver ahora

**Comment by profeIAP** [comment]
Ahora sí, gracias Abraham
