### ISSUE TITLE
Cambiar estética documento "Uso de la terminal en Geany"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#241]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

**Comment by profeIAP** [comment]
Necesito que revises los comentarios que te he dejado en el documento y, ya puestos, metas en el hilo de esta conversación un enlace al documento que has compartido para que sea más fácil acceder a él.

**Comment by AntonioJ98** [comment]
El [documento](https://goo.gl/aXwcNa)

**Comment by AntonioJ98** [comment]
No veo que haya que cambiar nada más. Échale un vistazo. @profeIAP

**Comment by profeIAP** [comment]
Revisado y comentado

**Comment by AntonioJ98** [comment]
A ver si está ya eso a su gusto. @profeIAP

**Comment by profeIAP** [comment]
Tengo un gusto muy "refinado" XD

**Comment by AntonioJ98** [comment]
Si está tarea es de cambiar la estética, ¿por qué me pones trabas añadiéndole nuevo contenido? @profeIAP

**Comment by profeIAP** [comment]
Porque, si se ve, se debe corregir ¿o eres de los que rehuyen y/o miran a otro lado?

**Comment by profeIAP** [comment]
Ahora sí, ha quedado perfecto.
Gracias Antonio Jesús
