### ISSUE TITLE
Cambiar estética documento "Gestión de proyectos"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#242]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Requiere esperar que se cierre la tarea #152

**Comment by antoniio92** [comment]
Estética cambiada :+1:

**Comment by profeIAP** [comment]
Veo que no has esperado a que @Rafaelcraftero acabe la tarea #152 

Es un "work in progress" por lo que has hecho trabajo inncesariamente.

Si @Rafaelcraftero fuese tan amable de seguir trabajando en [tu versión del documento](https://docs.google.com/document/d/1xf_naZMCV0Vwy4_oLaXWWfKr8gF-D0md1jZlffGqbec/edit?usp=sharing), igual te "libras" XD

**Comment by antoniio92** [comment]
esto va para largo no? JAJAJA

**Comment by profeIAP** [comment]
De momento quedas a la espera del final del trabajo por parte de D. Rafael (acá @Rafaelcraftero )

**Comment by antoniio92** [comment]
todo corregido :smile:

**Comment by profeIAP** [comment]
Pero no todo arreglado

**Comment by antoniio92** [comment]
Ahora si todo arreglado :smiling_imp:

**Comment by profeIAP** [comment]
Lo damos por bueno
