### ISSUE TITLE
Documentar la grabación del escritorio en formato GIF

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#243]
Crear documento compartido en el que se explique cómo grabar el contenido del escritorio (sería interesante poder elegir la ventana y/o zona a grabar) en Linux y su posible almacenamiento en un archivo **GIF Animado**.

La idea es poder mostrar en el blog (y/o en el wiki) determinadas funcionalidades que vayan apareciendo en la aplicación web.

Se aceptará tanto la grabación directa en gif como la grabación en vídeo y su posterior conversión a un gif (la que te resulte más sencilla)

**Comment by Mahc99** [comment]
Terminada.

**Comment by profeIAP** [comment]
Me temo que te queda bastante trabajo Miguel Ángel pero tiene una pinta estupenda

**Comment by Mahc99** [comment]
A lo mejor ahora esta bien (?)

**Comment by profeIAP** [comment]
Lo veo complicado... básicamente por haber ignorado la inmensa mayoría de las anotaciones que realicé en el documento :P

**Comment by Mahc99** [comment]
Mmmm he echo todo lo que me comentaste. (Quiza es que has mirado el documento antiguo cuando hoy te compartido otro nuevo  al parecerme mas facil incluir la plantilla desde una copia que rehacerlo todo de nuevo)

**Comment by profeIAP** [comment]
Toda la razón del mundo, como no teníamos enlazado [el documento compartido en Drive](https://docs.google.com/document/d/1Gwk0qZfTlDmF0YA8SBDj6xEUZ0Qyms-NWfAn4NTvb6M/edit?usp=sharing), me puse a corregir el que no era.

No obstante, te dejo algunas anotaciones... el trabajo tiene muy buena pinta

**Comment by Mahc99** [comment]
Corregido y con suerte terminado =P

**Comment by profeIAP** [comment]
Pues ha salido "cruz"...Sigue fallando la estructura del documento (te añado comentario al documento para que puedas solucionarlo)

**Comment by Mahc99** [comment]
Ya he cambiado la estructura, ya que no sabía como funcionaba anteriormente =P

**Comment by profeIAP** [comment]
No me cuadra Migue: confírmame que [este es el documento](https://docs.google.com/document/d/1Gwk0qZfTlDmF0YA8SBDj6xEUZ0Qyms-NWfAn4NTvb6M/edit?usp=sharing) que estás utilizando y/o comparte el enlace del nuevo.

Gracias

**Comment by Mahc99** [comment]
Si, es ese. Corregi la estructura y ahora solo los  que son titulos salen como tal. Si me puedes comentar lo que no te cuadra lo arreglo =P

**Comment by profeIAP** [comment]
Los niveles están elegidos incorrectamente: no se trata de ponerlos en
«cascada» sino de indicar la importancia de cada uno correctamente (piensa
en los apartados de cualquier tema de tus libros de texto)

**Comment by Mahc99** [comment]
Ya  creo que si. T_T

**Comment by profeIAP** [comment]
Confiesa Migue, me estás "troleando" ¿verdad?

![captura de pantalla de 2016-05-24 15 13 17](https://cloud.githubusercontent.com/assets/16881846/15505047/19e64ac6-21c2-11e6-88ca-6d9f8888ffa7.png)

**Comment by Mahc99** [comment]
Ojala fuera eso. He vuelto a cambiarlo.

**Comment by profeIAP** [comment]
Realmente esto parece un caso para Iker Jiménez... ¿seguro que no te estás quedando conmigo? XD

**Comment by Mahc99** [comment]
Ya había aprendido hacerlo, pero gracias. Respecto a lo de la tipografía he usado la misma que hay en el modelo en el encabezado.

**Comment by profeIAP** [comment]
Mal hecho... tamaños y tipos de letra son distintos.
¿Por qué sospecho que te has puedo a cambiar el estilo en el documento existente en lugar de pasar el contenido a la plantilla?

Aunque no te lo vas a creer...ahora está perfecto.

¡Damos por cerrada la tarea!
