### ISSUE TITLE
Completar ayuda configuración de GIT en la wiki del proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#244]
Incluir en el [apartado correspondiente de la wiki](https://github.com/profeIAP/panelDeControl/wiki#configuraci%C3%B3n) cómo listar las variables de configuración establecidas para nuestro proyecto.

La asigno directamente a @fdm1999 por haber incluido dicha información en [la documentación general del proyecto](https://docs.google.com/document/d/1-uDZdebGRuAp2iNBLcgsNaav6VfR3dg3KJwp8HW5P7I/edit#bookmark=id.zv7a6zcjoif) y considerar que es interesante que pueda accederse a ella desde la wiki.

**Comment by ghost** [comment]
Acabo de trasladar la configuración rápida y ayuda de Git de la documentación general del proyecto a la wiki. Cierro la tarea. Un saludo ;)

**Comment by profeIAP** [comment]
Añade algún ejemplo que facilite a tus compañeros el uso de
1. `git config {clave}`
2. los comandos de ayuda de git

**Comment by ghost** [comment]
acabo de añadir los ejemplos. El ejemplo de > git help es bastante largo (aunque hay más) pero es lo que aparece cuando lanzas ese comando. Cierro la tarea :)

**Comment by profeIAP** [comment]
Está bastante, bastante bien pero, con el segundo punto, me refería a incluir un ejemplo de uso de los comandos de ayuda de GIT que has puesto (y no que cuelgues la ayuda de git help ;) )

**Comment by ghost** [comment]
Lo acabo de cambiar. ¿Te referías a eso?

**Comment by profeIAP** [comment]
Sí, me refería a éso.

Mete un ejemplo de `git config --list` y damos por cerrada la tarea ¿te parece?

Enhorabuena, te ha quedado muy bien Francisco.

**Comment by ghost** [comment]
Acabo de incluir varios ejemplos. Cierro la tarea ;)

**Comment by profeIAP** [comment]
Pefecto Fran, ¡buen trabajo!
