### ISSUE TITLE
Ocultar los comentarios de la tarea #70

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#245]
Existen en la tarea #70 comentarios de los integrantes del grupo en los que aparecen los enlaces sin "ocultar" dentro del texto (visualmente poco profesional)

El **objetivo** de esta tarea es editar los comentarios de modo que sigan estando ahí pero que no se vean las urls.

**Comment by Cesarj9** [comment]
Acabada

**Comment by profeIAP** [comment]
Bote, gracias
