### ISSUE TITLE
Corregir la opción "Salir" del menú

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#246]
Debe aparecer como una opción simple (sin desplegar contenido)

![captura de pantalla de 2016-05-12 18 36 31](https://cloud.githubusercontent.com/assets/16881846/15222594/afa9cdcc-1870-11e6-9041-38c32fd99fc0.jpg)

**Comment by angel2190** [comment]
listo

**Comment by profeIAP** [comment]
Sí señor, perfecto.

Ahora sólo falta que @carlosaj98 le meta la ruta a /logout.

¡Buen trabajo Ángel, enhorabuena!
