### ISSUE TITLE
Añadir ruta a la opción "Salir" del menú

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#247]
La opción "Salir" del menú no tiene ninguna acción asociada.

Añadir enlace que apunte a la ruta **/logout**

**NOTA:** sólo tienes que añadir el enlace, no te preocupes si da error (por no existir el método GET en _index.php_)

**Comment by Raul-99** [comment]
Ya está hecha esta tarea

**Comment by profeIAP** [comment]
Genial Raul, acuérdate de subir los cambios al repositorio.

**Comment by Raul-99** [comment]
ya está acabada

**Comment by profeIAP** [comment]
Siguen sin estar los cambios en el repositorio, no puedo darla por cerrada aún.

Observo:
1. No existe el commit
2. No aparece tu usuario en ninguno de los commits de hoy
3. No se referencia a la tarea en ninguno de los commits del día de hoy

**Comment by profeIAP** [comment]
Raúl, siguen apareciendo varias opciones Salir (y la última de ellas incluye el enlace pedido en la tarea)

![captura de pantalla de 2016-05-25 16 51 49](https://cloud.githubusercontent.com/assets/16881846/15544486/2d8c6b50-2299-11e6-8484-6d874ed3f6ac.png)

Necesito que quites todo lo añadido y que sólo exista la primera de ellas

![captura de pantalla de 2016-05-25 16 54 17](https://cloud.githubusercontent.com/assets/16881846/15544520/55d8b3f2-2299-11e6-8e78-4485ac81a07e.png)

con el enlace a **/logout** pedido.

Rezo para que, con tanto "commit" no hayas "roto" algo :p

Debido a los continuos cambios y que se está complicando, subo la dificultad a "Normal" (espero que no te "moleste" ;) )

**Comment by Raul-99** [comment]
ya está

**Comment by profeIAP** [comment]
Casi Raúl
1. Ha vuelto a aparecer la lista desplegable (ya lo había quitado @angel2190 si no recuerdo mal) 
   ![captura de pantalla de 2016-05-30 19 31 55](https://cloud.githubusercontent.com/assets/16881846/15655430/6d1f49ec-269d-11e6-8b88-3f99e2914478.png)
2. El enlace a /logout tiene que estar en la entrada de primer nivel y no en la opción que despliegas (observa la imagen de cómo debe quedar) 
   ![captura de pantalla de 2016-05-30 19 34 15](https://cloud.githubusercontent.com/assets/16881846/15655443/8c6c2c7a-269d-11e6-9068-c2a256336d46.png)

**Comment by profeIAP** [comment]
Gracias Raúl, ha quedado perfecto.
