### ISSUE TITLE
Reducir la separación del menú superior

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#248]
Salvo que se vea mal en tu portátil (en cuyo caso bastará con subir captura de pantalla mostrando lo mal que queda), se necesita reducir en "1" la separación de las opciones del menú superior para que queden como en la siguiente captura.

![captura de pantalla de 2016-05-12 18 41 32](https://cloud.githubusercontent.com/assets/16881846/15222688/38ba27ec-1871-11e6-9430-7db3853a156f.png)

Para lograrlo, necesitaras modificar el fichero **layout.php** para dejarlo en una "distribución": 9+1+1+1=12 (a buen entendedor, pocas palabras bastan... ¿verdad @pablosaborido? ;) )

**Comment by nachowe12** [comment]
![captura de pantalla de 2016-05-30 14 16 17](https://cloud.githubusercontent.com/assets/15361371/15649652/6b467c3c-2673-11e6-9757-0aab8d17fb11.png) 
Como ves queda muy mal.

**Comment by profeIAP** [comment]
Sí queda mal... damos por cerrada la tarea, gracias Nacho.
¡Buen trabajo!
