### ISSUE TITLE
Renombrar ficheros de script

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#249]
Renombrar los ficheros de la carpeta **model/scripts** (los que no empiezan por view_) de modo que su nombre quede **table_**NOMBREFICHERO.sql (**p.e.** anotacion.sql quedaría como table_anotacion.sql)

**Comment by julioosos** [comment]
Ya.

**Comment by profeIAP** [comment]
Las tablas antiguas siguen estando (se supone que hay que renombrar, no duplicar)
Cuida que no se te haya olvidado algún fichero pues no me cuadra y los podrías borrar si lo haces "del tirón"

**Comment by julioosos** [comment]
yo hice un pull antes de esta tarea asi que deben de estar todos los ficheros de la carpeta scripts

**Comment by profeIAP** [comment]
Estar están pero hay más de la cuenta... lo más probable es que hayas ignorado algunos de los mensajes que aparecen al lanzar un _git status_: básicamente todos aquellos que dicen que los ficheros han sido borrados (y por tanto requieren un _git rm_)

**Comment by julioosos** [comment]
va

**Comment by julioosos** [comment]
ya

**Comment by profeIAP** [comment]
Ahora sí, perfecto Julio
