### ISSUE TITLE
Incluir el nuevo favicon de la web

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#251]
Incluir el nuevo favicon (tarea #167) en nuestra web.

El trabajo es prácticamente le mismo que el de la tarea #104 aunque se deberá:
1. comprobar que funciona tanto en Firefox como en Chrome
2. asegurar que el fichero (renombrar) tiene por nombre **favicon.ico**

**Comment by AbrahamgcArahal** [comment]
ya tenemos el favicon nuevo XD

**Comment by profeIAP** [comment]
Sí señor, muchas gracias Abraham
