### ISSUE TITLE
Cambiar plantilla blog

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#253]
Buscar (comentar, antes de subir, en este mismo hilo la propuesta que deseas utilizar) y cambiar la plantilla que tenemos actualmente en Blogger

**Comment by Cesarj9** [comment]
Blogger?? el blog?

**Comment by profeIAP** [comment]
Yep!

**Comment by profeIAP** [comment]
¿¡¿Qué cosa has puesto por plantilla?!? Has debido pillar un mal día de @antoniio92 porque la elegida es fea de dolor XD (amén de no haber consultado conmigo antes de subirla)

No te limites a las plantillas que vienen en Blogger... esas ya las he mirado yo (¿asignarías la etiqueta "reto" a hacer click sobre una de las que ya vienen? :) )

César, a ser posible, búscala "azulita" que son nuestros colores corporativos

**Comment by Cesarj9** [comment]
De acuerdooo... vaya... me gustaba el verde... la cambiare lo antes posiblee

**Comment by Cesarj9** [comment]
Espero que esta agrade mas a su gusto visual y no le sangren los ojos.
PD: habia una muy buena de star wars.... una pena

**Comment by profeIAP** [comment]
Hubiese estado chula la de Star Wars pero, como bien has intuido, desentonaba con la temática del blog XD

La de Saloon de pelis de "vaqueros" que has puesto no está mal (del todo), lástima que se "rebose" el menú por abajo ¿no te parece?

**Comment by Cesarj9** [comment]
Las "azulitas" que he llegado a encontrar o son muy tristes o no se adaptan bien a la pagina, por lo tanto creo que la nueva es una de las que mejor podría quedar.

**Comment by profeIAP** [comment]
Bastante mejor César pero... ¿puedes quitar cosas del margen derecho (p.e. las noticias más populares) para que se vean mejor las noticias? (Agobia un poco)

**Comment by Cesarj9** [comment]
creo que tal y como lo acabo de modificar es de las mejores formas que se puede poner esta plantilla, dejando algo mas libre la columna derecha.

**Comment by profeIAP** [comment]
Yo lo veo igual que ayer

**Comment by Cesarj9** [comment]
No, he cambiado el numero de noticias populares a muchas menos, y para que no se sature tanto he puesto que las noticias estén por meses, así se ve mucho mejor y algo menos agobiante, no?

**Comment by profeIAP** [comment]
El problema está en que tiene la misma importancia que las noticias de
actualidad (Que debería tener un espacio predominante)

**Comment by Cesarj9** [comment]
me podrías mandar al correo las imágenes de los 3 grupos??

**Comment by profeIAP** [comment]
Me gusta mucho la plantilla nueva (enhorabuena César)

He compartido carpeta en la que tenemos documentación (con las fotos de los distintos proyectos), debería haberte llegado invitación.

Gracias César

**Comment by Cesarj9** [comment]
Si, me ha llegado, pero no he tenido tiempo, de todos modos he de decidir que fotos quedaría mejor colocada.

Mucha gracias.

**Comment by Cesarj9** [comment]
Considera cambiar la etiqueta de ofimática a web o programación por su necesidad de la edición e  HTML...

**Comment by Cesarj9** [comment]
Donde puedo encontrar el javascript de las imágenes que van en sucesión del principio del blog?

**Comment by profeIAP** [comment]
Sus "deseos" son órdenes (amén de parecerme coherente y lógico)

Las imágenes puedes encontrarlas aquí

![captura de pantalla de 2016-05-25 15 43 05](https://cloud.githubusercontent.com/assets/16881846/15542068/76fa5fa4-228f-11e6-9c76-4751ad1857e2.png)

**Comment by Cesarj9** [comment]
Al fin, se recomienda escuchar con So What - Miles Davis, idea para otra tarea!!

**Comment by profeIAP** [comment]
Aplaudo la creatividad y la belleza del trabajo final.

Agradecer por igual a @FranPeroNoMoreno su colaboración que, aunque al César hay que darle lo que es suyo (y por tanto le pertenece) a los "currantes" hay que reconocerles el saber hacer y la dedicación (aunque sea agazapado en las sombras por el mero placer de crear algo bello)

Muy buen trabajo, chicos... deseando estoy ver alguna noticia publicada en el blog por lo que dejo aquí la idea para el que esté pensando en acometer la tarea #70 y esté falto de creatividad.
