### ISSUE TITLE
Usar datos reales en el autocompletado

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#254]
Modificar el campo **Alumno/a implicado** del formulario **parte.php** para que, haciendo uso del autocompletado:
1. sugiera nombres de alumno que coincidan con los datos introducidos
2. rellene los campos **Alumno/a implicado** y **Curso y Grupo** del alumno seleccionado cuando pierda el foco

**Comment by julioosos** [comment]
tengo un problema es que tenía pensado que el autocompletado entero era de uno de programación pero ahora son dos podrias meterlo solo en un paquete es que sino la varianza entre ofimatica y programacion se me va a  desequilibrar

**Comment by profeIAP** [comment]
Ya comentado en clase el "problema"...

**Comment by julioosos** [comment]
no comentado, no me has dicho si lo vas a dejar como una de programación o dos ¿que vas ha hacer?

**Comment by profeIAP** [comment]
Dijiste que te daba igual si lo dejaba como tarea de Programación ¿no?

**Comment by profeIAP** [comment]
Tu SQL para buscar por nombre sería  

> select nombre from alumno where nombre like '%:nombre%';

**Comment by julioosos** [comment]
maestro acuerdate de mirarme el autocompletado

**Comment by profeIAP** [comment]
Menos mal que me lo has recordado (gracias)

Al final he encontrado una forma eficiente de pasar a JSON el resultado de una consulta: el truco está en **PDO::FETCH_COLUMN** que, en lugar de devolver un array de objetos JSON (campo, valor) nos permite obtener un array que sólo contiene los valores de la columna.

No me enrollo más... que lo "disfrutes" ;)

**Comment by julioosos** [comment]
gracias

**Comment by profeIAP** [comment]
Un placer... estoy deseando ver el autocompletado en funcionamiento ;)

**Comment by julioosos** [comment]
si sigue estando libre volveré cuando equilibre mi desfase

**Comment by profeIAP** [comment]
Jaaaaarrrrrrr.... ¿¡¿y decides corregir el equilibrado "de ruedas" a estas alturas de la película?!? :O

Sería partidario de entrar en "negociaciones" y plantearme cambiar la categoría de la tarea si así te resulta más conveniente ;)

**Comment by julioosos** [comment]
Perfecto pues, en el momento en el cual yo acabe una de mis dos tareas me pongo manos a la obra con esta pero has de cambiarla a ofimática pero que no tenga que documentar nada que me da pereza XD

**Comment by profeIAP** [comment]
¿¡¿Pereza es lo que provoca las faltas de ortografía de tu comentario anterior?!? Por favor corrígelas antes de que me revienten los ojos.

**Comment by profeIAP** [comment]
@juanry, esta tarea es francamente compleja (con diferencia una de las peores que tenemos actualmente).
No sé si lo comenté en clase pero creo que igual opto por cogerla yo e implementarla para tener un modelo con el cuál poder realizar otras tareas similares.

**Comment by profeIAP** [comment]
Al final (y como "amenacé" en clase) la he implementado yo (para que tengáis un ejemplo al que recurrir) en el commit cbeb6019552315a6e89dd9da690ae86d03769b81

**Comment by profeIAP** [comment]
A modo de ilustración, dejaré la siguiente captura de la funcionalidad que se ha implementado

![image](https://user-images.githubusercontent.com/16881846/57233094-488c6100-701e-11e9-99af-808fc5308d41.png)
