### ISSUE TITLE
Alinear a la derecha la botonera de Parte.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#255]
Cambiar la alineación de los botones para que aparezcan en el lado derecho del formulario.

![captura de pantalla de 2016-05-16 18-17-22](https://cloud.githubusercontent.com/assets/16881846/15295792/86e3e1e6-1b92-11e6-92ed-74e856860595.png)

**Comment by profeIAP** [comment]
¿Será una tarea para nuestro "maquetador profesional" @pablosaborido? :)

**Comment by javierfl98** [comment]
te recuerdo que me has dicho que la ibas a poner como reto

**Comment by profeIAP** [comment]
Y como hombre de palabra, cumplo lo prometido

**Comment by profeIAP** [comment]
¿¡¿He cerrado automáticamente la tarea?!?

**Comment by profeIAP** [comment]
Estoy deseando ver tu commit.

La idea de ponerlo como reto se sustenta en que servirá de referencia a otras tareas similares

**Comment by javierfl98** [comment]
terminada

**Comment by profeIAP** [comment]
Ha quedado espectacular, gracias Javier
