### ISSUE TITLE
Cambiar botonera Alumno.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#256]
Cambiar en la vista **alumno.php** la botonera actualmente existente por una como la utilizada en **parte.php** (de utilidad resultarán las tareas #169 y #255)

Dicha botonera:
1. Debe estar alineada a la derecha (tarea #255)
2. Incluir los botones:
   - **Cancelar** (rojo): /alumnos/cancelar
   - **Aceptar** (verde): /alumnos/aceptar

Igualmente, se deberá eliminar el botón **Enviar** actualmente existente en el formulario

**Comment by carlosaj98** [comment]
ya esta hecha

**Comment by profeIAP** [comment]
Perfecto Carlos, ¡Un gran trabajo y en tiempo record!
