### ISSUE TITLE
Alinear a la derecha la botonera de Alumno.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#258]
Cambiar la alineación de los botones para que aparezcan en el lado derecho del formulario.

De especial utilidad sería la tarea #255

**Comment by rociomacho** [comment]
Respecto a esta tarea ya casi tengo averiguado cómo podría hacerlo, mi duda es: una vez que haga el cambio, ¿dónde tengo que mirar para comprobar que lo he realizado correctamente?

**Comment by profeIAP** [comment]
Genial... bastaría solicitar [la creación de un alumno](http://localhost:9000/alumnos/crear) y comprobar que los botones están en la derecha

**Comment by rociomacho** [comment]
¡Terminado! Espero que consideres la idea del reto.

**Comment by profeIAP** [comment]
Y ha quedado perfecto.

Al haber terminado la tarea sin poder ver el resultado de la #255 considero justo subir su categoría a "reto"

Muy buen trabajo, enhorabuena
