### ISSUE TITLE
Incluir calendario al campo ANOTACION.FECHA

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#259]
Modificar el formulario **view/anotacion.php** para que el campo FECHA incluya la posibilidad de seleccionar una fecha (evitando tener que introducirla manualmente)

Se recomienda esperar la finalización de la tarea #202 (no es imprescindible pero evitarás "conflictos" y cambios imprevistos) y te resultará de especial utilidad el trabajo realizado en la tarea #184

**Comment by dnrg98** [comment]
Arreglado con la ayuda de Antonio

**Comment by profeIAP** [comment]
Espectacular... le debes una al bueno de @AntonioJ98
