### ISSUE TITLE
Incluir acceso al blog en README.MD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#261]
Añadir [enlace al blog](http://semillerodeempresas.blogspot.com.es/) en el fichero README.MD

La entrada debe incluir:
1. un icono "alusivo" (¿logo de Blogger?)
2. un texto que invite a la participación (que no sea excesivamente largo, sólo exhortar a la acción)

**Comment by Patriexd** [comment]
;)

**Comment by profeIAP** [comment]
Genial, gracias Patri... definitivamente estás en "racha"
¡Sigue así!
