### ISSUE TITLE
Organizar documento "Servidor PHP"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#262]
Organizar convenientemente en apdos. (y dar algo más de sentido y coherencia a su contenido) [el documento "Servidor PHP"](https://docs.google.com/a/iesalandalus.com/document/d/1PRNOKOUI6jrGdE59teeujpevFCpb5mLf4GoEo5vcOGo/edit?usp=sharing)

**Comment by ghost** [comment]
Acabo de incluir los apdos. y cambiado algunas cosas del contenido. La dejo abierta por si hay algún fallo.

**Comment by profeIAP** [comment]
Bastante bien Francisco:
1. He editado levemente el texto
2. Te dejo un par de sugerencias para que quede perfecto

**Comment by ghost** [comment]
Acabo de recortar la foto. Creo que ya está bien. Cierro la tarea.

**Comment by profeIAP** [comment]
Incluyo comentarios

**Comment by ghost** [comment]
Acabo de cambiar la imagen y se ve mejor que antes. Dejo abierta la tarea por si hay algo más que arreglar.

**Comment by profeIAP** [comment]
No tengas miedo por cerrar las tareas... de todos modos, te he dejado comentario

**Comment by ghost** [comment]
Terminada :)

**Comment by profeIAP** [comment]
Perfecto, Fco. ¡Buen trabajo! (gracias)
