### ISSUE TITLE
Cambiar estética documento "Requisitos funcionales"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#263]
Adaptar la estética del documento a [la definida en la plantilla modelo](https://docs.google.com/document/d/1hsTZNaq8dMddGS2G9unRnwjtRucYc8fjalfC7gNNhCk/edit)

Se etiqueta como "Reto" debido al tamaño del documento.

**Comment by rociodanone3** [comment]
He cerrado la tarea porque ya está terminada, a falta del encabezado que me está creando problemas para insertarlo. El próximo día lo volveré a intentar desde otro portátil

**Comment by profeIAP** [comment]
Agradecería que no cerrases la tarea hasta que no consideres que está lista para ser revisada ;)

**Comment by rociodanone3** [comment]
Por favor intenta insertar la imagen del encabezado tú que es lo único que me falta para terminar la tarea, lo que condiciona también el desarrollo de mi entrada en el blog, ya que al no tener la tarea terminada no puedo adjuntar fotos. Ayúdame cuando tengas un rato porfiiiiiiiiiiiiiiiiii =(

**Comment by profeIAP** [comment]
Sus deseos son órdenes... imágenes insertadas

**Comment by rociodanone3** [comment]
Como ya está el encabezado adjunto, puedo cerrar mi tarea, por fiiiiiiiiiin!!!!!!! =)

**Comment by profeIAP** [comment]
¿¡¿Realmente pensabas que iba a resultar tan sencillo?!? juas juas juas (poner risa "diabólica")

Te dejo un par de anotaciones que sospecho habrán llegado a tu correo electrónico ;)

**Comment by rociodanone3** [comment]
He seguido las anotaciones que me enviaste al correo, y tras mi cita de hoy creo que por fin puedo cerrar la tarea correctamente

**Comment by profeIAP** [comment]
Ha quedado espectacular, muchísimas gracias Rocio
