### ISSUE TITLE
Añadir opción "Reiniciar terminal" al documento "Uso de la terminal en Geany"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#264]
Añadir anotación al documento [Uso de la terminal en Geany](https://docs.google.com/document/d/1qGw7POvqls41JTkEabE_efpReI3YHo_PCQm3MgTtyuU/edit#bookmark=id.xitpdxxqvkqm) explicando que si no cambia automáticamente al directorio solicitado, se soluciona reiniciando la terminal

![captura de pantalla de 2016-05-24 15 38 44](https://cloud.githubusercontent.com/assets/16881846/15505904/b2d8c18e-21c5-11e6-89f4-c7789d65e126.jpg)

**Comment by josufg** [comment]
@profeIAP Ya he añadido ese dato extra. Echale un vistazo y me dices lo que sea antes de cerrarla.

**Comment by profeIAP** [comment]
Comento sobre el documento

**Comment by josufg** [comment]
@profeIAP Ya lo he arreglado, échale un vistazo a ver que tal.

**Comment by profeIAP** [comment]
Te incluyo sugerencia en los comentarios

**Comment by josufg** [comment]
@profeIAP Mira en tu sugerencia

**Comment by profeIAP** [comment]
Mirado... quedo a la espera de novedades.

**Comment by josufg** [comment]
@profeIAP La cierro pues. Cualquier sugerencia la vuelves a abrir

**Comment by profeIAP** [comment]
Tengo una duda "existencial", te la anoto en los comentarios del documento.

**Comment by josufg** [comment]
Te contesté @profeIAP . No lo has leido?XD

**Comment by profeIAP** [comment]
Son miles (exageración en pro del andaluz) las notificaciones de Drive que recibo a diario.
Hemos acordado que, cuando consideréis que el documento está listo para volver a ser revisado, lo mejor es dejar un comentario en la tarea de GitHub.

Te dejo comentarios para que finalices el documento de una vez ;)

**Comment by josufg** [comment]
@profeIAP Ahora creo que está mejor (he quitado la parrafada XD) y he intentado explicar mejor (ya se la utilidad de "Reiniciar terminal".

**Comment by profeIAP** [comment]
Tus explicaciones, en ocasiones, me dan "miedo".

En esta ocasión, ha quedado bastante aceptable.

**Comment by josufg** [comment]
@profeIAP Jajaja vale
