### ISSUE TITLE
Documentar cómo enlazar a un apartado concreto de un documento

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#265]
Crear documento compartido en Google Drive explicando:
1. cómo añadir un marcador a un apartado de un documento
2. cómo obtener el enlace de dicho marcador

**Comment by profeIAP** [comment]
Necesito el enlace al documento compartido para poder corregir

**Comment by profeIAP** [comment]
l

**Comment by Cesarj9** [comment]
Te lo he compartido... pero bueno [aquí](https://docs.google.com/document/d/1P1xqof8Ntcvu9AO2QbE9bFq5TteEGTtntegpo8WRl4s/edit?usp=sharing) lo tienes

**Comment by profeIAP** [comment]
Pero no lo habías enlazado en la tarea :P

Está perfecto y a la primera... publica la noticia que te falta César
