### ISSUE TITLE
Documentar cómo añadir un enlace en MarkDown

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#266]
Crear documento compartido en el que se explique cómo añadir enlaces (tanto gráficamente como usando directamente la sintaxis markdown) en el texto de cualquier comentario de GitHub

**Comment by SyalChain** [comment]
@profeIAP ¿Esta tarea presume de tanta dificultad como el de las tablas? xD

**Comment by profeIAP** [comment]
Aquí no presumimos (aunque podríamos) de nada XD

La tarea en si no es complicada, la etiqueto como reto pues "presumo" que al final se os hará eterna por no hacer las cosas medianamente bien a la primera y requerir alguna interacción con este "humilde" profesor :P

**Comment by rociolm** [comment]
Ya te la he compartido, corrígela cuando puedas porfavor.

**Comment by profeIAP** [comment]
Gracias pero no olvides incluir el enlace al documento en los comentarios de esta tarea

**Comment by profeIAP** [comment]
Te incluyo comentarios sobre el documento que me has compartido

**Comment by rociolm** [comment]
Ya lo he corregido maestro, aquí te dejo el enlace: https://docs.google.com/document/d/1xU1acpywluhUvPPsVB1TdpybMCKRcRTwzHkHMHLaiTU/edit#

**Comment by profeIAP** [comment]
Al documento aún le queda bastante trabajo. Te dejo algunos comentarios.

**NOTA:** Oculta el enlace en el texto del comentario anterior para poder dar por cerrada la tarea.

**Comment by rociolm** [comment]
La he corregido de nuevo

**Comment by profeIAP** [comment]
Sigue pendiente **ocultar el enlace** en [tu comentario](https://github.com/profeIAP/panelDeControl/issues/266#issuecomment-223505041)

Te dejo algunas anotaciones

**Comment by rociolm** [comment]
Corregido de nuevo

**Comment by rociolm** [comment]
Acabo de añadir otra captura de pantalla para usarla como ejemplo, espero tu respuesta

**Comment by profeIAP** [comment]
Te dejo anotaciones en el documento

**Comment by rociolm** [comment]
Espero que ya este un poco mejor, he recortado las imagenes y borrado algunas cosas!

**Comment by profeIAP** [comment]
Genial @rociolm ... recuerda [ocultar el enlace](https://github.com/profeIAP/panelDeControl/issues/266#issuecomment-223505041) en el siguiente comentario

**Comment by profeIAP** [comment]
Ya empieza a tener coherencia... te incluyo algunas mejoras para que te quede perfecto.

**Comment by rociolm** [comment]
Acabo de corregir los fallos que tenía.

**Comment by profeIAP** [comment]
Te incluyo algunas mejoras para que quede perfecto.
Gracias Rocío

**Comment by rociolm** [comment]
Espero que este bien yaa!!!

**Comment by profeIAP** [comment]
Pues vuelves a incluir definiciones de enlaces "tipo Linux"en el documento.
Igualmente **recuerda** que [exijo que ocultes el siguiente enlace](https://github.com/profeIAP/panelDeControl/issues/266#issuecomment-223505041)

**Comment by rociolm** [comment]
Ya lo he corregido, aqui tienes oculto el enlace [https://docs.google.com/document/d/1xU1acpywluhUvPPsVB1TdpybMCKRcRTwzHkHMHLaiTU/edit#](url)

**Comment by rociolm** [comment]
Ya he corregido el documento, y he ocultado el enlace.

**Comment by profeIAP** [comment]
Y tanto que lo has ocultado ¿¡¿por qué has borrado el enlace al documento?!? 

Resulta "simpático" que seas precisamente tú quien esté explicando cómo usar enlaces en MarkDown XD

**Comment by profeIAP** [comment]
Te incluyo los comentarios (¿finales?) en el documento

**Comment by rociolm** [comment]
Teacher espero que ya este biennnnn! jaja aqui te dejo el enlace oculto!! 

[TAREA](https://docs.google.com/document/d/1xU1acpywluhUvPPsVB1TdpybMCKRcRTwzHkHMHLaiTU/edit#)

**Comment by profeIAP** [comment]
Ahora sí Rocío... ¡Qué bien trabajas cuando trabajas bien!
¡Enhorabuena!
