### ISSUE TITLE
Incluir editor WYSIWYG en las observaciones de un Alumno

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#268]
Modificar el campo **Comentario** del formulario **view/alumno.php** para que muestre un editor WYSIWYG como el implementado por @linanalandalus en la tarea #182

**Comment by josemita6** [comment]
maximo esfuerzo;)

**Comment by profeIAP** [comment]
Máximo rendimiento... pero el esfuerzo es del de al lado ¿no?
