### ISSUE TITLE
Evitar la existencias de noticias sin título en el blog

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#271]
Repasar el listado de noticias que hemos publicado y asegurar que todas tienen asignadas un título

![titulos-blog](https://cloud.githubusercontent.com/assets/16881846/15583127/b7b10634-2374-11e6-98f1-7fd2b7a1b7c7.jpg)

**Comment by Cesarj9** [comment]
Que mal preparado todo... echo en falta un enlace al [blog](http://semillerodeempresas.blogspot.com.es/)... 

No me lo tengas en cuenta... me vuelvo perfeccionista...

**Comment by Cesarj9** [comment]
No me lo tengas en cuenta... me vuelvo perfeccionista...

**Comment by Cesarj9** [comment]
Ya finalizada, aunque me he visto en la obligación de editar algunas entradas, debido a su título en la publicación y no en su lugar correspondiente. 

Que conste que solo decidí realizarla por poder decirte lo del primer comentario y para asegurarme la nota, aun así sigo 120% en las validaciones

**Comment by profeIAP** [comment]
Definitivamente he creado un "mostruo" (pero he de reconocer que me siento satisfecho de haber plantado, regado y alimentado ese espíritu crítico del que actualmente presumes y del que espero que hagas un buen uso ;) )

Te dejo una frase de esas que sabes que me gusta atesorar (y que esta mañana te comenté que preferí no escribir): 

> Más vale apuntar a la perfección y fallar 
> que apuntar a la mediocridad y acertar.
> [Francis Blanche]

**NOTA:** Tampoco es un secreto que no me sé resistir XD
