### ISSUE TITLE
Añadir reproductor MP3 al blog

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#272]
[Añadir reproductor](https://www.google.es/search?client=ubuntu&channel=fs&q=blogger+mp3+player&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=EC1HV829B4jW8AegkbmwDA) MP3 al blog de nuestro proyecto.

Entre la lista de canciones y, [por petición popular](https://github.com/profeIAP/panelDeControl/issues/253#issuecomment-221850336), deberá incluirse (entre otras) el tema _So What - Miles Davis_

**Comment by alemorales1999** [comment]
creo que ya está terminado

**Comment by profeIAP** [comment]
Fantásticamente bien Alejandro; @FranPeroNoMoreno y @Cesarj9 estarían orgullosos del trabajo realizado ;)

Enhorabuena y gracias por igual... hasta @rociodanone3 [te han dedicado un artículo en el blog](http://semillerodeempresas.blogspot.com.es/2016/06/el-blog-cuenta-con-hilo-musical.html) jejeje
