### ISSUE TITLE
Marcar "gráficamente" las IDEAs de la tarea #70

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#273]
Editar **todos** los comentarios de la tarea #70 en los que aparezca alguna idea de publicación para que muestre la bombilla de la imagen

![captura de pantalla de 2016-05-27 16 07 59](https://cloud.githubusercontent.com/assets/16881846/15610400/572e6282-2425-11e6-914d-a170b25b3fd8.png)

Para que funcione, sólo necesitar [mirar el código del siguiente comentario](https://github.com/profeIAP/panelDeControl/issues/70#issuecomment-222154692)

**Comment by SyalChain** [comment]
@profeIAP Es poco "ético" hacer preguntas de trabajo en un domingo xD pero, ¿habría que editar única y exclusivamente los comentarios con **IDEA** o también posibles sugerencias sin marcar como idea?

**Comment by SyalChain** [comment]
@profeIAP Hecho.

**Comment by profeIAP** [comment]
Perfect Emilio
