### ISSUE TITLE
Títulos en minúscula

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#275]
Repasar los títulos de todas las publicaciones del blog pasando a minúsculas aquellos que no estén

![captura de pantalla de 2016-05-31 16 06 58](https://cloud.githubusercontent.com/assets/16881846/15677269/d7c944b2-2749-11e6-9849-6bcfd8b25970.png)

**Comment by rociolm** [comment]
Ya he modificado todas las entradas, corrigelo cuando puedaaaaaaaaaaaaas!

**Comment by profeIAP** [comment]
A la primera @rociolm ¡Muy buen trabajo!
