### ISSUE TITLE
Formulario login en ventana "única"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#276]
Asegurar que el formulario de login aparece sin el layout actual.

Deberá: 
1. aparecer en una ventana completamente "en blanco" (sin cabecera ni menú)
2. centrado en pantalla

En lugar de como está actualmente

![captura de pantalla de 2016-05-31 16 09 08](https://cloud.githubusercontent.com/assets/16881846/15677347/36e64b48-274a-11e6-9c31-3b1616e4095e.png)

**Comment by carlosaj98** [comment]
Ya la he echo

**Comment by profeIAP** [comment]
A falta del detalle de centrar el formulario (y quitar la línea que se te ha quedado en la parte superior) tiene muy buena pinta.

Me ha encantado la iniciativa (y visión) de crear un nuevo layout.

¡Enhorabuena Carlos!

**Comment by carlosaj98** [comment]
ya he puesto el alineado vertical y he quitado la linea de la parte superior

**Comment by profeIAP** [comment]
Espectacular @carlosaj98 salvo por:
1. La raya negra que aparece en la caja de la contraseña
2. Está alineado a la derecha (verticalmente está perfecto)

![captura de pantalla de 2016-06-07 14 01 13](https://cloud.githubusercontent.com/assets/16881846/15856829/677a101e-2cb8-11e6-868c-3c7da01c9ab6.png)

**Comment by carlosaj98** [comment]
ya lo he corregido

**Comment by profeIAP** [comment]
Realmente espectacular perooo... ¿qué ha pasado con el logotipo del proyecto? (se ha perdido)

**Comment by carlosaj98** [comment]
ya lo he puesto bien

**Comment by profeIAP** [comment]
Oooolleeee... ¡ha quedado espectacular Carlos! ¡Enhorabuena!

Creo que este logro se merece una publicación en el blog (tarea #70) ¿no os parece? ;)
