### ISSUE TITLE
Documentar funcionamiento pantalla "Asignación de tutores"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#278]
Documentar la interacción del usuario con[ la pantalla que permite indicar qué profesor ejerce de tutor](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.7vd6m09yp57k) en cada grupo del centro usando como modelo la estructura definida en la [Edición de alumnos.](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.urcfy1a5u9t)

Deberá tenerse en cuenta:
1. El Sistema obtiene los grupos automáticamente a partir de los que se han utilizado al importar los alumnos del presente curso académico.
2. El Sistema sugiere nombres de profesores conforme los va escribiendo el Usuario

**Comment by majimgall** [comment]
Maestro ya he escrito en los requisitos funcionales en la asignación de tutores

**Comment by profeIAP** [comment]
Te dejo comentarios en el documento

**Comment by majimgall** [comment]
Maestro lo he corregido  jeje

**Comment by profeIAP** [comment]
Más quisieras...

**Comment by majimgall** [comment]
míralo aunque dudo  que este bien

**Comment by profeIAP** [comment]
Te lo confirmo... piensa un poco, no es tan complicado (y tienes ejemplos más arriba)

**Comment by majimgall** [comment]
Lo he vuelto a hacer 😞😞 espero haberlo entendido bien

**Comment by profeIAP** [comment]
Bastante mejor, María.
Damos por finalizado el trabajo.
