### ISSUE TITLE
Ajustar ancho campo Anotación.Fecha

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#279]
Ampliar el tamaño del campo Fecha en el formulario view/anotacion.php para que ocupe todo el espacio reservado para él y guarde una estética similar a la del resto de campos que aparecen en dicho formulario

![captura de pantalla de 2016-06-02 16-38-33](https://cloud.githubusercontent.com/assets/16881846/15748885/b9332480-28e0-11e6-8db0-b92a3a44796e.jpg)

**Comment by ghost** [comment]
Terminada con dificultades jeje.

**Comment by profeIAP** [comment]
Bien está lo que bien acaba...
