### ISSUE TITLE
Listar grupos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#28]
Sacar los **distintos** grupos a los que pertenecen los _alumnos_.
Deberá usarse la cláusula "distinct" en la sentencia SQL

**Comment by linanalandalus** [comment]
Esta tarea depende de la tarea #1

**Comment by profeIAP** [comment]
Para que puede ser utilizado, se deberá [crear una vista](https://docs.google.com/a/iesalandalus.com/document/d/1vwjKLieWg3o0dao3fAU072zPCYhkYTxzol-xzbjXkTw/edit?usp=sharing).

**Comment by linanalandalus** [comment]
ya esta la vista listadegrupos creado y subido al github.

**Comment by profeIAP** [comment]
Está perfecto Li Nan.

¿Podrías incluir en **la carpeta scripts** el script necesario para crear la vista? 

Sospecho que deseparecerá tan pronto alguien suba una nueva versión del binario de la BD.

**Comment by linanalandalus** [comment]
el script se incluye asi?????

**Comment by profeIAP** [comment]
Sí que se incluye así, la pega que te voy a poner es que el nombre de la vista (listadodealumno) no es lógico.

Cambia el nombre por **listaDeCursos** (ojo al uso de mayúsculas)  y no olvides modificar el fichero sql del script.

**Comment by linanalandalus** [comment]
acabo de modificar el nombre en la vista de base de datos y en el script.

**Comment by profeIAP** [comment]
Espectacular @linanalandalus, muy buen trabajo.

**Comment by profeIAP** [comment]
Eso sí... lo de las "mayúsculas" te lo has saltado a la "piola" XD
