### ISSUE TITLE
Homogeneizar el modo de mostrar las webs de los proyectos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#281]
Editar el [documento de requisitos funcionales](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=kix.7kxpmw7yk230) para que los enlaces a las webs de los distintos proyectos (GitHub, Twitter, Blogger, ...) en los que se basa nuestro Panel de Control tengan el mismo formato.

Sería interesante consensuarlo con @profeIAP antes de cambiarlos todos para evitar trabajo innecesario.

**Comment by danigomez99** [comment]
Tarea finalizada.

**Comment by profeIAP** [comment]
Bastante bien salvo que te han bailado algún que otro enlace, comento sobre el propio documento

**Comment by danigomez99** [comment]
Ya he cambiado los enlaces incorrectos.

Pd: El facebook de apuesta y gana y lector de huellas dactilar tienen el facebook cerrado por lo que no sale el perfil (yo ahí no puedo hacer nada).

**Comment by profeIAP** [comment]
Tienes toda la razón: quita los enlaces de los perfiles que yo no existan y/o estén cerrados.

Observo que, aunque parecidos, hay "lotes de iconos" que tienen más (o menos) espacios que otros: he estado corrigiendo algunos pero como no se "acababan" te dejo pendiente eliminar todo el espacio que sobre para compactarlos e intentar que ocupen el menor espacio posible (con suerte cabrán todos juntos en la misma página y, a ser posible, con el párrafo de su definición)

Gracias Daniel, está quedando muy bien

**Comment by danigomez99** [comment]
He intentado quitar los máximos espacios posible y en dos proyectos el icono de git sale en otra página diferente porque no hay espacio en la que está plasmado su correspondiente proyecto.

**Comment by profeIAP** [comment]
Te ha quedado muy bien, muchas gracias D. Danié
