### ISSUE TITLE
Cambiar el color de la opción "Salir"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#282]
Modificar la hoja de estilos para que el tono de azul de la opción **Salir** sea el mismo que el del resto de opciones

![captura de pantalla de 2016-06-03 13 24 17](https://cloud.githubusercontent.com/assets/16881846/15777319/8f531b8a-298e-11e6-9e0b-bb8cc6475ce8.png)

**Comment by carlosaj98** [comment]
ya he puesto el color

**Comment by profeIAP** [comment]
Cierto, y ha quedado muy bien.

¿Podrías ponerlo en "negrita" para que no desentone con el resto?

Gracias Carlos

**Comment by carlosaj98** [comment]
ya lo he solucionado

**Comment by profeIAP** [comment]
Y perfectamente además... ¡Buen trabajo Carlos!
