### ISSUE TITLE
Redireccionar correctamente al borrar un alumno

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#283]
Cambiar [la redirección existente actualmente](https://github.com/profeIAP/panelDeControl/blob/72878b8ab4c10748e61074641870a40bf14d5a45/index.php#L180) para que al borrar un alumno aparezca el listado de alumnos.

Debe hacerse un

> $app->redirect('/alumnos');

**Comment by 1998ejc** [comment]
hecho!!

**Comment by profeIAP** [comment]
Sí señor, y te ha quedado perfecto.

¡Sigue así! ¡Vamos por el siguiente "reto"! ;)
