### ISSUE TITLE
Añadir cómo corregir el usuario que hace un commit a la wiki

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#287]
Añadir **al final** d[el apartado Configuración de la wiki](https://github.com/profeIAP/panelDeControl/wiki#configuraci%C3%B3n) cómo corregir el nombre del usuario que ha realizado el commit.

Para ello se incluirá [el siguiente comado](http://goo.gl/oSLR6u) con un ejemplo que lo ilustre.

**Comment by angelagr** [comment]
mira la wiki para ver si está bien

**Comment by profeIAP** [comment]
Está incompleto y no aparece el comando que sugiero en en la descripción de la tarea.

**Comment by angelagr** [comment]
he añadido más cosas

**Comment by profeIAP** [comment]
Bastante mejor pero:
1. Redacta el párrafo para que sea más coherente 
2. Crea un apartado para lo que estás expliando (no lo mezcles con el resto del contenido)

**Comment by angelagr** [comment]
Ya lo he corregido, espero que ya esté bien

**Comment by profeIAP** [comment]
No del todo (pero mejor que antes):
1. Para crear apartados se usa la almohadilla (en tu caso, nivel 3): "#"
2. Pon un ejemplo debajo explicando qué significa cada cosa (usando un enumerado, no lo pongas todo "junto" en una frase)
3. En lugar de _"Para ello incluímos el siguiente comando"_ quedaría mejor: _"y lanzamos el siguiente comando"_

**Comment by angelagr** [comment]
He añadido el ejemplo, dime si falta algo

**Comment by profeIAP** [comment]
Está bastante mejor, pero no bien (sorry):
1. Has utilizado "Título 1" para el apartado (cuando debería ser "Título 3" para que quede dentro del apdo. "Configuración")
2. Interesante ejemplo (¿de dónde lo has cogido Ángela?) No hace falta hablar del parámetro _rebase_: la idea es que cuentes cómo cambiar el autor del último commit con el comando que te pasé
3. No olvides utilizar algún usuario de gitHub (y su correo) en lugar de poner _Author Name email@address.com_

**Comment by angelagr** [comment]
Ya he cambiado el tipo de título, espero que ese sea el correcto. ¿Podría poner como usuario y correo el mío?

**Comment by profeIAP** [comment]
No te recomiendo usar tu correo y usuario... invéntalos (no hay problema).

El título ha dejado de serlo para pasar a volver a estar en negrita.

Aquí puedes consultar [cómo usar encabezados en MarkDown](https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html#Markdownsyntaxguide-Headings)

El ejemplo sigue estando igual.

**Comment by angelagr** [comment]
ya he cambiado el título, he puesto un correo y usuario. No sé que tengo que cambiar del ejemplo.

**Comment by profeIAP** [comment]
@angelagr 
1. El título debería ser 3 (y no 6)
2. Si miras el fragmento de código que proporcioné en la descripción de la tarea, la dirección de correo debe estar entre signos '<' y '>')
3. Quita todos los pasos del ejemplo.

Ánimo que esta tarea la terminas ya

**Comment by angelagr** [comment]
No sé a que tipo de título te refieres, la dirección del correo está entre '<' '>'. Los pasos del ejemplo ya los he eliminado.

**Comment by profeIAP** [comment]
Genial, el ejemplo realmente estaba "estorbando".

En MarkDown, el número de almohadillas ('#') que se colocan delante del texto indican la profundidad o nivel (dentro del esquema del documento) que ocupa dicho apartado.

En tu caso has puesto 6 almohadillas (título 6) cuando deberías haber usado 3 (título 3)

El correo sigue sin los signos de mayor y menor

![captura de pantalla de 2016-06-16 16 43 06](https://cloud.githubusercontent.com/assets/16881846/16120959/af267350-33e1-11e6-9e63-d7f8650b5260.png)

**Comment by angelagr** [comment]
Ya he corregido el título y le he puesto al correo los signos, espero que ya esté lista

**Comment by profeIAP** [comment]
@angelagr me podrías haber dicho que tenías problemas para poner los '<' y '>' (¡Con razón decías que los habías puesto! ... y yo no los veía XD; te lo he dejado arreglado porque la solución del espacio que metiste tampoco valía porque le daría problemas a los compañeros que usasen tu línea de código )

Perfecto, te he corregido (levemente) el párrafo y he añadido un enumerado que debes rellenar para dar por cerrada la tarea (poca cosa, no sufras)

**Comment by angelagr** [comment]
Espero que esté ya bien!!!!!!

**Comment by profeIAP** [comment]
Ahora sí, perfecto Ángela.
¡Buen trabajo!
