### ISSUE TITLE
Lanzar sql para la creación de tabla desde index.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#288]
El **objetivo** es:
1. Crear un método (p.e. _'/crearTabla'_) que nos permita lanzar cualquiera de las sql que tenemos en el directorio **model/scripts** y 
2. Asegurarnos que realmente se crea dicha tabla en la BD (bórrala primero y, tras lanzar el script debería volver a aparecer)

**Comment by j1m1** [comment]
~~Explicame~~ esto por favor

**Comment by profeIAP** [comment]
Comentado en clase.

**Comment by profeIAP** [comment]
Ha quedado perfecto Jesús, ¡Buen trabajo!
