### ISSUE TITLE
Generar gráficas

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#29]
Buscar y probar ejemplo que permita mostrar gráficas de distinto tipo (barras, puntos, sectores, ...) en base a los datos que se proporcionen

**Comment by profeIAP** [comment]
Incluye una gráfica de sectores abajo para que tengamos distintos modelos

**Comment by profeIAP** [comment]
Fantástico salvo porque he encontrado que **¡Hay dos <html> en la misma página!** (= aberración aberrante)

Aprovecha que te toca editarlo para **utilizar la plantilla layout.php** como base y que tus gráficas tengan la misma estética que el resto de contenidos de la web.

Aunque suena complejo, es tan sencillo como:
1. hacer una copia de cualquiera de los formularios que tenemos en la carpeta **/view**
2. renombrar a grafica.php
3. incluir en {% block cuerpo %} el código que has subido recientemente

**Comment by profeIAP** [comment]
Perfecto: ya tiene la estética "oficial"

Ahora sólo falta solucionar el uso de dos bloques `<html></html>` ¿no te parece?

**Comment by profeIAP** [comment]
Vale, has quitado los <html></html> pero sigue teniendo un monstruo "bicéfalo" al aparecer tanto dos <head> como dos <body> (por otra parte, totalmente innecesarios por estar usando layout.php (que ya los incluye)

**Comment by profeIAP** [comment]
Bastante, bastante mejor... pero requiere "afinar" la solución (siguen apareciendo, [etiquetas `<head>` dentro del cuerpo](https://github.com/profeIAP/panelDeControl/blob/18c400bfae922ea318de611d49c1e8c134a9a16a/view/grafica.php#L65) cual 'avestruz')

Recomiendo incluir todo el código `<script>` justo antes del `</body>` y organizar convenientemente el resto

**Comment by profeIAP** [comment]
Rocío, no veo el commit referenciado en la tarea y el código que tenemos en el repositorio parece el mismo de siempre (sigue incluyendo la etiqueta body y el código tal y como me lo enseñaste hoy)

**Comment by profeIAP** [comment]
Está perfecto... o casi: esta [línea](https://github.com/profeIAP/panelDeControl/blob/002ed2471f7d517e66c6d6b70fa20e95616532e6/view/grafica.php#L12) ya está incluida en layout.php.

¡Quítala de grafica.php! Su sitio es layout para que esté disponible en cualquier vista en la que deseemos mostrar un diagrama.

Enhorabuena Rocío, ha costado pero te ha quedado genial.

**Comment by rociomacho** [comment]
Ya he hecho los cambios. Espero que por fin esté a tu gusto.

**Comment by profeIAP** [comment]
No es cuestión de gustos (que esa faceta la tengo atrofiada) sino de corrección y eficiencia en la implementación :P

Ahora está estupendamente, ¡Excelente trabajo @rociomacho!
