### ISSUE TITLE
Documentar cómo gestionar capas en GIMP

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#290]
Crear documento compartido en Drive explicando cómo se unen capas en una sola imagen usando Gimp.

La idea es explicar: 
1. Cómo abrir un par de imágenes como capas
2. Colocarlas correctamente
3. Guardar la imagen resultante.

**Comment by angel2190** [comment]
te lo comparti a tu correo

**Comment by profeIAP** [comment]
Soy consciente pero, como llevo un tiempo comentado: llegan notificaciones cada vez que hacéis algún cambio por lo que se agradece comentario en las tareas cuando consideréis que está listo (así me evito tener que estar mirando trabajos sin terminar).

Ahora le echo un vistazo, gracias Ángel

**Comment by profeIAP** [comment]
Por cierto: **otro requisito habitual**: añade un enlace al documento compartido en el texto de alguno de tus comentarios para que resulte sencillo al que lo desee acceder a la documentación que has creado ;)

**Comment by profeIAP** [comment]
Visto y comentado... tenemos algo de "tajo" :)

**Comment by angel2190** [comment]
le he hecho algunos cambios como lo ves ahora?

**Comment by profeIAP** [comment]
No olvides incluir un enlace al documento compartido en alguno de los comentarios de esta tarea: es un requisito para poder darla por terminada.

**Comment by profeIAP** [comment]
Veo que sigue sin incluir [la plantilla de documentación](https://docs.google.com/document/d/1AChRiNlMCXpeF1mN9xyfI86J0ZBbho4q4BlitMat86g/edit)... opto por no seguir corrigiéndolo en dichas condiciones.

**Comment by angel2190** [comment]
listo 
[https://docs.google.com/document/d/1DZI_6CHWgkAJkGUlnB3M6701RRBDu6Abe8mhdo3YaHY/edit](url)

**Comment by profeIAP** [comment]
Recuerda que **es un requisito** ocultar los enlaces en los comentarios ;)

Por cierto, el enlace proporcionado en el comentario anterior no es correcto

**Comment by profeIAP** [comment]
El documento no es lo pedido... la idea es más sencilla, limítate a explicar lo que se indica en la descripción inicial de la tarea
