### ISSUE TITLE
Generar datos ficticios ALUMNO/A

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#301]
Utilizando la función _[concatenate()](https://docs.google.com/document/d/10Z09UTJnhUuhDhDViEVN3a61f32BK23Op_mGFb6hlA0/edit?usp=sharing)_  de Google Sheets simular los valores de la columna indicada en el fichero compartido de Google Drive que simula [los datos almacenados en Séneca](https://docs.google.com/a/iesalandalus.com/spreadsheets/d/1CsNShEVyfDip4OP3Gcjb6eav3yti0WUMRaPbXHD8yic/edit?usp=sharing).

Deberá concatenarse el contenido de las columnas NOMBRE (tarea #300), PRIMER APELLIDO (tarea #298) y SEGUNDO APELLIDO (tarea #299) generado en las tareas correspondientes.

De especial utilidad pueden resultar los documentos generados en las tareas #38 y #61 al incluir ejemplos de uso.

**Comment by j1m1** [comment]
O yo soy muy torpe... o no sé, pero yo esto no lo entiendo. ¿Me lo explicas?

**Comment by profeIAP** [comment]
Por supuesto que te lo explico: la idea es generar un nombre completo (nombre y dos apellidos) uniendo (función concatenate) los valores que ya deberían existir (los creará otro, si no están puedes ponerlos a mano) en las columnas NOMBRE, PRIMER APELLIDO y SEGUNDO APELLIDO.

¿Lo he aclarado u "oscurecido"? ;)

**Comment by profeIAP** [comment]
Perfecto, Rubén
Simplemente, espectacular
![image](https://user-images.githubusercontent.com/16881846/59438129-2d69f980-8df3-11e9-8cf9-9299d4875749.png)
