### ISSUE TITLE
Documentar cómo compartir una foto con Google Drive desde el móvil

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#307]
Crear [documento compartido en Google Drive](https://drive.google.com/open?id=18mX5JQv8roYLbaGkhIa6BZsguqG5erywjSkKBQ_140A) explicando cómo subir una fotografía realizada con el móvil directamente a Google Drive utilizando la opción compartir de Android.

**Comment by j1m1** [comment]
Mmm... esto no es muy sencillo?

**Comment by profeIAP** [comment]
No diré que sea complicado 
pero me parece sensato
que seas desconfiado.

**NOTA:** Sabes que soy exigente con los trabajos entregados, no vale cualquier "papelote", de ahí que esté etiquetado como reto ;)

**Comment by j1m1** [comment]
Puede que la complicación esté en la explicación y expresión mía en este caso, pero me refiero a que el contenido es muy escaso, ¿no crees? Porque desde mi móvil sólo hay que "cliquear" unas tres veces.

**Comment by j1m1** [comment]
Por cierto, ¿el documento lo debo crear yo y compartir con la clase?

**Comment by profeIAP** [comment]
Efectivamente, trabajar esa expresión es uno de los objetivos ;)

**Comment by j1m1** [comment]
Por lo que he entendido, ya está terminada. Y compartida con todos los miembros de esta asignatura !

**Comment by profeIAP** [comment]
Echo de menos un enlace al documento compartido en alguno de los comentarios de esta tarea ;)

**Comment by profeIAP** [comment]
Respecto al documento:
1. No usa la plantilla de documentación que tenemos.
2. No hay capturas de pantalla que ilustren el proceso

Ves como al final no era tan sencillo como creías ;)

**Comment by j1m1** [comment]
[url=https://drive.google.com/open?id=1aI2ddO71sgY96X2fBnYNhiA3C2XHPo1tKwVBl3iOanM] He insertado imágenes{url/]

**Comment by j1m1** [comment]
Creo que ya..

**Comment by profeIAP** [comment]
Está mucho mejor pero sigues sin utilizar la plantilla oficial.

Recuerda ocultar el enlace, Jesús...

**Comment by j1m1** [comment]
¿Cuál es la plantilla oficial? Ups... se me ha escapado !

**Comment by profeIAP** [comment]
La tenemos en la carpeta de documentación... por tratarse de ud., [aquí la tiene](https://drive.google.com/open?id=18mX5JQv8roYLbaGkhIa6BZsguqG5erywjSkKBQ_140A)

**Comment by j1m1** [comment]
[](https://drive.google.com/open?id=1aI2ddO71sgY96X2fBnYNhiA3C2XHPo1tKwVBl3iOanM)

**Comment by j1m1** [comment]
[Finalizado](https://drive.google.com/open?id=1aI2ddO71sgY96X2fBnYNhiA3C2XHPo1tKwVBl3iOanM)

**Comment by j1m1** [comment]
[Ahora sí](https://drive.google.com/open?id=18mX5JQv8roYLbaGkhIa6BZsguqG5erywjSkKBQ_140A)

**Comment by profeIAP** [comment]
Ahora no... por cierto, no hace falta que incluyas enlace cada vez que pongas un comentario ;)

**Comment by j1m1** [comment]
Echa el ojillo por mi documento y verás como te gusta !

**Comment by profeIAP** [comment]
Gustar me gusta pero está muy "desordenado" :P

Has ignorado el crear apartados dentro del documento, Jesús.

**Comment by j1m1** [comment]
[Ya está en el documento oficial, y creo que no me falta nada](https://drive.google.com/open?id=18mX5JQv8roYLbaGkhIa6BZsguqG5erywjSkKBQ_140A)

**Comment by profeIAP** [comment]
Di que sí Jesús, que te ha quedado espectacular.
¡Muy buen trabajo!
