### ISSUE TITLE
Documentar cómo cerrar sesiones de Google que se queden abiertas en otro equipo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#308]
Crear [documento compartido en Drive](https://docs.google.com/document/d/1GLZACOd8BuOceTEW4sf4vRGp3ozUKKG_boob3mwDsNg/edit#) explicando cómo cerrar sesiones de Google que se nos hayan quedado abiertas en algún equipo (imagina que se te agota la batería o que cuando llegas a casa te surge la duda si la cerraste)

**Comment by ghost** [comment]
Acabo de terminarlo. Se me olvidó dejarte el enlace del documento al compartírtelo en Google Drive, te lo dejo aquí: [Google Drive](https://docs.google.com/document/d/1GLZACOd8BuOceTEW4sf4vRGp3ozUKKG_boob3mwDsNg/edit#)

**Comment by profeIAP** [comment]
Oculta el enlace en el comentario anterior.

Te dejo algunos comentarios en el documento.

**Comment by ghost** [comment]
Ya están corregidos los comentarios y he ocultado el enlace del comentario anterior ;)

**Comment by profeIAP** [comment]
Perfecto a falta de que aceptes las sugerencias (y/o las mejores)

Sigo pensando que no es buena idea utilizar el "enturbiado" de la imagen (marea)

**Comment by ghost** [comment]
He puesto el efecto "enturbiado" porque en la imagen aparece la IP de mi ordenador de casa, la de mi móvil, etc y no quiero que se pueda distinguir en la imagen aunque sea un poco... Lo que puedo hacer si te parece bien es recortar la imagen más y dejar solo lo que he puesto para que quede más destacado y así ya no se vería el resto de información.

**Comment by profeIAP** [comment]
Me parece bien, otro efecto (que suelo utilizar cuando aparecen datos privados) que te podría servir es el de pixelar.

![captura de pantalla de 2016-06-16 16 40 50](https://cloud.githubusercontent.com/assets/16881846/16120836/3f3a229e-33e1-11e6-8ae3-5462679fc575.png)

La solución de recortar me parece acertada, Francisco

**Comment by ghost** [comment]
Listo acabo de recortar las imágenes ;)
**PD:** muchas gracias por el consejo, lo tendré en cuenta para la próxima vez jeje.

**Comment by profeIAP** [comment]
Ha quedado genial, ¡buen trabajo Francisco! (parece de verdad y todo ;) )
