### ISSUE TITLE
Estudiar el uso de phpUnit

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#31]
Instalar y probar el uso de phpUnit

**Comment by profeIAP** [comment]
Elaborar una pequeña prueba de uso

**Comment by julioosos** [comment]
No se puede debido a que requiere el php 5.6 y el que nosotros tenemos es el php 5.5

**Comment by profeIAP** [comment]
Busca versión anterior de phpUnit que funcione con php 5.5.

**Comment by julioosos** [comment]
Ya ha sido testeado por mi y está perfecto; con esto finalizo la tarea

**Comment by profeIAP** [comment]
Pero no has aportado la pequeña prueba de uso que te indico en uno de los primeros comentarios ¿no te parece?

Abro nuevamente la tarea.

**Comment by julioosos** [comment]
vale

**Comment by julioosos** [comment]
Ya está terminada
