### ISSUE TITLE
Revisar que tienen nombre todos los checks de view/parte.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#317]
Revisar el código del formulario parte comprobando que todos tienen el campo _name_
![2018-11-22_16-03](https://user-images.githubusercontent.com/16881846/48910452-49ff0e00-ee70-11e8-9554-85c541fc3b31.png)
y su valor coincide con el esperado en la base de datos
![2018-11-22_16-05](https://user-images.githubusercontent.com/16881846/48910522-761a8f00-ee70-11e8-8719-d4bc7505cd28.png)

**Comment by sergioreina2002** [comment]
@adrivel, estos campos faltan:
G_FUMAR
L_USAR GORRAS, GAFAS DE SOL O REPROD. DE MÚSICA EN CLASE

**Comment by profeIAP** [comment]
Buen trabajo Sergio
@adrivel, no olvides crear tarea para añadir los campos indicados por Sergio a la BD
