### ISSUE TITLE
Bloquear campo tutor/a en view/parte.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#318]
Modificar el formulario de partes para que el campo _Tutor/a_ aparezca sombreado como ocurre (por poner algunos ejemplos) con _Curso y Grupo_ o _Profesor/a_
![2018-11-22_16-09](https://user-images.githubusercontent.com/16881846/48910771-14a6f000-ee71-11e8-8120-11cfc0d9edf6.png)

**Comment by adrivel** [comment]
@maricarmengarcia está correcto :+1:
