### ISSUE TITLE
Documentar el uso de phpUnit

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#32]
Crear [documento compartido en Google Drive](https://docs.google.com/document/d/1a65nPt9saHhvfkBgZMiJtCvipIIHFoMEY7hkqYkVQOk/edit?usp=sharing) que permita a otros instalar y usar los tests de prueba.
Realizar en colaboración con la persona encargada de estudiar su uso (ver #31)

**Comment by profeIAP** [comment]
Aquí tienes [el ppa para php 5.6](https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6)

**Comment by JVG13** [comment]
Parece ser que ya no hay más errores en el documento de Php, cierro la tarea

**Comment by profeIAP** [comment]
Me alegra que al final olvidases cerrar la tarea... te he dejado comentarios

**Comment by profeIAP** [comment]
Bastante mejor...

**Comment by JVG13** [comment]
Ya he corregido los últimos errores que vistes, excepto el de explicar como sabemos si se ha instalado bien PhpUnit que la asignarías como una nueva tarea. Cierro la tarea

**Comment by profeIAP** [comment]
El jaleo que nos está dando esta tarea Jesús... desgraciadamente, añado nuevas anotaciones.
Gracias por recordarme que cree la tarea.

**Comment by profeIAP** [comment]
Creo la tarea #260 para explicar la comprobación de phpUnit

**Comment by JVG13** [comment]
A ver ahora...

**Comment by profeIAP** [comment]
Te lo he reeditado para que te resulte más sencillo terminar finalmente la tarea. 
Presta especial atención a los comentarios pues faltan un par de datos que deberás incluir
Ánimo Jesús

**Comment by JVG13** [comment]
miralo cuando tengas tiempo, por favor

**Comment by profeIAP** [comment]
Te lo he pulido (para acabar esta tarea de una vez) pero queda una anotación sobre la imagen que has cambiado de composer.json

**Comment by JVG13** [comment]
Listo lo de la imagen

**Comment by profeIAP** [comment]
No te lo vas a creer pero está perfecta.

Grandísimo trabajo Jesús ¡enhorabuena! (tanto es así que considero justo etiquetar la tarea como "reto" para compensar el esfuerzo)

Muchas gracias y enhorabuena una vez más.
