### ISSUE TITLE
Crear método GET:/usuarios/recuperar

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#323]
Cuya implementación únicamente se encargue de [anotar en el log](https://github.com/profeIAP/panelDeControl/blob/0df92c99045e96b399a9b87c1b77fa92a49e09b9/index.php#L709) el mensaje "Debemos implementar cómo recuperar la contraseña de un usuario"

**Comment by adrivel** [comment]
@antoniovalle14 Genial, aunque estaría mejor si utilizaras los tabuladores (es solo para que se vea más bonito) pero la tarea está hecha :+1:

**Comment by profeIAP** [comment]
Muy bien a los dos: a @antoniovalle14 por realizar (y subir) correctamente su primera tarea y a @adrivel por las recomendaciones que ayuden a mejorar al equipo

Buen trabajo, chicos 👍
