### ISSUE TITLE
Campos requeridos en el formulario del login

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#328]
Modificar [el formulario que nos permite iniciar sesión ](https://github.com/profeIAP/panelDeControl/blob/47592b0013d21e27a974e391118ceb8bb6237711/view/login.php#L17) para que los campos "nombre" y "clave" sean obligatorios rellenar.

**Comment by profeIAP** [comment]
Con tu permiso asigno esta tarea al milestone 0.2 (es el que se parece algo más)
Muy buena observación, Adrián 👍

**Comment by profeIAP** [comment]
Está perfecto, buen trabajo Juan 👍
