### ISSUE TITLE
Cambiar el campo "Hora" de /view/anotacion.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#329]
Cambiar el campo de "Hora" por un select en [/view/anotacion.php](https://github.com/profeIAP/panelDeControl/blob/6f6b33a6dc239bbf65046dc027363e3af2295a25/view/anotacion.php#L29), de manera que se pueda elegir la hora tal y como se hace en [/view/parte.php](https://github.com/profeIAP/panelDeControl/blob/6f6b33a6dc239bbf65046dc027363e3af2295a25/view/parte.php#L31).

**Comment by profeIAP** [comment]
@antoniovalle14 lo has hecho rápido y bien... hoy me estás sorprendiendo (enhorabuena) por lo pronto que parece que les estás cogiendo el "truco" tanto a GIT como a la programación 👍

Sólo has cometido un pequeño fallo: observa que se ha descolocado el formulario 
![captura](https://user-images.githubusercontent.com/16881846/51536191-0b270d80-1e4b-11e9-806b-f94f51dedb21.png)

Es debido al [uso de Boostrap CSS Grid](https://getbootstrap.com/docs/3.3/css/#grid-options) pero prefiero contártelo el próximo día en clase. Vente y hablamos 👍

**Comment by profeIAP** [comment]
Creo que esto se nos está complicando 😅
Pide cita en la próxima clase y te explico cómo funciona Boostrap para que pueda quedar el formulario como aparece en la siguiente imagen
![image](https://user-images.githubusercontent.com/16881846/52330755-7ac5fc80-29f6-11e9-81c6-422fb2bb0855.png)

**Comment by profeIAP** [comment]
Genial Antonio, un gran trabajo. Gracias

![image](https://user-images.githubusercontent.com/16881846/52632871-017d4c80-2ec3-11e9-85b6-68d64d9b59a9.png)
