### ISSUE TITLE
Cambiar el campo "Fecha" de /view/anotacion.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#330]
Cambiar el campo "Fecha" de [/view/anotacion.php](https://github.com/profeIAP/panelDeControl/blob/6f6b33a6dc239bbf65046dc027363e3af2295a25/view/anotacion.php#L33) actual por el de [/view/parte.php](https://github.com/profeIAP/panelDeControl/blob/6f6b33a6dc239bbf65046dc027363e3af2295a25/view/parte.php#L24), para dar la posibilidad de seleccionar la fecha.

**[!]** No funcionará si no se ha completado la tarea #332

**Comment by profeIAP** [comment]
Genial Antonio, funciona perfectamente.
Gracias
