### ISSUE TITLE
Funcionamiento del campo "Fecha" de /view/anotacion.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#332]
Una vez completada la tarea #330 solo necesitaremos darle funcionalidad. Para ello, deberemos traer el script de [/view/parte.php](https://github.com/profeIAP/panelDeControl/blob/6f6b33a6dc239bbf65046dc027363e3af2295a25/view/parte.php#L156-L190) a /view/anotacion.php

**Comment by profeIAP** [comment]
Genial, Antonio 👍
