### ISSUE TITLE
Fecha automática para el campo "Fecha" de /view/anotacion.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#333]
Para que en el campo "Fecha" aparezca la fecha de hoy automáticamente, deberemos de incluir la variable $valores tal y como ya se hace para [partes -> crear](https://github.com/profeIAP/panelDeControl/blob/98a63926478649450a4b4fae5066a78049c5cc26/index.php#L421).

**Comment by profeIAP** [comment]
@adrivel, sería interesante:
1. marcar en qué línea de index.php debe hacerse 
1. indicar la complejidad
1. usar la etiqueta vista, modelo o controlador (en lugar de _programación_ que está "obsoleta")
1. asociar la tarea a un milestone

**Comment by profeIAP** [comment]
Ha quedado genial Juan Diego, gracias 👍
![image](https://user-images.githubusercontent.com/16881846/52869936-0b16e680-3147-11e9-8992-7bd88b14ad0e.png)
