### ISSUE TITLE
Proteger urls en /view/partes.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#336]
Con una implementación similar a la #334 deberás modificar el listado de partes para que se protejan las urls que permiten:
1. [Eliminar](https://github.com/profeIAP/panelDeControl/blob/cee274c64bd3708600003e38f864b9bfe8f8ddbd/view/partes.php#L26) un parte
1. [Editar](https://github.com/profeIAP/panelDeControl/blob/cee274c64bd3708600003e38f864b9bfe8f8ddbd/view/partes.php#L27) un parte

**Comment by Juanzdy** [comment]
Listo

**Comment by profeIAP** [comment]
Y además, de verdad
Gracias Juan Diego 👍

![image](https://user-images.githubusercontent.com/16881846/52625501-6d56b980-2eb1-11e9-9981-0909c0c88a8a.png)
