### ISSUE TITLE
Crear tabla en /view/partes.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#339]
Adaptar la tabla de [/view/usuarios.php](https://github.com/profeIAP/panelDeControl/blob/ba25cdd089f3c352b95ea0e6902c6cb847d572e5/view/usuarios.php#L19-L42) para listar partes en /view/partes.php

**Comment by profeIAP** [comment]
Perfecto tras el commit a7e8e6dbc8ced622e922a0d34d5af9242719909c de Rubén.
