### ISSUE TITLE
Listar resumen partes leves por tipo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#34]
Obtener de la BD el número de cada uno de los partes de tipo leve (Perturbar el desarrollo de las clases, Faltar a clase injustificadamente, ...) existentes

**Comment by profeIAP** [comment]
Depende de la tabla Partes de la tarea #2

**Comment by profeIAP** [comment]
Tenemos que hablar para definir la información que se mostrará en pantalla

**Comment by Rafaelcraftero** [comment]
Terminada

**Comment by profeIAP** [comment]
Rafael, no veo la vista que estabas creando ni en la BD ni en la carpeta de scripts ¿?

Igualmente veo en el commit que has creado algunas vistas (no eran necesarias aunque se agradecen) que no son invocadas (y por tanto no son utilizadas) desde la web.

Si te parece hablamos el próximo día y/o corriges lo que consideres oportuno.

Gracias Rafa

**Comment by profeIAP** [comment]
Recuerda usar _git rm FICHERO_
Crea una vista para tu consulta usando [las instrucciones que tenemos en Drive](https://docs.google.com/a/iesalandalus.com/document/d/1vwjKLieWg3o0dao3fAU072zPCYhkYTxzol-xzbjXkTw/edit?usp=sharing)

**Comment by profeIAP** [comment]
Llamaremos a la vista **resumenPartesLeves**

**Comment by profeIAP** [comment]
Espectacular D. Rafael, realmente puede sentirse orgulloso (como así estaba esta mañana en clase) del trabajo realizado.

¡Buen trabajo!
