### ISSUE TITLE
Crear método Usuario::existe($email)

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#340]
Antes de poder recuperar la contraseña, necesitaremos comprobar que el email introducido corresponde a un usuario registrado. Para ello, necesitamos crear el método Usuario::existe($email) en /controller/Usuario.php ([puedes ayudarte de esta tarea de RetA2](https://github.com/andalusIES/retados/issues/478))

**Comment by profeIAP** [comment]
El código que necesitas [está aquí](https://github.com/andalusIES/retados/blob/c7976619dc35b7063d0b84506ee6567f69d52fdb/controller/Usuario.php#L61-L63)

**Comment by profeIAP** [comment]
Genial Esther, buen trabajo y, encima, eres la experta en Git del grupo 😉👍
