### ISSUE TITLE
Traer el archivo jquery.tablesorter.js

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#342]
Traer el archivo jquery.tablesorter.js de Retados a nuestro proyecto (lo podrás encontrar en la carpeta /js/tablesorter-master/). El archivo deberá de estar en la carpeta /js/.

**Comment by profeIAP** [comment]
Está perfecto @maricarmengarcia salvo porque has usado la extensión _.txt_ (en lugar de la habitual que es _.js_ para los ficheros **J**ava**S**cript)

Aplica ese pequeño cambio y podremos dar por cerrada la tarea 👍

**Comment by profeIAP** [comment]
Genial MC
Buen trabajo, gracias 👍
