### ISSUE TITLE
Incluir jquery.tablesorter.js en nuestro proyecto

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#343]
Una vez completada la tarea #342, debemos incluir el script en el proyecto. Incluirlo en el archivo layout.php con la etiqueta <script></script>

**Comment by profeIAP** [comment]
Qué coraje @isabelop, el nombre del fichero no está bien escrito
![image](https://user-images.githubusercontent.com/16881846/52633035-7c466780-2ec3-11e9-9f48-ed50f965f0e9.png)

**Comment by profeIAP** [comment]
Ahora sí, perfecto Isa
Gracias 👍

![image](https://user-images.githubusercontent.com/16881846/52633783-bd3f7b80-2ec5-11e9-8eec-b9e7e19da37e.png)
