### ISSUE TITLE
CSS para ordenar tablas

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#344]
Crear la hoja de estilos /css/**tablasorter.css** donde se deberá de incluir el contenido de la etiqueta <style></style> que se añadió [en este commit de Retados](https://github.com/andalusIES/retados/blob/7ea7379dd1e2a7eb549a99df8d68f6bfa9d82177/view/preguntas.php#L62-L78).

**Comment by profeIAP** [comment]
Creo que @marialop7 ha confundido el número de tarea al subir la suya XD

**Comment by profeIAP** [comment]
Antonio, sobra [este fragmento de código](https://github.com/profeIAP/panelDeControl/blob/9c463019dd3a7283fd118f8e95434b70356bc7c9/css/tablasorter.css#L1-L5) por no tratarse de código CSS (sino HTML que se nos ha colado) y otro trozo que te he comentado directamente en el propio código del commit (seguramente te habrán llegado emails con notificaciones)

**Comment by profeIAP** [comment]
Genial, ahora sí.
Hoy has estado en "racha" finalizando tareas, buen trabajo Antonio 👍

**Comment by rociodanone3** [comment]
Sácame de aquí!!!! Jajaja

**Comment by profeIAP** [comment]
Me gustaría pero está en tus manos el poder salir, Rocío
Aquí tienes [cómo evitar las notificaciones](https://drive.google.com/file/d/0B42JQKLr8bXaa1NLUlhkZTJpS3M/view), regalo de nuestro amigo Alejandro ;)
