### ISSUE TITLE
Incluir el CSS de ordenar tablas en nuestro proyecto

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#345]
Una vez completada la tarea #344, incluir la hoja de estilo en nuestro proyecto. La podemos incluir en layout.php utilizando la etiqueta < link>.

**Comment by profeIAP** [comment]
En realidad María ha cerrado esta tarea con el commit 067ec55

**Comment by profeIAP** [comment]
Buen trabajo 👍
