### ISSUE TITLE
Ordenar tabla de /view/usuarios.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#346]
Para que se pueda ordenar las filas de la tabla de usuarios, debemos incluir [este script](https://github.com/andalusIES/retados/commit/7ea7379dd1e2a7eb549a99df8d68f6bfa9d82177#diff-f61ab9f3b1a4ba29b7c21ff44637fb7dR81) en el archivo usuarios.php.

**¡!** Ten en cuenta que la id de la tabla debe de coincidir con la que está en el script.

**Comment by profeIAP** [comment]
Perfecto Alba, buen trabajo 👍

**Comment by profeIAP** [comment]
Perfecto Antonio, buen trabajo 👍
