### ISSUE TITLE
Modificar consulta de listar partes

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#348]
Modificar [esta consulta](https://github.com/profeIAP/panelDeControl/blob/3471d982cd2d3d5b4692518ce15ee43e98ee9fc0/index.php#L381) para que en la tabla de /view/partes.php solo aparezca la siguiente información:

- ID
- ID_ALUMNO
- GRUPO
- FECHA
- HORA
- ASIGNATURA
- PROFESOR

**Pista:** _SELECT columna, columnb FROM mytable_

**Comment by profeIAP** [comment]
Adrián, yo optaría por crear una vista en lugar de colocar en `index.php` una consulta que, irremediablemente, va a crecer conforme evolucionen nuestras necesidades.

Igualmente, ten en cuenta que va a tener más de una decodificación (alumno, profesor, asignatura, ...) que hará que la consulta crezca tanto que resulte ilegible dentro de `index.php`

**Comment by profeIAP** [comment]
Perfecto María, muy buen trabajo 👍
