### ISSUE TITLE
Crear tabla en /view/partes.php y que se pueda ordenar

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#349]
Implementar una tabla en /view/partes.php que liste los partes y, además, se pueda ordenar.

**Comment by profeIAP** [comment]
Ha queda bastante bien Juan salvo porque:

1. Las urls usan `../usurios/..` en lugar de `../partes/..`
2. Ha quedado un resto de tabla antes del _jumbotron_
3. Falta la cabecera ACCIONES sobre los botones de borrar y editar

![image](https://user-images.githubusercontent.com/16881846/53286085-55acea00-3769-11e9-9766-b8e3581b150c.png)

**Comment by profeIAP** [comment]
Perfecto, Juan
