### ISSUE TITLE
Listar resumen partes graves por tipo

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#35]
Obtener de la BD el número de cada uno de los partes de tipo **grave** (Agresión física, Amenaza o coacción, ...) existentes

**Comment by alexrueda7** [comment]
Ya esta terminada, el unico problema es el que daba error en G_AGRESION.

**Comment by profeIAP** [comment]
Para dar por finalizada la tarea debe:
1. modificarse la BD (model/dictados.db)
2. incluirse el script que genera la vista en model/scripts

**Comment by alexrueda7** [comment]
Ya esta terminada

**Comment by profeIAP** [comment]
Alejandro, la BD está perfectamente subida (incluye la vista). 
No obstante el contenido del fichero model/scripts/view_resumenpartesgraves.sql no es el esperado (contiene una select en lugar del "create view")

**Comment by alexrueda7** [comment]
Ya esta terminada

**Comment by profeIAP** [comment]
Genial Alejandro, simplemente genial.

La vista nos va a venir de lujo, ¡gracias!
