### ISSUE TITLE
Eliminar listados antiguos de /view/partes.php y /view/usuarios.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#352]
Como hemos insertado las nuevas tablas, ya no necesitaremos el antiguo listado de partes y de usuarios.

**Comment by profeIAP** [comment]
@adrivel yo dividiría esta tarea en 2 (una para _/view/partes.php_ y otra para _/view/usuarios.php_)
@isabelop quédate con la que te "apetezca" 👍

**Comment by profeIAP** [comment]
Aunque ha costado prácticamente nada implementar esta tarea 😏
podemos darla por buena 😉

**Comment by profeIAP** [comment]
Perfecto Juan 👍
