### ISSUE TITLE
Crear tabla "grupos"

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#354]
Crear una tabla llamada "grupos" con los siguientes campos:

- ID (tipo: PK Autoincrement)
- NOMBRE (tipo: text)
- ACTIVO (tipo: text, valor predeterminado: true)

**Comment by profeIAP** [comment]
Igual la próxima vez, te resulta más cómodo hacer una captura de pantalla del resultado de SQLiteman

![image](https://user-images.githubusercontent.com/16881846/52869775-b1aeb780-3146-11e9-8d9f-ef6dfbf8826f.png)

**Comment by profeIAP** [comment]
@adrivel, esta tarea me plantearía dejarla (y sus equivalentes) como forma de tener una tabla donde "cargar" con los datos del curso escolar.

Recuerda que, con cada carga inicial de datos, vamos a limpiar estas tablas y volcar todos los datos nuevos a utilizar en los partes.
