### ISSUE TITLE
Modificar tabla "partes"

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#355]
En la tabla partes, modificar el nombre de los siguientes campos:

- GRUPO -> ID_GRUPO
- ASIGNATURA -> ID_ASIGNATURA
- PROFESOR -> ID_PROFESOR

Además, el tipo de campo deberá cambiarse a INTEGER.

**Comment by profeIAP** [comment]
@Estherr13 se está encargando, en la tarea #350 de cambiar a INTEGER los campos 😉
