### ISSUE TITLE
Modificar consulta de listar usuarios

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#356]
Quitar del SELECT de [esta consulta](https://github.com/profeIAP/panelDeControl/blob/3877dc24216fdb8b203e98e60ea0eaada76603d0/index.php#L436) el campo "clave", e incluir el campo "rol".

**Comment by profeIAP** [comment]
Muy buena idea Adrián, me encanta 👍

**Comment by profeIAP** [comment]
Añado comentario sobre el propio commit

**Comment by profeIAP** [comment]
Buen trabajo Juanry 👍

**Comment by profeIAP** [comment]
Abro la tarea porque @juanry parece que se ha confundido de número de tarea y ha cerrado la de @antoniovalle14 😱

**Comment by profeIAP** [comment]
Ahora sí, perfecto Antonio
Muy buen trabajo 👍
