### ISSUE TITLE
Campo obligatorio en /view/parte.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#358]
Hacer que el campo con id "alumnoaImplicado" sea obligatorio de rellenar.

**Comment by profeIAP** [comment]
Genial Antonio, muy buen trabajo; sólo espero que @sergiocabezas (cuando termine de añadir todos los motivos de parte) gestione bien la "colisión" que le va a provocar el "merge automático" y no se pierda el cambio 😉👍
