### ISSUE TITLE
Listar partes por alumno

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#36]
Listar los partes puestos a un alumno concreto (por ID)
**OJO** Debe realizarse dentro del formulario de edición de un alumno

**Comment by j1m1** [comment]
No entiendo dónde debo realizar esta tarea. ¿En una tabla en SQLiteman?

**Comment by jasvazquez** [comment]
No, es un listado como el que tenemos actualmente en [_/comentarios_](https://github.com/profeIAP/proyecto2015-16/blob/f816d3e6043221e3438bb94d4fd21588c3cec3ab/index.php#L73-L82) pero debe recibir como parámetro el ID de un alumno concreto.

No se muestran todos los partes, sólo aquellos que tengan el campo ID_ALUMNO igual al indicado en el parámetro

**Comment by profeIAP** [comment]
Así leemos [el ID del alumno](https://github.com/profeIAP/proyecto2015-16/blob/f816d3e6043221e3438bb94d4fd21588c3cec3ab/index.php#L124-L126) que nos interesa

**Comment by profeIAP** [comment]
Y aquí puedes ver cómo lanzar un [select con un parámetro](https://github.com/profeIAP/panelDeControl/blob/f816d3e6043221e3438bb94d4fd21588c3cec3ab/index.php#L129-L131)

**Comment by j1m1** [comment]
Ya...

**Comment by profeIAP** [comment]
Está bastante, bastante bien pero:
1. Deberías colocar el código en **/partes**/buscar/poralumno (en lugar del actual **/alumnos**/buscar/poralumno)
2. Como se va a reutilizar la vista **/view/partes.php** envía los resultados de lanzar la consulta en la variable **comentarios** (en lugar de la actual **partes**). Estoy contigo que es más coherente hacerlo así pero dejaremos para una posterior tarea cambiar el nombre de la variable en todos los sitios en los que se llama a **/view/partes.php**
3. Agradecería que el parámetro que se envía a /partes/buscar/poralumno fuese ID en lugar de ID_ALUMNO (resulta más cómodo y no muestra detalles innecesarios del almacenamiento en la BD)

Aunque parece mucho lo que pongo está realmente bien el trabajo que has hecho Jesús... puedes estar orgulloso ;)

**Comment by profeIAP** [comment]
Buscando el origen de un problema encuentro que en tu merge no has tenido todo el cuidado que hubiese sido deseable (*_probad la web antes de hacer un git push *_) y has echado por tierra parte de la tarea #166 de @angel2190. 

![captura de pantalla de 2016-05-24 16 06 59](https://cloud.githubusercontent.com/assets/16881846/15506889/96d3711a-21c9-11e6-9329-d1f8e6c21434.png)

Se observa:
1. Ha vuelto a desaparecer el PANEL DE CONTROL de la parte superior (resuelto en su momento por @carlosaj98 )
2. Vuelven a descargarse [ficheros CSS de la web](https://github.com/profeIAP/panelDeControl/commit/f5e74a084183154ef669357de11a62a42f96305d#diff-52ef2a346517f81837f6e60c88126a1aL14) (en lugar de utilizar las copias locales de @angel2190 )

Para dar por cerrada la tarea tendrás:
1. Resolver lo que te indico en el comentario de arriba
2. Arreglar el "estropicio"

**Comment by j1m1** [comment]
Mirala de nuevo

**Comment by profeIAP** [comment]
Has arreglado los problemas indicados pero parece que no termina de funcionar bien

![captura de pantalla de 2016-05-27 16 58 37](https://cloud.githubusercontent.com/assets/16881846/15611804/5341bb90-242c-11e6-9d6f-60419778a134.png)

Observa que está intentando renderizar **comentarios.php** (en lugar de **partes.php**)

**Comment by profeIAP** [comment]
Por cierto, por "homogeneidad" pasa el atributo ID a minúscula

La invocación correcta [debería ser del siguiente modo](http://localhost:9000/partes/buscar/poralumno?id=1844851086):

> http://localhost:9000/partes/buscar/poralumno?**id=**NNN

**Comment by j1m1** [comment]
creo que ya "_"

**Comment by profeIAP** [comment]
Esta casi perfecta Jesús (muy buen trabajo)

Te falta el punto 2 para que aparezcan listados los partes en pantalla

**Comment by j1m1** [comment]
Corrige mi commit que ayer se te pasó, y quiero verla ya cerrada ("_")

**Comment by j1m1** [comment]
Corrige mi commit que ayer se te pasó, y quiero verla ya cerrada ("_")

**Comment by profeIAP** [comment]
No se me pasó... no comentaste nada en la tarea (ni la cerraste) y por ello no pasé a revisarlo ;P

**Comment by profeIAP** [comment]
Has corregido el nombre de la variable pero observa que no devuelve ningún parte cuando se intenta filtrar por alumno... personalmente revisaría la SQL que estás lanzando (aunque suene raro, que suena, puede deberse al uso incorrecto de minúsculas en los nombres de las columnas)

**Comment by j1m1** [comment]
FUNCIONA JEFE !

**Comment by profeIAP** [comment]
Espectacular Jesús, espectacular... ganitas tenía de verlo funcionando ¡**Enhorabuena** "monstruo"!
