### ISSUE TITLE
Crear clase Registro

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#365]
Crear archivo en la carpeta controller y que se llame Registro.php

En él se deberá de copiar [la clase Registro que ya está en Reta2](https://github.com/andalusIES/retados/blob/master/controller/Registro.php).

**Comment by profeIAP** [comment]
@adrivel ¿acordamos finalmente que se importaría el código de la clase Registro.php que tenemos en Ret{A2}?

**Comment by profeIAP** [comment]
Perfecto, buen trabajo María
