### ISSUE TITLE
Crear tabla t_rol

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#367]
Crear una tabla llamada que contenga los siguientes campos:

- ID (tipo: PK Autoincrement
- ROL (tipo: Text)

**Comment by profeIAP** [comment]
Yo pondría las siguientes columnas:

+ ID (tipo: PK Autoincrement
+ **NOMBRE** (tipo: Text)

Obsérvese que he cambiado el nombre de la columna ROL -> NOMBRE

**Comment by profeIAP** [comment]
Perfecto Sergio, buen trabajo 👍
