### ISSUE TITLE
Generar datos ficticios partes

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#37]
Compartir [hoja de cálculo en Drive](https://docs.google.com/spreadsheets/d/1j1he7cnr2ffUScyKRKwXC16PNKSMm5hVVguPHRv_yHw/edit#gid=0) que simule los datos que debe incluir la tabla Partes (ver #2)

**Comment by profeIAP** [comment]
No se busca introducir un listado (más o menos grande) de partes sino poder generar una lista relativamente aleatoria de cualquier longitud (da igual que necesitemos 5, 100 o 2000 partes)

De especial utilidad serían las funciones definidas en las tareas #69, #94 y #112

**Comment by profeIAP** [comment]
Esta tarea empieza a "apestar" ¿Verdad @Patriexd y @MartaCorzo?

**Comment by semacg98** [comment]
[Aqui](https://docs.google.com/spreadsheets/d/1j1he7cnr2ffUScyKRKwXC16PNKSMm5hVVguPHRv_yHw/edit#gid=0) la dejó, te la he enviado y te he dado permisos @profeIAP  , espero que esté ya bien... si te parece correcta, cierra la tarea, sino ya me dices que puedo corregir ;)

**Comment by profeIAP** [comment]
Para empezar hablaría de _corregir_ la ortografía [ no me lo tomes a mal, estoy obligado a hacerlo ;) ]

No temas cerrar la tarea cuando consideres que está terminada (ya me encargo yo de abrirlo si no es así jejeje)

Te incluyo observaciones en el documento que me has compartido.

Ánimo, ¡está a un 80% terminada la tarea!

**Comment by semacg98** [comment]
Ahora sí, espero que por fin esté bien.. jajaja

**Comment by profeIAP** [comment]
Bien no, está espectacular... ¡Buen trabajo!
