### ISSUE TITLE
Hacer consulta a t_rol

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#372]
Una vez completada la tarea #371, hacer una consulta a t_rol desde index.php en la parte de /usuarios/crear. En la consulta se deberá de seleccionar todas las filas y columnas de dicha tabla.  ([ejemplo](https://github.com/profeIAP/panelDeControl/blob/ecec55da5ae48fc7e8c0c2043d76a52f43f4be20/index.php#L239))

**Comment by profeIAP** [comment]
Cambio el tipo porque realmente estamos obteniendo, desde el controlador, datos de la BD

**Comment by profeIAP** [comment]
@adrivel, recuerda que hay que hacer lo mismo en `/usuarios/editar`

**Comment by profeIAP** [comment]
Añado comentario sobre la propia tarea

**Comment by profeIAP** [comment]
Y perfecto, también... ya tenemos el listado de los roles disponibles en pantalla 👍

![image](https://user-images.githubusercontent.com/16881846/57373615-194e2f00-7199-11e9-9e22-75cb535481a0.png)
