### ISSUE TITLE
Incluir la valores de roles en /usuarios/crear

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#373]
Una vez completada la tarea #372, tendremos que pasar la variable $r a $valores.
Después, deberemos de incluir $valores en el echo, justo como se hace [aquí](https://github.com/profeIAP/panelDeControl/blob/ecec55da5ae48fc7e8c0c2043d76a52f43f4be20/index.php#L240).

**Comment by profeIAP** [comment]
Se la asigno a @marialop7 pues lo está haciendo ya mientras implementa la tarea #372 (no recordaba esta tarea y se la he explicado incluyendo esta funcionalidad 😅)

**Comment by marialop7** [comment]
Cerrada en el commit b9104f64e7d93264b52318c2ac9bd5c93c4e7bb7

**Comment by profeIAP** [comment]
Muy buen trabajo, María
