### ISSUE TITLE
Listar los roles en el seleccionador de perfil en /usuarios/crear

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#374]
Modificar el seleccionador de perfil en /view/usuario.php, de forma que se puedan seleccionar los roles registrados en la tabla t_rol.

Puedes ayudarte de [esto](https://github.com/profeIAP/panelDeControl/blob/ecec55da5ae48fc7e8c0c2043d76a52f43f4be20/view/partes.php#L35).

No funcionará hasta que se complete la tarea #373

**Comment by profeIAP** [comment]
Perfecto Isable, sobre la "bocina", pero perfecto 😉👍
