### ISSUE TITLE
Cambiar el tipo de campo en /view/usuario.php

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#376]
Modificar los campos de "Contraseña" y "Repetir contraseña" en /view/usuario.php [a tipo contraseña](https://www.w3schools.com/tags/att_input_type_password.asp).

**Comment by profeIAP** [comment]
Qué máquina, vas a batir un récord mundial (e histórico) en Programación en esta asignatura 😲

![image](https://user-images.githubusercontent.com/16881846/55398597-3f086880-5549-11e9-974e-b7c0b8ac77cd.png)

Muy buen trabajo, Antonio
