### ISSUE TITLE
Crear la columna de observaciones en la tabla de usuario

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#378]
Crear una columna llamada OBSERVACIONES en la tabla de usuario después de la columna ROL. Deberá de ser tipo TEXT.

**Comment by profeIAP** [comment]
Perfecto Isabel, muy buen trabajo

![image](https://user-images.githubusercontent.com/16881846/55398665-67906280-5549-11e9-8656-02225cee0fef.png)
