### ISSUE TITLE
Mostrar observaciones en editar usuarios (/view/usuario.php)

### ISSUE THREAD

**Issue by adrivel** [profeIAP/proyecto2015-16#379]
Una vez completada la tarea #378, hacer las modificaciones necesarias para que en la edición de usuarios aparezcan observaciones en el campo con id "comentario".

![image](https://user-images.githubusercontent.com/16881846/55252757-e76db280-5253-11e9-914f-d79674c4c56d.png)

Comprobar que se muestran las observaciones editando la columna OBSERVACIONES de alguno de los usuarios de la BD que vayas a editar.

**Comment by profeIAP** [comment]
Aunque con las prisas no hemos visto el nombre correcto del campo, está perfecto MC 👍
