### ISSUE TITLE
Cambiar estética web

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#39]
Devolver los colores y estética de la plantillaWeb compartida por el profesor el trimestre anterior.
No deben aparecer los colores "azulitos" actuales.

**Comment by profeIAP** [comment]
Técnicamente es tan "sencillo" como cambiar el fichero layout.php que tenemos actualmente por el que había en la plantilla que proporcionamos al principio del trimestre pasado.

El contenido de dicho fichero [se encuentra en el repositorio que habilitamos en su día](https://github.com/profeIAP/plantillaWEB/blob/master/view/layout.php)

**OJO:** Las opciones de menú deben ser las que tenemos actualmente en el proyecto

![captura de pantalla de 2016-04-04 19 08 08](https://cloud.githubusercontent.com/assets/16881846/14256263/98594792-fa98-11e5-9c5a-56f2b91f53d0.png)

**Comment by SyalChain** [comment]
@profeIAP No aparece el elemento background en ese fichero; igualmente lo he tomado de la carpeta que conservaba.

**Comment by SyalChain** [comment]
Finiquitado, he liado un poco las cosas al principio pero el último push es el que cuenta.

**Comment by profeIAP** [comment]
Sí que lo has "finiquitado"... sí (yo estoy pensando hacer lo mismo contigo XD )

La idea era volver a un blanco "impoluto" el fondo de la web pero veo que os empeñáis en "empapelarlo" con fondos a cuál más hortera jojojo.

Estoy por "embrearte" por:
1. devolver el fondo azulito de **vuestro** proyecto (que no del mío)
2. Subir al repositorio cosas sin probar... si lo hubieses probado, verías que había una colisión que no has resuelto

![captura de pantalla de 2016-04-15 18 33 03](https://cloud.githubusercontent.com/assets/16881846/14568314/9e96a99e-0338-11e6-9689-7f5ec34df7b6.jpg)

**NOTA:** si el lunes me ves con una brocha y un cubo... corre "insensato" XD

**Comment by SyalChain** [comment]
Fondo eliminado, como acordamos el lunes.

La próxima vez hagamos una tarea para sobrecargar los fondos con imágenes de glitch y mareamos al personal XD

**Comment by profeIAP** [comment]
Pues no es mala idea pero ¿no era una "glitch" el fondo elegido por @mariamiura16? XD
