### ISSUE TITLE
Crear función buscarAsignatura() en parte.php

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#392]
Crear a función javaScript solicitada que, haciendo uso de la [función AJAX de jQuery para realizar peticiones POST](https://www.w3schools.com/jquery/jquery_ajax_get_post.asp) invoque al método `/partes/buscar/asignatura` de la tarea #387 

Deberá proporcionarle los parámetros:
+ `FECHA`
+ `HORA`
+ `GRUPO`

Pero con valores inventados (ya crearemos otra tarea para que se usen los valores correctos)

**Comment by profeIAP** [comment]
Está muy bien Sergio (salvo porque he tenido que ponerle una coma)
Para que esté perfecto, sería interesante que uses datos de verdad: un CURSO como 1º ESO A o una FECHA que no sea el "pato Donald"
Espero a que corrijas dicho tema para poder dar por cerrada la tarea
Gracias, monstuo

**Comment by sergiocabezas** [comment]
Me pone que hay conflictos,lo he intentado subir de todas formas, pero lo he tenido que cerrar desde aqui, nose si se habran subido.

**Comment by profeIAP** [comment]
Desgraciadamente, parece que no ha subido
Asegúrate de haber hecho el `git add` y el `git commit` antes del _push_

![image](https://user-images.githubusercontent.com/16881846/58653332-c38f2180-8315-11e9-8ec3-219d2e142e50.png)

**Comment by profeIAP** [comment]
He añadido comentario sobre el propio commit

**Comment by profeIAP** [comment]
Perfecto, gracias Sergio 👍
