### ISSUE TITLE
Esbozar pantalla parte

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#4]
Esquematizar cómo sería la pantalla para la introducción de partes

**Comment by danigomez99** [comment]
¿Qué tarea tengo que realizar para llevar este proyecto a cabo?

**Comment by profeIAP** [comment]
Pensar...

**Comment by profeIAP** [comment]
@danigomez99 Se te olvidó cerrar la tarea... me "invito" yo ;)
