### ISSUE TITLE
Investigar el hashing de claves

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#41]
La idea es no almacenar directamente en la BD las claves del usuario.
De especial utilidad puede ser [el siguiente enlace](https://josephscott.org/archives/2016/03/password-hashing-examples/).

Deberá desarrollarse un mini ejemplo en el que se pruebe si, la misma clave, al aplicar más de una vez el algoritmo de hashing, genera dos resultados distintos pero da positivo al intentar validar la clave original.

Ejemplo:

encriptar("miClave") = **3eFa012eRTty2** => desencriptar("**3eFa012eRTty2**") = miClave
encriptar("miClave") = **g3450gH54eTRs** => desencriptar("**g3450gH54eTRs**") = miClave

**Comment by jonathan1328** [comment]
@jasvazquez no había una página con un poquitín menos de español?? jajajaj

**Comment by profeIAP** [comment]
Nada como practicar el inglés para coger soltura con el tiempo y la lectura :)

**Comment by jonathan1328** [comment]
@profeIAP ya está acabada, te estoy intentando enviar un pantallazo pero no se guardan los pantallazos

**Comment by profeIAP** [comment]
Los pantallazos, en Guadalinex, se guardan en la carpeta **Imágenes** de tu usuario.
De todos modos, sería mucho mejor que subieses a **index.php** el método que has usado en tus pruebas ¿no te parece?

**Comment by profeIAP** [comment]
Para poder dar por terminada la tarea, necesito que subas el código al repositorio (no olvides incluir en el comentario del commit, el número de la tarea para que aparezca reflejado en esta conversación)

Ánimo que lo que me enseñaste en clase estaba perfecto ;)

**Comment by jonathan1328** [comment]
@profeIAP ya está acabadooooo (llorando), hemos tenido que hacer un clone, después de intentar numerosas opciones.

**Comment by profeIAP** [comment]
Muy pero que muy bien Jonathan, ¡enhorabuena! 

La próxima vez, recuerda poner la almohadilla junto al número de tarea en el comentario d[el commit](https://github.com/profeIAP/panelDeControl/commit/f4ad77f2ea66ec990314a76db78c62f5c429a7a0) para que aparezca reflejado en los comentarios de la tarea
