### ISSUE TITLE
Tabla usuarios

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#42]
Para gestionar las personas que pueden acceder al sistema

**Comment by jasvazquez** [comment]
Antonio, la BD que has subido con el commit, ha eliminado la tabla alumnos... sintiéndolo mucho te va a tocar corregirlo para poder dar por cerrada esta tarea.

Has tenido suerte: aunque ha dejado de funcionar parte de la aplicación (antes de hacer un commit debe comprobarse que todo funciona con normalidad) tiene solución y no es tan grave como para que te peguemos plumas con brea y te paseemos por los pasillos del instituto para que sirva de escarnio a otros compañeros :P

**Comment by profeIAP** [comment]
Reabro la tarea por no haber incluido el script de creación de la tabla en [model/scripts](https://github.com/profeIAP/proyecto2015-16/tree/599ab544ad34a1beebaa7bc6a1749e619018bce7/model/scripts)/usuario.sql

**Comment by antoniio92** [comment]
MAESTRO ESTA HECHO YA!

**Comment by profeIAP** [comment]
Perfecto Antonio, gracias.
