### ISSUE TITLE
Borrar usuario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#43]
Eliminar entrada de la bd

**Comment by profeIAP** [comment]
Necesito que subas el código al repositorio para poder darla por finalizada.

**Comment by mariamiura16** [comment]
cierro la tarea porque ya lo subi ayer.

**Comment by profeIAP** [comment]
Realmente no implementas el borrado de la tabla **usuario**: observa que únicamente [has cambiado hacia dónde se dirige el sistema una vez que se borra un **alumno**](https://github.com/profeIAP/proyecto2015-16/commit/7234203c810deefdd22c43f462fd79a753c1fd77?diff=split#diff-828e0013b8f3bc1bb22b4f57172b019dL102)

Debes crear un método distinto (queremos poder seguir borrrando alumnos) aunque muy parecido (prácticamente cambia el nombre de la tabla)

**Comment by mariamiura16** [comment]
cierro la tarea, ayer lo subí a github

**Comment by profeIAP** [comment]
@mariamiura16 [tu commit de ayer](https://github.com/profeIAP/proyecto2015-16/commit/ba7b1504e615abedb8f5a722c468a63ffb0f74c2) en ningún momento incluye el código necesario para **borrar un usuario**.

Te invito a echar un vistazo al enlace e indicarme dónde se realiza la operación solicitada.

Personalmente creo que andas confundida; si necesitas ayuda [pide "cita"](https://docs.google.com/a/iesalandalus.com/forms/d/1F2aAeLnQPD7WuxDAX9H30LY6x3hLbfHyqdVoMSUOv14/edit?usp=drive_web) y lo vemos ¿te parece?

**Comment by profeIAP** [comment]
Tras hablar contigo, veo que tienes toda la razón del mundo: perdón.
