### ISSUE TITLE
Editar usuario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#44]
Modificar entrada de la bd

**Comment by dnrg98** [comment]
Hecho [en nuestra plantilla](https://github.com/profeIAP/proyecto2015-16/blob/bc3eef999523a4e235054c22b0af00a7bb89f0c7/index.php#L149-L186). Para funcionar en otros proyectos habría que modificar los campos.

**Comment by profeIAP** [comment]
Necesito que subas el código al repositorio para poder dar por cerrada la tarea.

**Comment by dnrg98** [comment]
Subido

**Comment by dnrg98** [comment]
Esta tarea está hecha ya, no se necesita actualizar ya que la hice para hacer la página que estamos utilizando y sigue funcionando

**Comment by profeIAP** [comment]
Dani, no termino de verlo y en el repositorio no parece haber ningún commit tuyo... te apunto para charlar en clase y me lo expliques con detalle ¿te parece?

**Comment by profeIAP** [comment]
Tras hablar, abro la tarea mientras subes el código con los cambios que hemos comentado.

**Comment by profeIAP** [comment]
Sigo sin ver el commit, ¿seguro que has subido los cambios?

**Comment by profeIAP** [comment]
[Encontrado](https://github.com/profeIAP/proyecto2015-16/blob/0a4a69261f4aedcf7b54d004bcfe9ad07f8a93d3/index.php#L253-L289) pero no olvides incluir en el próximo commit el número de la tarea para que aparezca en este hilo.
