### ISSUE TITLE
Documentar la creación de vistas en SQLite

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#46]
Como medio de no incluir complejas consultas en el código fuente de la aplicación

**Comment by FranGarciaCo** [comment]
Muy interesante @profeIAP !!!

**Comment by profeIAP** [comment]
Me alegra que te resulte interesante... lástima que, de momento, no haya propuesto los procedimientos almacenados y/o los 'triggers' ;)

**Comment by FranGarciaCo** [comment]
Finalizado 27-03-16

**Comment by profeIAP** [comment]
Incluidos comentarios sobre posibles mejoras en [el documento que has compartido en drive](https://goo.gl/s5va83)

**Comment by FranGarciaCo** [comment]
Finalizado definitivamente 31-03-16

**Comment by profeIAP** [comment]
Vamos a tener que redefinir el término "finalizado"... deseando estoy de ver el comentario que pondrás en la próxima entrega XD

**Comment by profeIAP** [comment]
Muy buen trabajo "Curro"
