### ISSUE TITLE
Listar ranking de profesores que ponen más partes entre dos fechas

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#49]
Listar, ordenado por número de partes, los profesores que ponen más partes entre dos fechas

**Comment by Tropfer** [comment]
english pls

**Comment by profeIAP** [comment]
It's a nice idea but my students don't speak it fluently ;)

**Comment by SyalChain** [comment]
If you mind, I can help you explain it in class whenever it's needed 👐

**Comment by jasvazquez** [comment]
Thx Emilio but your mates haven't got your English level and this issues
list also it's used at 1° Bach where you cannot (or shouldn't)
explain/translate it ;)

**Comment by flobato322** [comment]
que tengo que hacer en esta tarea?

**Comment by profeIAP** [comment]
Crear una [vista en la BD](https://docs.google.com/a/iesalandalus.com/document/d/1vwjKLieWg3o0dao3fAU072zPCYhkYTxzol-xzbjXkTw/edit?usp=sharing) en la que aparezcan los nombres de los profesores y los partes que han puesto cada unos.

Dicha lista estará ordenada decrecientemente (desde el que pone más partes al que menos)

**Comment by rociodanone3** [comment]
Cierro la tarea gracias EN GRAN PARTE a tu ayuda jejeje GRACIAAAAAAAAAAAAAAAAAAAAAAAS =)

**Comment by profeIAP** [comment]
¿¡¿Y la culpa de no funcionar, también será mía?!? 
Que sepas que espero el "jamón" :P
