### ISSUE TITLE
Esbozar pantalla anotación

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#5]
Esquematizar cómo sería la pantalla donde se anota las entrevistas del jefe de estudios con los alumnos.

Téngase en cuenta que, como mínimos, debe incluir el nombre del alumno que se ha entrevistado, y la fecha de la reunión

**Comment by profeIAP** [comment]
Sube la imagen al documento de requisitos funcionales de la tarea #71

**Comment by rociolm** [comment]
Ya está subida la foto al documento, espero tu valoracion.

**Comment by profeIAP** [comment]
Echo de menos los botones Aceptar/Cancelar pero podemos darla por terminada
