### ISSUE TITLE
Exportar datos a CSV

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#50]
La idea es generar un fichero CSV con los datos de alguna tabla de la BD de modo que pueda ser procesados en otras aplicaciones y/o sistemas.

**Comment by FranGarciaCo** [comment]
Finalizado 7-4-16

**Comment by profeIAP** [comment]
Veo que has mejorado el documento con respecto a la última revisión, gracias.
Aún así, has dejado en el  "tintero" algunas correcciones que se antojan necesarias.
Agradecerías l[e echases un vistazo](https://docs.google.com/document/d/1Dr4NCj_oqf_QmqH7gjsRBrj9shxFlhccWWVTmqBGqUA/edit#) cuando te sea posible para poder dar por finalizada esta "titánica" tarea

**Comment by FranGarciaCo** [comment]
Considero finalizada la tarea.

**Comment by FranGarciaCo** [comment]
Esta tarea, debido a que la orienté hacia la documentación de cómo exportar usando la interfaz de SQLite, le propongo si la puede considerar como ofimática, ya que esta tarea no ha llevado en ningún momento bajar al terreno escarpado de la programación.

**Comment by profeIAP** [comment]
Se acepta la moción
