### ISSUE TITLE
Esbozar pantalla alumno

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#56]
Esquematizar cómo sería la pantalla para editar los datos de un alumno.
**OJO:** debe tenerse en cuenta que ha de mostrar la información indicada en #27

**Comment by angelagr** [comment]
ya está insertada la foto en el drive, espero tu evaluación

**Comment by profeIAP** [comment]
Te incluyo comentarios en el documento

**Comment by angelagr** [comment]
ya he corregido lo que me has dicho

**Comment by profeIAP** [comment]
Casi perfecto Ángela, ¡ánimo!

**Comment by angelagr** [comment]
Ya está corregido

**Comment by jasvazquez** [comment]
Te ha quedado estupendo, gracias Ángela
