### ISSUE TITLE
Esbozar pantalla login

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#6]
Esquematizar cómo sería la pantalla de acceso al sistema.

**Comment by jasvazquez** [comment]
No me canso de ver el resultado, os ha quedado espectacular. Buen trabajo tanto el tuyo como el de @rociomacho, ¡enhorabuena!

Para dar por finalizada la tarea, necesito que subas dicha imagen al correspondiente apartado del documento de requisitos funcionales #71

**Comment by jasvazquez** [comment]
Perfecto
