### ISSUE TITLE
Investigar el autocompletado de campos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#60]
La idea es estudiar cómo hacer que un formulario sugiera valores posibles en base a lo que lleva escrito el usuario.

Sirva a modo de ejemplo [el siguiente código jquery+php](http://goo.gl/q0jnMe)

![Ejemplo autocompletado](https://www.algolia.com/assets/flat2/animated-gif/autocomplete-bd427489ac1457f6dbafc98f604c5fc5.gif)

**Comment by julioosos** [comment]
me la quedo

**Comment by julioosos** [comment]
ya esta , incluso arregle el servidor creo....

**Comment by julioosos** [comment]
por cierto creame la nueva tarea

**Comment by profeIAP** [comment]
Fantástico Julio, aunque estéticamente más feo que el del gif que he puesto de ejemplo funciona a la perfección ¡Enhorabuena!
