### ISSUE TITLE
Generar datos ficticios usuarios

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#61]
Compartir hoja de cálculo en Drive que simule los datos que debe incluir la tabla Usuarios (ver #42)

**Comment by profeIAP** [comment]
Estás acaparando tareas "innecesariamente". Te dejo la de programación y esta te la "quito".
No sufras, voy a crear una tarea de ofimática que te viene que ni "pintada" :)

**Comment by Cesarj9** [comment]
Bieeeen

**Comment by profeIAP** [comment]
Será para Antonio no para ti so "acaparador" :P

**Comment by Cesarj9** [comment]
😢...

**Comment by profeIAP** [comment]
No se busca introducir un listado (más o menos grande) de usuarios sino poder generar una lista relativamente aleatoria de cualquier longitud (da igual que necesitemos 5, 100 o 2000 usuarios)

De especial utilidad serían las funciones definidas en las tareas #69, #94 y #112

**Comment by antoniio92** [comment]
te es suficiente esto datos: 
ID
NOMBRE
EMAIL
CLAVE
o quieres alguno mas?
y la tabla la quieres en tabla de calculo o en lo puedo hacer en documento mejor ?

**Comment by profeIAP** [comment]
Debe contener los datos que indique la tabla Usuario definida en la tarea #42 
Debes anotarlos en una hoja de cálculo de Drive pero los datos deben generarse automáticamente mezclando nombres y apellidos de forma aleatoria para que parezcan más reales (de ahí que sean de especial utilidad las tareas #69, #94 y #112)

**Comment by linanalandalus** [comment]
ya esta terminado aqui te dejo el [enlace del documento](https://docs.google.com/spreadsheets/d/1IbotYATErMMrHEzd27Scoik1Zr8FfsumIEQELBB_j08/edit?usp=sharing)

**Comment by linanalandalus** [comment]
Quiero ya el 11!!!!!!!!! espero que me lo pongas pronto

**Comment by linanalandalus** [comment]
Quiero ya el 11!!!!!!!!! espero que me lo pongas pronto

**Comment by profeIAP** [comment]
Y no te mereces menos Li Nan
Fantástico trabajo, ¡enhorabuena!

No sé si Séneca me dejará ponerte lo que te mereces pero, si no es así, considera que en mi corazón (y mi mente) siempre tendrás dicha puntuación ;)
