### ISSUE TITLE
Documentar la creación de pilotos de datos

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#68]
Explicar en un documento compartido en Google Drive cómo se crea un piloto de datos

**Comment by jasvazquez** [comment]
Li Nan, aunque me has compartido el documento perfectamente, no estaría de mas que se pusiese un comentario aquí y/o se cerrase la tarea (así me saltaría la notificación correspondiente y me facilitaría la gestión de las tareas)

**Comment by linanalandalus** [comment]
esto ya esta terminado como mucho me corriges algun fallo que haya y ya esta

**Comment by profeIAP** [comment]
Lo vuelvo a "matizar"

**Comment by linanalandalus** [comment]
ya acabo de corregirlo todo asi que ya he terminado esta tarea.

**Comment by profeIAP** [comment]
¡Buen trabajo Li Nan!
Comparto [el documento](https://docs.google.com/document/d/1-w5PlYv3WtcMwssuW-Y4XX2K4dS10MVI-UC50lp9usY/edit?usp=sharing) con tus compañeros.
