### ISSUE TITLE
Documentar funcionamiento pantalla login

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#7]
En base al diseño de la pantalla de login #6 indicar cómo sería la interacción del usuario con ella.

**Comment by alexrueda7** [comment]
@profeIAP Ya he terminado, revísalo en el documento de requisitos funcionales.

**Comment by profeIAP** [comment]
Te he incluido algunas recomendaciones pero revisa igualmente el estilo (debe estar todo en presente de indicativo a la hora de expresar la interacción de cada uno de los actores que intervienen)

**Comment by profeIAP** [comment]
La dejo cerrada pero me gustaría que echases un vistazo a las correcciones de "estilo" que te he incluido.
