### ISSUE TITLE
Crear documento requisitos funcionales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#71]
Generar [documento en Google Drive](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit?usp=sharing) (y compartir con el profesor) para la recogida de la especificación funcional del proyecto.

Debe utilizar el formato indicado el trimestre anterior y el esquema que tenemos en la pizarra indicando los proyectos que han sido fusionados en el proyecto actual.

**Comment by josufg** [comment]
Hecho maestro @jasvazquez , ya tranquilamente la observas.

**PD:** Ahora que tengo hecha esta me voy a coger la tarea #77  (añadir datos del proyecto de Huella Dactilar) ya que lo complementa.

**Comment by profeIAP** [comment]
Josué, incluye en el documento el esquema que tenemos en la pizarra sobre cómo han sido integrados los distintos proyectos que teníamos.

Considero que el apartado "Proyectos anteriores" es el lugar ideal ¿no te parece?

**Comment by profeIAP** [comment]
@josufg No entiendo por qué has soltado la tarea cuando sólo te queda poder el diagrama que tenemos en la pizarra. Has hecho todo el trabajo ¿por qué abandonar al final?

A @MartaCorzo le viene de lujo pero considero que la tarea está prácticamente finalizada a falta del último "fleco" ¿no os parece?

**Comment by profeIAP** [comment]
@josufg Todavía no has contestado... ¿Terminarás la tarea?

**Comment by josufg** [comment]
No me di cuenta @profeIAP intentaré arreglarlo

**Comment by profeIAP** [comment]
Lo imagino, andamos demasiado centrados (que no es mala señal) en el trabajo actual.
No corre excesiva prisa, pero no lo dejes nuevamente olvidado.
Gracias Josué

**Comment by josufg** [comment]
@profeIAP ¿Qué falta hacer?

**Comment by profeIAP** [comment]
Entiendo que has resuelto la duda en el momento que has venido a la pizarra por la imagen ¿verdad?

**Comment by josufg** [comment]
Terminada @profeIAP . Ya están en el orden del diagrama. La cierro.

**Comment by profeIAP** [comment]
Josué, no veo el esquema en el documento.
Observo que has estado haciendo cambios en el apartado "proyectos anteriores" pero falta la imagen ¿?

**Comment by josufg** [comment]
@profeIAP No sabía que debía añadir la imagen

**Comment by josufg** [comment]
@profeIAP Ya he añadido la imagen del diagrama para que la gente pueda observarlo y he cambiado algunas cosillas con respecto a la imagen. ¿La puedo cerrar?

**Comment by profeIAP** [comment]
[Ha quedado](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.p9fdyjcy0rgz) muy bien pero recorta la imagen para que no tenga tanto espacio "en blanco" por debajo.
Gracias

**Comment by josufg** [comment]
Vale @profeIAP

**Comment by josufg** [comment]
Ya @profeIAP

**Comment by profeIAP** [comment]
Ha quedado estupendo, gracias Josué
