### ISSUE TITLE
Añadir datos proyecto Outfit al documento de requisitos funcionales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#72]
Deberán incluirse los enlaces a las redes sociales, github y blog junto a una pequeña descripción de cuál era la finalidad del proyecto en el documento de requisitos funcionales creado en la tarea #71

**Comment by fran98moreno** [comment]
hecho por mi hoy :)

**Comment by fran98moreno** [comment]
Fix

**Comment by profeIAP** [comment]
Pequeñas correcciones; agradecería le echases un vistazo

**Comment by profeIAP** [comment]
Estupendo
