### ISSUE TITLE
Añadir datos proyecto Pártete al documento de requisitos funcionales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#74]
Deberán incluirse los enlaces a las redes sociales, github y blog junto a una pequeña descripción de cuál era la finalidad del proyecto en el documento de requisitos funcionales creado en la tarea #71

**Comment by mariamiura16** [comment]
Ya he realizado la tarea y te la envio por email

**Comment by jasvazquez** [comment]
No está maquetado correctamente (hay iconos y textos en líneas distintas, se usan estilos de "Título" dentro de párrafos, ...)

Dale un pequeño repaso y cerramos la tarea ¿te parece?

**Comment by mariamiura16** [comment]
Ya está solucionado, a la espera de que me digas si lo dejo así o lo cambio, con respecto al resultado de la encuesta que quieres realizar.

**Comment by profeIAP** [comment]
No te preocupes: lo dejamos como está pues os ha quedado muy bien.
Si realizamos la encuesta, ya crearemos una tarea para que alguien se encargue de unificar los estilos existentes ¿te parece? ;)
