### ISSUE TITLE
Añadir datos proyecto UpMyMusic al documento de requisitos funcionales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#75]
Deberán incluirse los enlaces a las redes sociales, github y blog junto a una pequeña descripción de cuál era la finalidad del proyecto en el documento de requisitos funcionales creado en la tarea #71

**Comment by ghost** [comment]
Ya está realizada la tarea @jasvazquez . Voy a por otra #20

**Comment by profeIAP** [comment]
La dejo cerrada pues te ha quedado muy bien la descripción del proyecto. 
Te he incluido una sugerencia en el documento que espera tu revisión.
Buen trabajo, Fco.
