### ISSUE TITLE
Añadir datos proyecto Brothers Barbu documento de requisitos funcionales

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#76]
Deberán incluirse los enlaces a las redes sociales, github y blog junto a una pequeña descripción de cuál era la finalidad del proyecto en el documento de requisitos funcionales creado en la tarea #71

**Comment by profeIAP** [comment]
Abro la tarea pues existe una pequeña corrección en el documento

**Comment by angel2190** [comment]
Ya he hecho las correcciones. Miralo para ver si ya esta bien y pueda cerrar la tarea.

**Comment by profeIAP** [comment]
Para futuras tareas, no temas cerrarla cuando consideres que está terminada [ si no lo estuviese, ya me encargaré yo de abrirla ;) ]

Buen trabajo, Ángel
