### ISSUE TITLE
Cambiar logotipo por el de Pártete

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#8]
Deberá buscarse en el repositorio del grupo y modificar layout.php en nuestro proyecto.

**Comment by profeIAP** [comment]
El código de dicho proyecto se encuentra en https://github.com/pablosaborido/informatica-2bach-c.git

**Comment by manu21499** [comment]
Ya he acabado la tarea que me ha asignado @jasvazquez

**Comment by jasvazquez** [comment]
En realidad te lo ha asignado @profeIAP ;)

**Comment by profeIAP** [comment]
Debes subir los cambios en el código fuente al repositorio de GitHub

**Comment by profeIAP** [comment]
En la última versión del código fuente aparece el mismo logotipo de siempre en lugar de el nuevo

**Comment by mariamiura16** [comment]
la haces tu o la hago yo? es para hoy!! que llevas 23 días para hacerla

**Comment by manu21499** [comment]
ya he subido los cambios al git hub @profeIAP

**Comment by profeIAP** [comment]
Nos hemos dado cuenta "todos" Manu XO

![captura de pantalla de 2016-04-06 15 41 29](https://cloud.githubusercontent.com/assets/16881846/14318649/30f0cbc6-fc0e-11e5-9962-3ec43f05054f.png)

**Comment by mariamiura16** [comment]
no está hecho, solo esta cambiado el fondo y lo he hecho yo, la imagen sigue sin aparecer.

**Comment by profeIAP** [comment]
Como no funcionaba lo que hizo @manu21499 he deshecho el commit para que no afecte al resto del equipo de trabajo.

Hasta mañana no tienen clase ellos; esperemos contar con el nuevo logo antes del lunes ¿te parece? ;)

**Comment by profeIAP** [comment]
@manu21499 esta tarea la has dejado sin terminar. Yo corregí el "estropicio" pero no hice la tarea: si observas, el logo actualmente es el antiguo.

¿Puede cogerla @mariamiura16 o has quitado tu asignación por error?

**Comment by profeIAP** [comment]
Aquí tienes [la imagen](https://github.com/pablosaborido/informatica-2bach-c/blob/master/img/icono.jpg)

**Comment by profeIAP** [comment]
No has subido tus cambios al repositorio ¿has hecho [el git push](https://github.com/profeIAP/proyecto2015-16/wiki#subida)?

**Comment by profeIAP** [comment]
Comportamiento altamente irregular... sospecho que: 
1. @javierfl98 
2. @mariamiura16 

vais a aparecer próximamente en la tarea #150 de @fran98moreno
