### ISSUE TITLE
Subida de ficheros al servidor

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#84]
Estudiar (e implementar prueba) para subir imágenes al directorio _/img_ del servidor

**Comment by profeIAP** [comment]
Recomendaría buscar ejemplo de subida de ficheros utilizando Slim Framework

**Comment by FranGarciaCo** [comment]
Hola, te referías a esta tarea?

**Comment by profeIAP** [comment]
Efectivamente: una tarea digna de tu "pericia" :)

**Comment by FranGarciaCo** [comment]
Hay tareas, como esta, que necesitan algo más que pericia. ¿Me sugiere algunos enlaces concretos que me ayuden a enfocar correctamente la tarea?

**Comment by profeIAP** [comment]
La tarea de investigación era (y es) parte del proceso.
Como comenté en clase creo recordar que tengo implementado algo parecido en un proyecto "alternativo" que compartí con [vuestros compañeros del Lector de Huellas](http://semillerodeempresas.blogspot.com.es/search/label/LectorID)

Si encuentro la oportunidad, te lo comparto...

**Comment by profeIAP** [comment]
Quizás te sea de utilidad [el siguiente ejemplo](http://www.w3schools.com/php/php_file_upload.asp)

Para adaptarlo a nuestro proyecto tienes que:
1. meter una nueva vista (hay un ejemplo en el enlace) para el formulario que permitirá la subida de fichero.
2. incluir el código que aparece al final del artículo (Complete Upload File PHP Script) dentro de un método post de nuestro index.php [ $app->post('/LoQueHayasPuestoEnElActionDelFormulario') ]

**Comment by FranGarciaCo** [comment]
He finalizado la tarea, espero no aparecer de nuevo en el Hall Of Blame.

**Comment by FranGarciaCo** [comment]
Solicitud formal, cree una tarea para mí... Quiero "hacer" un código "completo" entre la subida y el importar...

**Comment by profeIAP** [comment]
Formalmente hablando, se debería utilizar el término "funcionalidad" en lugar de "código 'completo'", no obstante se entiende la esencia (y el fondo) de la petición
