### ISSUE TITLE
Estudiar cómo insertar datos de prueba en la BD

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#87]
Buscar el modo de importar en una tabla de SQLite los datos generados en la hoja de cálculo de Google Drive

**Comment by profeIAP** [comment]
¿Alguna "prueba" que valide el cierre de la tarea? :)

**Comment by AbrahamgcArahal** [comment]
![tarea 87](https://cloud.githubusercontent.com/assets/15833009/14597446/0e8cc90c-054d-11e6-8357-2c6de44177ea.png)

En esta imagen te muestro una tabla que cree en drive y la tabla en SQlite con dichos datos

**Comment by profeIAP** [comment]
Cuenta brevemente el procedimiento seguido para lograrlo... ¿has optado por escribir los datos tanto en la BD como en Drive? :P

**Comment by profeIAP** [comment]
Gracias Abraham
