### ISSUE TITLE
Documentar cómo incluir dependencias en el proyecto

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#89]
Crear [documento compartido en Google Drive](https://docs.google.com/document/d/1WN_R6ZfHQ1MyG2F2XQHypQz0pAxqNSVHXV_fXLk7xxE/edit?usp=sharing) donde se especifique cómo añadir al fichero _composer.json_ versiones concretas de librerías de las que dependa el proyecto (como p.e. phpunit o slim)

**Comment by profeIAP** [comment]
César, te quito esta tarea porque ya tienes otra asignada y hemos comentado que no se debe acaparar tareas que no se van a abordar inmediatamente (no vale "bloquear" trabajos)

**Comment by julioosos** [comment]
Ya está hecho

**Comment by profeIAP** [comment]
Cuasi perfecto... incluyo comentario nímio

**Comment by julioosos** [comment]
ya está  corregido

**Comment by profeIAP** [comment]
Recortar imágenes no parece estar entre tus habilidades personales XD
Te dejo referencia en los comentarios para que quede perfecto.

**Comment by julioosos** [comment]
No estaba entre mis habilidades pero ya se encuentra en ellas XD

**Comment by profeIAP** [comment]
De eso se trata... de aprender, ¡sigue así que estás "creciendo"! (por fortuna, metafóricamente hablando ;) )

Muy buen trabajo

**Comment by julioosos** [comment]
Gracias, la verdad es que estoy aprendiendo mas que si solo le hubiera dicho al pape que me lo hiciera.
Pd:El pique sano es bueno (quiero ganarle) XD

**Comment by profeIAP** [comment]
Me alegra que haya sana rivalidad y ganas de mejorar... los dos estáis haciendo grandes avances ¿Demostrará @carlosaj98 de lo que realmente es capaz? ;P

**Comment by julioosos** [comment]
Carlos tiene dos modos: "focuson" y "focusout" durante el segundo trimestre estaba "focuson" ahora "parece" "focusout" XD (empleando lo aprendido hoy en clase de info sobre el "focusout")
