### ISSUE TITLE
Crear plantilla para documentar funcionalidad

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#9]
Diseñar el formato que deben seguir todos los documentos en los que se especifique el comportamiento de algún formulario de la web

**Comment by profeIAP** [comment]
Comparte en cuanto te sea posible (aunque no esté terminado) para que otros compañeros puedan realizar su trabajo sobre este documento

**Comment by profeIAP** [comment]
El formato que especifiques debe incluirse en el documento de la tarea #71

**Comment by profeIAP** [comment]
El documento base que debes utilizar es [el de Requisitos funcionales](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#heading=h.62icp9df6foo)

Utiliza el apartado "Historias de usuario"

**Comment by profeIAP** [comment]
Sirva como modelo el [formato utilizado en el mantenimiento de usuarios](https://docs.google.com/document/d/1y0PcZjIyRoMCnXRP4bMX14R6VTI2JBbB28YqFxyJuLU/edit#bookmark=id.yyjepx322v4k)

**Comment by profeIAP** [comment]
Te incluyo pequeñas correcciones de "estilo" en el documento.

Dejo la tarea para que te tomes la molestia de revisarlos y te familiarices con el lenguaje y la estructura (recuerda que vas a ser el "referente" en este tipo de tareas :P)

**Comment by Cesarj9** [comment]
Sin problemas, lo mirare cuando me levante del banco ;D
Cj9

**Comment by profeIAP** [comment]
Ok, damos por finalizada la tarea.
Gracias César
