### ISSUE TITLE
Documentar cómo mostrar un calendario en un formulario

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#92]
Crear documento compartido en Google Drive que indique cómo utilizar el plugin jQuery para introducir fechas estuadiado en la tarea #91

**Comment by profeIAP** [comment]
El [documento compartido](https://drive.google.com/open?id=1p_7TAdO4UqkZjQ58ORcNg50pqokmVFzv9oRKSxKwTow) requiere algunas 'mejoras'

**Comment by profeIAP** [comment]
Algunos de los comentarios de la revisión anterior no han sido abordados.

**Comment by profeIAP** [comment]
Faltan detalles nimios

**Comment by profeIAP** [comment]
Sigue faltando el detalle de explicar cómo se marca una caja de texto para que pueda utilizarse con ella el calendario

**Comment by profeIAP** [comment]
Te dejo la "pista" definitiva... suerte

**Comment by marialuisapf** [comment]
vale, ya, creo que está terminado

**Comment by profeIAP** [comment]
Reajusto el anexo final y doy por cerrada la tarea.

Gracias por la "profesionalidad" mostrada Mª Luisa

**Comment by marialuisapf** [comment]
Gracias

**Comment by profeIAP** [comment]
A ti
