### ISSUE TITLE
Documentar cómo mejorar la calidad de las imágenes escaneadas

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#93]
Técnica utilizada habitualmente para la aplicación de algoritmos de OCR a documentos de texto.

La idea es poder utilizar dicha mejora de las imágenes en los dibujos de pantallas de usuario que vamos a incluir en la documentación del proyecto.

http://goo.gl/eGTxhr
http://goo.gl/kDA8HB

**Comment by profeIAP** [comment]
Interesante [plugin de Gimp](http://graphicdesign.stackexchange.com/a/20482) para la mejora de imágenes

**Comment by jasvazquez** [comment]
Te he dejado algunas sugerencias en el documento que me has compartido.
Tiene muy buena pinta, enhorabuena.

**Comment by profeIAP** [comment]
Está casi perfecto pero quedan por pulir algunos detalles para que sea un digno tutorial.

**Comment by profeIAP** [comment]
Comparto [el documento](https://docs.google.com/document/d/1Xau2T5XaZFE-t_tYxTCcDu7N6eDoiZWnX1WUEbKzE98/edit) con tus compañeros a falta de revisarlo

**Comment by profeIAP** [comment]
Ya casi está terminado, ¡ánimo!

**Comment by profeIAP** [comment]
No tengo claro que entiendas el funcionamiento de los encabezados en un documento (o tienes un problema grave con las "jerarquías" :P)

Así que te lo dejo pendiente de corregir ese detalle nimio.

El documento ha quedado espectacular

**Comment by profeIAP** [comment]
Vuelvo a abrir por no haber corregido el detalle que nos faltaba :(

**Comment by profeIAP** [comment]
Enhorabuena Rocío... un fantástico trabajo tanto de investigación como de documentación.
Puedes sentirte realmente orgullosa ;)
