### ISSUE TITLE
Documentar cómo insertar imágenes en GitHub

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#98]
Crear documento compartido en Google Drive donde se explique cómo lograr que aparezcan imágenes en los comentarios de Google Drive tal y como se hace en la tarea #91

**Comment by profeIAP** [comment]
Sería de utilidad consultar [la sintaxis de MarkDown](https://guides.github.com/features/mastering-markdown/)

**Comment by Raul-99** [comment]
[hola]
(https://cloud.githubusercontent.com/assets/15778013/14141050/ecde6ae2-f67c-11e5-9bc6-1941400af0eb.jpeg)

**Comment by Raul-99** [comment]
pincha para ver la [imagen](https://cloud.githubusercontent.com/assets/15778013/14141077/1694e8de-f67d-11e5-9e7d-ff3883ba1523.jpeg)

**Comment by profeIAP** [comment]
No está mal pero la idea es que la imagen se vea dentro del comentario como la que puedes observar debajo de estas líneas

![](https://cloud.githubusercontent.com/assets/15778013/14141077/1694e8de-f67d-11e5-9e7d-ff3883ba1523.jpeg)

**Comment by Raul-99** [comment]
Así está bien
![images](https://cloud.githubusercontent.com/assets/15778013/14199581/f60f8da2-f7e5-11e5-8d0a-18cd35b279bd.jpeg)

**Comment by Raul-99** [comment]
ya esta echa esta tarea. @profeIAP

**Comment by profeIAP** [comment]
Aunque te he puesto un comentario en [el documento que me has compartido](https://drive.google.com/open?id=1wIzd-3TnSPfyHgHr2VVXIzSq_dTw0IDkzQ02GgsIcPU)...
![175218326-640x427](https://cloud.githubusercontent.com/assets/16881846/14209848/7394b8ca-f826-11e5-9850-84024e01bf7b.jpg)

**Comment by Raul-99** [comment]
Arreglado

**Comment by profeIAP** [comment]
Te incluyo comentario sobre el enlace que has proporcionado a MarkDown

**Comment by profeIAP** [comment]
Buen trabajo Raúl, damos por cerrada la tarea.
No obstante, echa un vistazo al documento pues he incluido un par de cambios que necesito que aceptes
