### ISSUE TITLE
Generar formulario para solicitar "cita previa"

### ISSUE THREAD

**Issue by profeIAP** [profeIAP/proyecto2015-16#99]
Generar en Google Drive un formulario que nos permita indicar (desde nuestro sitio) al profesor que queremos que nos resuelva una duda evitando tener que utilizar el papel y el lápiz que venimos usando hasta ahora

**Comment by jasvazquez** [comment]
Probado el formulario en otro ordenador con distinta resolución y sigue viéndose igual que en el de clase. 

Algunos sugieren que [la imagen debe ser de 500x125px](https://productforums.google.com/d/msg/docs/dx4AkVWw9xo/WlTvZlfbfeoJ)

**Comment by profeIAP** [comment]
Pablo, no encuentro el formulario ¿has dejado de compartir el documento?

**Comment by profeIAP** [comment]
Gracias por compartírmelo.
Ya [lo estamos usando](https://drive.google.com/open?id=1F2aAeLnQPD7WuxDAX9H30LY6x3hLbfHyqdVoMSUOv14) y va genial ;)
Sólo queda cambiar la imagen para poder dar por cerrada la tarea, ¡buen trabajo!

**Comment by profeIAP** [comment]
Sigue con la imagen mal... no puedo aceptar el cierre de la tarea (sorry)

**Comment by profeIAP** [comment]
Lo daremos por bueno a pesar de:
1. estar la imagen borrosa
2. no poder leerse el texto
